// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: dev_observer/api/web/observations.proto

package service

import (
	contextify "github.com/devplaninc/contextify/clients/go/contextify"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetObservationsResponse struct {
	state           protoimpl.MessageState        `protogen:"opaque.v1"`
	xxx_hidden_Keys *[]*contextify.ObservationKey `protobuf:"bytes,1,rep,name=keys,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetObservationsResponse) Reset() {
	*x = GetObservationsResponse{}
	mi := &file_dev_observer_api_web_observations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObservationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObservationsResponse) ProtoMessage() {}

func (x *GetObservationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_web_observations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetObservationsResponse) GetKeys() []*contextify.ObservationKey {
	if x != nil {
		if x.xxx_hidden_Keys != nil {
			return *x.xxx_hidden_Keys
		}
	}
	return nil
}

func (x *GetObservationsResponse) SetKeys(v []*contextify.ObservationKey) {
	x.xxx_hidden_Keys = &v
}

type GetObservationsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Keys []*contextify.ObservationKey
}

func (b0 GetObservationsResponse_builder) Build() *GetObservationsResponse {
	m0 := &GetObservationsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Keys = &b.Keys
	return m0
}

type GetObservationResponse struct {
	state                  protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_Observation *contextify.Observation `protobuf:"bytes,1,opt,name=observation,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetObservationResponse) Reset() {
	*x = GetObservationResponse{}
	mi := &file_dev_observer_api_web_observations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObservationResponse) ProtoMessage() {}

func (x *GetObservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_web_observations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetObservationResponse) GetObservation() *contextify.Observation {
	if x != nil {
		return x.xxx_hidden_Observation
	}
	return nil
}

func (x *GetObservationResponse) SetObservation(v *contextify.Observation) {
	x.xxx_hidden_Observation = v
}

func (x *GetObservationResponse) HasObservation() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Observation != nil
}

func (x *GetObservationResponse) ClearObservation() {
	x.xxx_hidden_Observation = nil
}

type GetObservationResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Observation *contextify.Observation
}

func (b0 GetObservationResponse_builder) Build() *GetObservationResponse {
	m0 := &GetObservationResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Observation = b.Observation
	return m0
}

type GetProcessingResultsRequest struct {
	state               protoimpl.MessageState             `protogen:"opaque.v1"`
	xxx_hidden_FromDate *timestamppb.Timestamp             `protobuf:"bytes,1,opt,name=from_date,json=fromDate,proto3,oneof"`
	xxx_hidden_ToDate   *timestamppb.Timestamp             `protobuf:"bytes,2,opt,name=to_date,json=toDate,proto3,oneof"`
	xxx_hidden_Filter   *contextify.ProcessingResultFilter `protobuf:"bytes,3,opt,name=filter,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetProcessingResultsRequest) Reset() {
	*x = GetProcessingResultsRequest{}
	mi := &file_dev_observer_api_web_observations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessingResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessingResultsRequest) ProtoMessage() {}

func (x *GetProcessingResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_web_observations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetProcessingResultsRequest) GetFromDate() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_FromDate
	}
	return nil
}

func (x *GetProcessingResultsRequest) GetToDate() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ToDate
	}
	return nil
}

func (x *GetProcessingResultsRequest) GetFilter() *contextify.ProcessingResultFilter {
	if x != nil {
		return x.xxx_hidden_Filter
	}
	return nil
}

func (x *GetProcessingResultsRequest) SetFromDate(v *timestamppb.Timestamp) {
	x.xxx_hidden_FromDate = v
}

func (x *GetProcessingResultsRequest) SetToDate(v *timestamppb.Timestamp) {
	x.xxx_hidden_ToDate = v
}

func (x *GetProcessingResultsRequest) SetFilter(v *contextify.ProcessingResultFilter) {
	x.xxx_hidden_Filter = v
}

func (x *GetProcessingResultsRequest) HasFromDate() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_FromDate != nil
}

func (x *GetProcessingResultsRequest) HasToDate() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ToDate != nil
}

func (x *GetProcessingResultsRequest) HasFilter() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Filter != nil
}

func (x *GetProcessingResultsRequest) ClearFromDate() {
	x.xxx_hidden_FromDate = nil
}

func (x *GetProcessingResultsRequest) ClearToDate() {
	x.xxx_hidden_ToDate = nil
}

func (x *GetProcessingResultsRequest) ClearFilter() {
	x.xxx_hidden_Filter = nil
}

type GetProcessingResultsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Defaults to "to - 7d"
	FromDate *timestamppb.Timestamp
	// Default to "now"
	ToDate *timestamppb.Timestamp
	Filter *contextify.ProcessingResultFilter
}

func (b0 GetProcessingResultsRequest_builder) Build() *GetProcessingResultsRequest {
	m0 := &GetProcessingResultsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_FromDate = b.FromDate
	x.xxx_hidden_ToDate = b.ToDate
	x.xxx_hidden_Filter = b.Filter
	return m0
}

type GetProcessingResultsResponse struct {
	state              protoimpl.MessageState              `protogen:"opaque.v1"`
	xxx_hidden_Results *[]*contextify.ProcessingItemResult `protobuf:"bytes,1,rep,name=results,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetProcessingResultsResponse) Reset() {
	*x = GetProcessingResultsResponse{}
	mi := &file_dev_observer_api_web_observations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessingResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessingResultsResponse) ProtoMessage() {}

func (x *GetProcessingResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_web_observations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetProcessingResultsResponse) GetResults() []*contextify.ProcessingItemResult {
	if x != nil {
		if x.xxx_hidden_Results != nil {
			return *x.xxx_hidden_Results
		}
	}
	return nil
}

func (x *GetProcessingResultsResponse) SetResults(v []*contextify.ProcessingItemResult) {
	x.xxx_hidden_Results = &v
}

type GetProcessingResultsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Results []*contextify.ProcessingItemResult
}

func (b0 GetProcessingResultsResponse_builder) Build() *GetProcessingResultsResponse {
	m0 := &GetProcessingResultsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Results = &b.Results
	return m0
}

type GetProcessingResultResponse struct {
	state             protoimpl.MessageState           `protogen:"opaque.v1"`
	xxx_hidden_Result *contextify.ProcessingItemResult `protobuf:"bytes,1,opt,name=result,proto3,oneof"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetProcessingResultResponse) Reset() {
	*x = GetProcessingResultResponse{}
	mi := &file_dev_observer_api_web_observations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessingResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessingResultResponse) ProtoMessage() {}

func (x *GetProcessingResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_web_observations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetProcessingResultResponse) GetResult() *contextify.ProcessingItemResult {
	if x != nil {
		return x.xxx_hidden_Result
	}
	return nil
}

func (x *GetProcessingResultResponse) SetResult(v *contextify.ProcessingItemResult) {
	x.xxx_hidden_Result = v
}

func (x *GetProcessingResultResponse) HasResult() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Result != nil
}

func (x *GetProcessingResultResponse) ClearResult() {
	x.xxx_hidden_Result = nil
}

type GetProcessingResultResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Result *contextify.ProcessingItemResult
}

func (b0 GetProcessingResultResponse_builder) Build() *GetProcessingResultResponse {
	m0 := &GetProcessingResultResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Result = b.Result
	return m0
}

type CreateProcessingItemRequest struct {
	state                         protoimpl.MessageState         `protogen:"opaque.v1"`
	xxx_hidden_Key                *contextify.ProcessingItemKey  `protobuf:"bytes,1,opt,name=key,proto3"`
	xxx_hidden_ProcessImmediately bool                           `protobuf:"varint,2,opt,name=process_immediately,json=processImmediately,proto3"`
	xxx_hidden_Data               *contextify.ProcessingItemData `protobuf:"bytes,3,opt,name=data,proto3"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *CreateProcessingItemRequest) Reset() {
	*x = CreateProcessingItemRequest{}
	mi := &file_dev_observer_api_web_observations_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProcessingItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProcessingItemRequest) ProtoMessage() {}

func (x *CreateProcessingItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_web_observations_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateProcessingItemRequest) GetKey() *contextify.ProcessingItemKey {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return nil
}

func (x *CreateProcessingItemRequest) GetProcessImmediately() bool {
	if x != nil {
		return x.xxx_hidden_ProcessImmediately
	}
	return false
}

func (x *CreateProcessingItemRequest) GetData() *contextify.ProcessingItemData {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *CreateProcessingItemRequest) SetKey(v *contextify.ProcessingItemKey) {
	x.xxx_hidden_Key = v
}

func (x *CreateProcessingItemRequest) SetProcessImmediately(v bool) {
	x.xxx_hidden_ProcessImmediately = v
}

func (x *CreateProcessingItemRequest) SetData(v *contextify.ProcessingItemData) {
	x.xxx_hidden_Data = v
}

func (x *CreateProcessingItemRequest) HasKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Key != nil
}

func (x *CreateProcessingItemRequest) HasData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Data != nil
}

func (x *CreateProcessingItemRequest) ClearKey() {
	x.xxx_hidden_Key = nil
}

func (x *CreateProcessingItemRequest) ClearData() {
	x.xxx_hidden_Data = nil
}

type CreateProcessingItemRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key                *contextify.ProcessingItemKey
	ProcessImmediately bool
	Data               *contextify.ProcessingItemData
}

func (b0 CreateProcessingItemRequest_builder) Build() *CreateProcessingItemRequest {
	m0 := &CreateProcessingItemRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Key = b.Key
	x.xxx_hidden_ProcessImmediately = b.ProcessImmediately
	x.xxx_hidden_Data = b.Data
	return m0
}

type CreateProcessingItemResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProcessingItemResponse) Reset() {
	*x = CreateProcessingItemResponse{}
	mi := &file_dev_observer_api_web_observations_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProcessingItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProcessingItemResponse) ProtoMessage() {}

func (x *CreateProcessingItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_web_observations_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type CreateProcessingItemResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 CreateProcessingItemResponse_builder) Build() *CreateProcessingItemResponse {
	m0 := &CreateProcessingItemResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type DeleteProcessingItemRequest struct {
	state          protoimpl.MessageState        `protogen:"opaque.v1"`
	xxx_hidden_Key *contextify.ProcessingItemKey `protobuf:"bytes,1,opt,name=key,proto3"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteProcessingItemRequest) Reset() {
	*x = DeleteProcessingItemRequest{}
	mi := &file_dev_observer_api_web_observations_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProcessingItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProcessingItemRequest) ProtoMessage() {}

func (x *DeleteProcessingItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_web_observations_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteProcessingItemRequest) GetKey() *contextify.ProcessingItemKey {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return nil
}

func (x *DeleteProcessingItemRequest) SetKey(v *contextify.ProcessingItemKey) {
	x.xxx_hidden_Key = v
}

func (x *DeleteProcessingItemRequest) HasKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Key != nil
}

func (x *DeleteProcessingItemRequest) ClearKey() {
	x.xxx_hidden_Key = nil
}

type DeleteProcessingItemRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key *contextify.ProcessingItemKey
}

func (b0 DeleteProcessingItemRequest_builder) Build() *DeleteProcessingItemRequest {
	m0 := &DeleteProcessingItemRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Key = b.Key
	return m0
}

type DeleteProcessingItemResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProcessingItemResponse) Reset() {
	*x = DeleteProcessingItemResponse{}
	mi := &file_dev_observer_api_web_observations_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProcessingItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProcessingItemResponse) ProtoMessage() {}

func (x *DeleteProcessingItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_web_observations_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DeleteProcessingItemResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DeleteProcessingItemResponse_builder) Build() *DeleteProcessingItemResponse {
	m0 := &DeleteProcessingItemResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetProcessingRunStatusResponse struct {
	state             protoimpl.MessageState           `protogen:"opaque.v1"`
	xxx_hidden_Result *contextify.ProcessingItemResult `protobuf:"bytes,1,opt,name=result,proto3,oneof"`
	xxx_hidden_Item   *contextify.ProcessingItem       `protobuf:"bytes,2,opt,name=item,proto3,oneof"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetProcessingRunStatusResponse) Reset() {
	*x = GetProcessingRunStatusResponse{}
	mi := &file_dev_observer_api_web_observations_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessingRunStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessingRunStatusResponse) ProtoMessage() {}

func (x *GetProcessingRunStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_web_observations_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetProcessingRunStatusResponse) GetResult() *contextify.ProcessingItemResult {
	if x != nil {
		return x.xxx_hidden_Result
	}
	return nil
}

func (x *GetProcessingRunStatusResponse) GetItem() *contextify.ProcessingItem {
	if x != nil {
		return x.xxx_hidden_Item
	}
	return nil
}

func (x *GetProcessingRunStatusResponse) SetResult(v *contextify.ProcessingItemResult) {
	x.xxx_hidden_Result = v
}

func (x *GetProcessingRunStatusResponse) SetItem(v *contextify.ProcessingItem) {
	x.xxx_hidden_Item = v
}

func (x *GetProcessingRunStatusResponse) HasResult() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Result != nil
}

func (x *GetProcessingRunStatusResponse) HasItem() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Item != nil
}

func (x *GetProcessingRunStatusResponse) ClearResult() {
	x.xxx_hidden_Result = nil
}

func (x *GetProcessingRunStatusResponse) ClearItem() {
	x.xxx_hidden_Item = nil
}

type GetProcessingRunStatusResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Result *contextify.ProcessingItemResult
	Item   *contextify.ProcessingItem
}

func (b0 GetProcessingRunStatusResponse_builder) Build() *GetProcessingRunStatusResponse {
	m0 := &GetProcessingRunStatusResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Result = b.Result
	x.xxx_hidden_Item = b.Item
	return m0
}

type GetProcessingItemsRequest struct {
	state             protoimpl.MessageState            `protogen:"opaque.v1"`
	xxx_hidden_Filter *contextify.ProcessingItemsFilter `protobuf:"bytes,1,opt,name=filter,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetProcessingItemsRequest) Reset() {
	*x = GetProcessingItemsRequest{}
	mi := &file_dev_observer_api_web_observations_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessingItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessingItemsRequest) ProtoMessage() {}

func (x *GetProcessingItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_web_observations_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetProcessingItemsRequest) GetFilter() *contextify.ProcessingItemsFilter {
	if x != nil {
		return x.xxx_hidden_Filter
	}
	return nil
}

func (x *GetProcessingItemsRequest) SetFilter(v *contextify.ProcessingItemsFilter) {
	x.xxx_hidden_Filter = v
}

func (x *GetProcessingItemsRequest) HasFilter() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Filter != nil
}

func (x *GetProcessingItemsRequest) ClearFilter() {
	x.xxx_hidden_Filter = nil
}

type GetProcessingItemsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Filter *contextify.ProcessingItemsFilter
}

func (b0 GetProcessingItemsRequest_builder) Build() *GetProcessingItemsRequest {
	m0 := &GetProcessingItemsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Filter = b.Filter
	return m0
}

type GetProcessingItemsResponse struct {
	state            protoimpl.MessageState        `protogen:"opaque.v1"`
	xxx_hidden_Items *[]*contextify.ProcessingItem `protobuf:"bytes,1,rep,name=items,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetProcessingItemsResponse) Reset() {
	*x = GetProcessingItemsResponse{}
	mi := &file_dev_observer_api_web_observations_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessingItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessingItemsResponse) ProtoMessage() {}

func (x *GetProcessingItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_web_observations_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetProcessingItemsResponse) GetItems() []*contextify.ProcessingItem {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *GetProcessingItemsResponse) SetItems(v []*contextify.ProcessingItem) {
	x.xxx_hidden_Items = &v
}

type GetProcessingItemsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Items []*contextify.ProcessingItem
}

func (b0 GetProcessingItemsResponse_builder) Build() *GetProcessingItemsResponse {
	m0 := &GetProcessingItemsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	return m0
}

type UpdateProcessingItemRequest struct {
	state           protoimpl.MessageState         `protogen:"opaque.v1"`
	xxx_hidden_Key  *contextify.ProcessingItemKey  `protobuf:"bytes,1,opt,name=key,proto3"`
	xxx_hidden_Data *contextify.ProcessingItemData `protobuf:"bytes,2,opt,name=data,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateProcessingItemRequest) Reset() {
	*x = UpdateProcessingItemRequest{}
	mi := &file_dev_observer_api_web_observations_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProcessingItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProcessingItemRequest) ProtoMessage() {}

func (x *UpdateProcessingItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_web_observations_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateProcessingItemRequest) GetKey() *contextify.ProcessingItemKey {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return nil
}

func (x *UpdateProcessingItemRequest) GetData() *contextify.ProcessingItemData {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *UpdateProcessingItemRequest) SetKey(v *contextify.ProcessingItemKey) {
	x.xxx_hidden_Key = v
}

func (x *UpdateProcessingItemRequest) SetData(v *contextify.ProcessingItemData) {
	x.xxx_hidden_Data = v
}

func (x *UpdateProcessingItemRequest) HasKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Key != nil
}

func (x *UpdateProcessingItemRequest) HasData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Data != nil
}

func (x *UpdateProcessingItemRequest) ClearKey() {
	x.xxx_hidden_Key = nil
}

func (x *UpdateProcessingItemRequest) ClearData() {
	x.xxx_hidden_Data = nil
}

type UpdateProcessingItemRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key  *contextify.ProcessingItemKey
	Data *contextify.ProcessingItemData
}

func (b0 UpdateProcessingItemRequest_builder) Build() *UpdateProcessingItemRequest {
	m0 := &UpdateProcessingItemRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Key = b.Key
	x.xxx_hidden_Data = b.Data
	return m0
}

type UpdateProcessingItemResponse struct {
	state           protoimpl.MessageState     `protogen:"opaque.v1"`
	xxx_hidden_Item *contextify.ProcessingItem `protobuf:"bytes,1,opt,name=item,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateProcessingItemResponse) Reset() {
	*x = UpdateProcessingItemResponse{}
	mi := &file_dev_observer_api_web_observations_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProcessingItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProcessingItemResponse) ProtoMessage() {}

func (x *UpdateProcessingItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_web_observations_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateProcessingItemResponse) GetItem() *contextify.ProcessingItem {
	if x != nil {
		return x.xxx_hidden_Item
	}
	return nil
}

func (x *UpdateProcessingItemResponse) SetItem(v *contextify.ProcessingItem) {
	x.xxx_hidden_Item = v
}

func (x *UpdateProcessingItemResponse) HasItem() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Item != nil
}

func (x *UpdateProcessingItemResponse) ClearItem() {
	x.xxx_hidden_Item = nil
}

type UpdateProcessingItemResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Item *contextify.ProcessingItem
}

func (b0 UpdateProcessingItemResponse_builder) Build() *UpdateProcessingItemResponse {
	m0 := &UpdateProcessingItemResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Item = b.Item
	return m0
}

var File_dev_observer_api_web_observations_proto protoreflect.FileDescriptor

const file_dev_observer_api_web_observations_proto_rawDesc = "" +
	"\n" +
	"'dev_observer/api/web/observations.proto\x12!dev_observer.api.web.observations\x1a)dev_observer/api/types/observations.proto\x1a'dev_observer/api/types/processing.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"b\n" +
	"\x17GetObservationsResponse\x12G\n" +
	"\x04keys\x18\x01 \x03(\v23.dev_observer.api.types.observations.ObservationKeyR\x04keys\"l\n" +
	"\x16GetObservationResponse\x12R\n" +
	"\vobservation\x18\x01 \x01(\v20.dev_observer.api.types.observations.ObservationR\vobservation\"\x82\x02\n" +
	"\x1bGetProcessingResultsRequest\x12<\n" +
	"\tfrom_date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\bfromDate\x88\x01\x01\x128\n" +
	"\ato_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x06toDate\x88\x01\x01\x12Q\n" +
	"\x06filter\x18\x03 \x01(\v29.dev_observer.api.types.processing.ProcessingResultFilterR\x06filterB\f\n" +
	"\n" +
	"_from_dateB\n" +
	"\n" +
	"\b_to_date\"q\n" +
	"\x1cGetProcessingResultsResponse\x12Q\n" +
	"\aresults\x18\x01 \x03(\v27.dev_observer.api.types.processing.ProcessingItemResultR\aresults\"~\n" +
	"\x1bGetProcessingResultResponse\x12T\n" +
	"\x06result\x18\x01 \x01(\v27.dev_observer.api.types.processing.ProcessingItemResultH\x00R\x06result\x88\x01\x01B\t\n" +
	"\a_result\"\xe1\x01\n" +
	"\x1bCreateProcessingItemRequest\x12F\n" +
	"\x03key\x18\x01 \x01(\v24.dev_observer.api.types.processing.ProcessingItemKeyR\x03key\x12/\n" +
	"\x13process_immediately\x18\x02 \x01(\bR\x12processImmediately\x12I\n" +
	"\x04data\x18\x03 \x01(\v25.dev_observer.api.types.processing.ProcessingItemDataR\x04data\"\x1e\n" +
	"\x1cCreateProcessingItemResponse\"e\n" +
	"\x1bDeleteProcessingItemRequest\x12F\n" +
	"\x03key\x18\x01 \x01(\v24.dev_observer.api.types.processing.ProcessingItemKeyR\x03key\"\x1e\n" +
	"\x1cDeleteProcessingItemResponse\"\xd6\x01\n" +
	"\x1eGetProcessingRunStatusResponse\x12T\n" +
	"\x06result\x18\x01 \x01(\v27.dev_observer.api.types.processing.ProcessingItemResultH\x00R\x06result\x88\x01\x01\x12J\n" +
	"\x04item\x18\x02 \x01(\v21.dev_observer.api.types.processing.ProcessingItemH\x01R\x04item\x88\x01\x01B\t\n" +
	"\a_resultB\a\n" +
	"\x05_item\"m\n" +
	"\x19GetProcessingItemsRequest\x12P\n" +
	"\x06filter\x18\x01 \x01(\v28.dev_observer.api.types.processing.ProcessingItemsFilterR\x06filter\"e\n" +
	"\x1aGetProcessingItemsResponse\x12G\n" +
	"\x05items\x18\x01 \x03(\v21.dev_observer.api.types.processing.ProcessingItemR\x05items\"\xb0\x01\n" +
	"\x1bUpdateProcessingItemRequest\x12F\n" +
	"\x03key\x18\x01 \x01(\v24.dev_observer.api.types.processing.ProcessingItemKeyR\x03key\x12I\n" +
	"\x04data\x18\x02 \x01(\v25.dev_observer.api.types.processing.ProcessingItemDataR\x04data\"e\n" +
	"\x1cUpdateProcessingItemResponse\x12E\n" +
	"\x04item\x18\x01 \x01(\v21.dev_observer.api.types.processing.ProcessingItemR\x04itemB@Z>github.com/devplaninc/contextify/clients/go/contextify/serviceb\x06proto3"

var file_dev_observer_api_web_observations_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_dev_observer_api_web_observations_proto_goTypes = []any{
	(*GetObservationsResponse)(nil),           // 0: dev_observer.api.web.observations.GetObservationsResponse
	(*GetObservationResponse)(nil),            // 1: dev_observer.api.web.observations.GetObservationResponse
	(*GetProcessingResultsRequest)(nil),       // 2: dev_observer.api.web.observations.GetProcessingResultsRequest
	(*GetProcessingResultsResponse)(nil),      // 3: dev_observer.api.web.observations.GetProcessingResultsResponse
	(*GetProcessingResultResponse)(nil),       // 4: dev_observer.api.web.observations.GetProcessingResultResponse
	(*CreateProcessingItemRequest)(nil),       // 5: dev_observer.api.web.observations.CreateProcessingItemRequest
	(*CreateProcessingItemResponse)(nil),      // 6: dev_observer.api.web.observations.CreateProcessingItemResponse
	(*DeleteProcessingItemRequest)(nil),       // 7: dev_observer.api.web.observations.DeleteProcessingItemRequest
	(*DeleteProcessingItemResponse)(nil),      // 8: dev_observer.api.web.observations.DeleteProcessingItemResponse
	(*GetProcessingRunStatusResponse)(nil),    // 9: dev_observer.api.web.observations.GetProcessingRunStatusResponse
	(*GetProcessingItemsRequest)(nil),         // 10: dev_observer.api.web.observations.GetProcessingItemsRequest
	(*GetProcessingItemsResponse)(nil),        // 11: dev_observer.api.web.observations.GetProcessingItemsResponse
	(*UpdateProcessingItemRequest)(nil),       // 12: dev_observer.api.web.observations.UpdateProcessingItemRequest
	(*UpdateProcessingItemResponse)(nil),      // 13: dev_observer.api.web.observations.UpdateProcessingItemResponse
	(*contextify.ObservationKey)(nil),         // 14: dev_observer.api.types.observations.ObservationKey
	(*contextify.Observation)(nil),            // 15: dev_observer.api.types.observations.Observation
	(*timestamppb.Timestamp)(nil),             // 16: google.protobuf.Timestamp
	(*contextify.ProcessingResultFilter)(nil), // 17: dev_observer.api.types.processing.ProcessingResultFilter
	(*contextify.ProcessingItemResult)(nil),   // 18: dev_observer.api.types.processing.ProcessingItemResult
	(*contextify.ProcessingItemKey)(nil),      // 19: dev_observer.api.types.processing.ProcessingItemKey
	(*contextify.ProcessingItemData)(nil),     // 20: dev_observer.api.types.processing.ProcessingItemData
	(*contextify.ProcessingItem)(nil),         // 21: dev_observer.api.types.processing.ProcessingItem
	(*contextify.ProcessingItemsFilter)(nil),  // 22: dev_observer.api.types.processing.ProcessingItemsFilter
}
var file_dev_observer_api_web_observations_proto_depIdxs = []int32{
	14, // 0: dev_observer.api.web.observations.GetObservationsResponse.keys:type_name -> dev_observer.api.types.observations.ObservationKey
	15, // 1: dev_observer.api.web.observations.GetObservationResponse.observation:type_name -> dev_observer.api.types.observations.Observation
	16, // 2: dev_observer.api.web.observations.GetProcessingResultsRequest.from_date:type_name -> google.protobuf.Timestamp
	16, // 3: dev_observer.api.web.observations.GetProcessingResultsRequest.to_date:type_name -> google.protobuf.Timestamp
	17, // 4: dev_observer.api.web.observations.GetProcessingResultsRequest.filter:type_name -> dev_observer.api.types.processing.ProcessingResultFilter
	18, // 5: dev_observer.api.web.observations.GetProcessingResultsResponse.results:type_name -> dev_observer.api.types.processing.ProcessingItemResult
	18, // 6: dev_observer.api.web.observations.GetProcessingResultResponse.result:type_name -> dev_observer.api.types.processing.ProcessingItemResult
	19, // 7: dev_observer.api.web.observations.CreateProcessingItemRequest.key:type_name -> dev_observer.api.types.processing.ProcessingItemKey
	20, // 8: dev_observer.api.web.observations.CreateProcessingItemRequest.data:type_name -> dev_observer.api.types.processing.ProcessingItemData
	19, // 9: dev_observer.api.web.observations.DeleteProcessingItemRequest.key:type_name -> dev_observer.api.types.processing.ProcessingItemKey
	18, // 10: dev_observer.api.web.observations.GetProcessingRunStatusResponse.result:type_name -> dev_observer.api.types.processing.ProcessingItemResult
	21, // 11: dev_observer.api.web.observations.GetProcessingRunStatusResponse.item:type_name -> dev_observer.api.types.processing.ProcessingItem
	22, // 12: dev_observer.api.web.observations.GetProcessingItemsRequest.filter:type_name -> dev_observer.api.types.processing.ProcessingItemsFilter
	21, // 13: dev_observer.api.web.observations.GetProcessingItemsResponse.items:type_name -> dev_observer.api.types.processing.ProcessingItem
	19, // 14: dev_observer.api.web.observations.UpdateProcessingItemRequest.key:type_name -> dev_observer.api.types.processing.ProcessingItemKey
	20, // 15: dev_observer.api.web.observations.UpdateProcessingItemRequest.data:type_name -> dev_observer.api.types.processing.ProcessingItemData
	21, // 16: dev_observer.api.web.observations.UpdateProcessingItemResponse.item:type_name -> dev_observer.api.types.processing.ProcessingItem
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_dev_observer_api_web_observations_proto_init() }
func file_dev_observer_api_web_observations_proto_init() {
	if File_dev_observer_api_web_observations_proto != nil {
		return
	}
	file_dev_observer_api_web_observations_proto_msgTypes[2].OneofWrappers = []any{}
	file_dev_observer_api_web_observations_proto_msgTypes[4].OneofWrappers = []any{}
	file_dev_observer_api_web_observations_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dev_observer_api_web_observations_proto_rawDesc), len(file_dev_observer_api_web_observations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dev_observer_api_web_observations_proto_goTypes,
		DependencyIndexes: file_dev_observer_api_web_observations_proto_depIdxs,
		MessageInfos:      file_dev_observer_api_web_observations_proto_msgTypes,
	}.Build()
	File_dev_observer_api_web_observations_proto = out.File
	file_dev_observer_api_web_observations_proto_goTypes = nil
	file_dev_observer_api_web_observations_proto_depIdxs = nil
}
