// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: dev_observer/api/types/ai.proto

package contextify

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PromptConfig struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Model *ModelConfig           `protobuf:"bytes,1,opt,name=model,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PromptConfig) Reset() {
	*x = PromptConfig{}
	mi := &file_dev_observer_api_types_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptConfig) ProtoMessage() {}

func (x *PromptConfig) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PromptConfig) GetModel() *ModelConfig {
	if x != nil {
		return x.xxx_hidden_Model
	}
	return nil
}

func (x *PromptConfig) SetModel(v *ModelConfig) {
	x.xxx_hidden_Model = v
}

func (x *PromptConfig) HasModel() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Model != nil
}

func (x *PromptConfig) ClearModel() {
	x.xxx_hidden_Model = nil
}

type PromptConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Model *ModelConfig
}

func (b0 PromptConfig_builder) Build() *PromptConfig {
	m0 := &PromptConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Model = b.Model
	return m0
}

type ModelConfig struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Provider    string                 `protobuf:"bytes,1,opt,name=provider,proto3"`
	xxx_hidden_ModelName   string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3"`
	xxx_hidden_Temperature float32                `protobuf:"fixed32,3,opt,name=temperature,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ModelConfig) Reset() {
	*x = ModelConfig{}
	mi := &file_dev_observer_api_types_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelConfig) ProtoMessage() {}

func (x *ModelConfig) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ModelConfig) GetProvider() string {
	if x != nil {
		return x.xxx_hidden_Provider
	}
	return ""
}

func (x *ModelConfig) GetModelName() string {
	if x != nil {
		return x.xxx_hidden_ModelName
	}
	return ""
}

func (x *ModelConfig) GetTemperature() float32 {
	if x != nil {
		return x.xxx_hidden_Temperature
	}
	return 0
}

func (x *ModelConfig) SetProvider(v string) {
	x.xxx_hidden_Provider = v
}

func (x *ModelConfig) SetModelName(v string) {
	x.xxx_hidden_ModelName = v
}

func (x *ModelConfig) SetTemperature(v float32) {
	x.xxx_hidden_Temperature = v
}

type ModelConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Provider    string
	ModelName   string
	Temperature float32
}

func (b0 ModelConfig_builder) Build() *ModelConfig {
	m0 := &ModelConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Provider = b.Provider
	x.xxx_hidden_ModelName = b.ModelName
	x.xxx_hidden_Temperature = b.Temperature
	return m0
}

type SystemMessage struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Text string                 `protobuf:"bytes,1,opt,name=text,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SystemMessage) Reset() {
	*x = SystemMessage{}
	mi := &file_dev_observer_api_types_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMessage) ProtoMessage() {}

func (x *SystemMessage) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SystemMessage) GetText() string {
	if x != nil {
		return x.xxx_hidden_Text
	}
	return ""
}

func (x *SystemMessage) SetText(v string) {
	x.xxx_hidden_Text = v
}

type SystemMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Text string
}

func (b0 SystemMessage_builder) Build() *SystemMessage {
	m0 := &SystemMessage{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Text = b.Text
	return m0
}

type UserMessage struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Text        *string                `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
	xxx_hidden_ImageUrls   []string               `protobuf:"bytes,3,rep,name=image_urls,json=imageUrls,proto3"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UserMessage) Reset() {
	*x = UserMessage{}
	mi := &file_dev_observer_api_types_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMessage) ProtoMessage() {}

func (x *UserMessage) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserMessage) GetText() string {
	if x != nil {
		if x.xxx_hidden_Text != nil {
			return *x.xxx_hidden_Text
		}
		return ""
	}
	return ""
}

func (x *UserMessage) GetImageUrls() []string {
	if x != nil {
		return x.xxx_hidden_ImageUrls
	}
	return nil
}

func (x *UserMessage) SetText(v string) {
	x.xxx_hidden_Text = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *UserMessage) SetImageUrls(v []string) {
	x.xxx_hidden_ImageUrls = v
}

func (x *UserMessage) HasText() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UserMessage) ClearText() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Text = nil
}

type UserMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Text      *string
	ImageUrls []string
}

func (b0 UserMessage_builder) Build() *UserMessage {
	m0 := &UserMessage{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Text != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Text = b.Text
	}
	x.xxx_hidden_ImageUrls = b.ImageUrls
	return m0
}

type PromptTemplate struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_System *SystemMessage         `protobuf:"bytes,1,opt,name=system,proto3,oneof"`
	xxx_hidden_User   *UserMessage           `protobuf:"bytes,2,opt,name=user,proto3,oneof"`
	xxx_hidden_Config *PromptConfig          `protobuf:"bytes,3,opt,name=config,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PromptTemplate) Reset() {
	*x = PromptTemplate{}
	mi := &file_dev_observer_api_types_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptTemplate) ProtoMessage() {}

func (x *PromptTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PromptTemplate) GetSystem() *SystemMessage {
	if x != nil {
		return x.xxx_hidden_System
	}
	return nil
}

func (x *PromptTemplate) GetUser() *UserMessage {
	if x != nil {
		return x.xxx_hidden_User
	}
	return nil
}

func (x *PromptTemplate) GetConfig() *PromptConfig {
	if x != nil {
		return x.xxx_hidden_Config
	}
	return nil
}

func (x *PromptTemplate) SetSystem(v *SystemMessage) {
	x.xxx_hidden_System = v
}

func (x *PromptTemplate) SetUser(v *UserMessage) {
	x.xxx_hidden_User = v
}

func (x *PromptTemplate) SetConfig(v *PromptConfig) {
	x.xxx_hidden_Config = v
}

func (x *PromptTemplate) HasSystem() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_System != nil
}

func (x *PromptTemplate) HasUser() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_User != nil
}

func (x *PromptTemplate) HasConfig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Config != nil
}

func (x *PromptTemplate) ClearSystem() {
	x.xxx_hidden_System = nil
}

func (x *PromptTemplate) ClearUser() {
	x.xxx_hidden_User = nil
}

func (x *PromptTemplate) ClearConfig() {
	x.xxx_hidden_Config = nil
}

type PromptTemplate_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	System *SystemMessage
	User   *UserMessage
	Config *PromptConfig
}

func (b0 PromptTemplate_builder) Build() *PromptTemplate {
	m0 := &PromptTemplate{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_System = b.System
	x.xxx_hidden_User = b.User
	x.xxx_hidden_Config = b.Config
	return m0
}

type UsageMetadata struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_InputTokens  int32                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3"`
	xxx_hidden_OutputTokens int32                  `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3"`
	xxx_hidden_TotalTokens  int32                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *UsageMetadata) Reset() {
	*x = UsageMetadata{}
	mi := &file_dev_observer_api_types_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageMetadata) ProtoMessage() {}

func (x *UsageMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UsageMetadata) GetInputTokens() int32 {
	if x != nil {
		return x.xxx_hidden_InputTokens
	}
	return 0
}

func (x *UsageMetadata) GetOutputTokens() int32 {
	if x != nil {
		return x.xxx_hidden_OutputTokens
	}
	return 0
}

func (x *UsageMetadata) GetTotalTokens() int32 {
	if x != nil {
		return x.xxx_hidden_TotalTokens
	}
	return 0
}

func (x *UsageMetadata) SetInputTokens(v int32) {
	x.xxx_hidden_InputTokens = v
}

func (x *UsageMetadata) SetOutputTokens(v int32) {
	x.xxx_hidden_OutputTokens = v
}

func (x *UsageMetadata) SetTotalTokens(v int32) {
	x.xxx_hidden_TotalTokens = v
}

type UsageMetadata_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	InputTokens  int32
	OutputTokens int32
	TotalTokens  int32
}

func (b0 UsageMetadata_builder) Build() *UsageMetadata {
	m0 := &UsageMetadata{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_InputTokens = b.InputTokens
	x.xxx_hidden_OutputTokens = b.OutputTokens
	x.xxx_hidden_TotalTokens = b.TotalTokens
	return m0
}

var File_dev_observer_api_types_ai_proto protoreflect.FileDescriptor

const file_dev_observer_api_types_ai_proto_rawDesc = "" +
	"\n" +
	"\x1fdev_observer/api/types/ai.proto\x12\x19dev_observer.api.types.ai\"L\n" +
	"\fPromptConfig\x12<\n" +
	"\x05model\x18\x01 \x01(\v2&.dev_observer.api.types.ai.ModelConfigR\x05model\"j\n" +
	"\vModelConfig\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x02R\vtemperature\"#\n" +
	"\rSystemMessage\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"_\n" +
	"\vUserMessage\x12\x17\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"image_urls\x18\x03 \x03(\tR\timageUrlsB\a\n" +
	"\x05_textJ\x04\b\x02\x10\x03R\timage_url\"\xed\x01\n" +
	"\x0ePromptTemplate\x12E\n" +
	"\x06system\x18\x01 \x01(\v2(.dev_observer.api.types.ai.SystemMessageH\x00R\x06system\x88\x01\x01\x12?\n" +
	"\x04user\x18\x02 \x01(\v2&.dev_observer.api.types.ai.UserMessageH\x01R\x04user\x88\x01\x01\x12?\n" +
	"\x06config\x18\x03 \x01(\v2'.dev_observer.api.types.ai.PromptConfigR\x06configB\t\n" +
	"\a_systemB\a\n" +
	"\x05_user\"z\n" +
	"\rUsageMetadata\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x05R\foutputTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokensB8Z6github.com/devplaninc/contextify/clients/go/contextifyb\x06proto3"

var file_dev_observer_api_types_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_dev_observer_api_types_ai_proto_goTypes = []any{
	(*PromptConfig)(nil),   // 0: dev_observer.api.types.ai.PromptConfig
	(*ModelConfig)(nil),    // 1: dev_observer.api.types.ai.ModelConfig
	(*SystemMessage)(nil),  // 2: dev_observer.api.types.ai.SystemMessage
	(*UserMessage)(nil),    // 3: dev_observer.api.types.ai.UserMessage
	(*PromptTemplate)(nil), // 4: dev_observer.api.types.ai.PromptTemplate
	(*UsageMetadata)(nil),  // 5: dev_observer.api.types.ai.UsageMetadata
}
var file_dev_observer_api_types_ai_proto_depIdxs = []int32{
	1, // 0: dev_observer.api.types.ai.PromptConfig.model:type_name -> dev_observer.api.types.ai.ModelConfig
	2, // 1: dev_observer.api.types.ai.PromptTemplate.system:type_name -> dev_observer.api.types.ai.SystemMessage
	3, // 2: dev_observer.api.types.ai.PromptTemplate.user:type_name -> dev_observer.api.types.ai.UserMessage
	0, // 3: dev_observer.api.types.ai.PromptTemplate.config:type_name -> dev_observer.api.types.ai.PromptConfig
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_dev_observer_api_types_ai_proto_init() }
func file_dev_observer_api_types_ai_proto_init() {
	if File_dev_observer_api_types_ai_proto != nil {
		return
	}
	file_dev_observer_api_types_ai_proto_msgTypes[3].OneofWrappers = []any{}
	file_dev_observer_api_types_ai_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dev_observer_api_types_ai_proto_rawDesc), len(file_dev_observer_api_types_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dev_observer_api_types_ai_proto_goTypes,
		DependencyIndexes: file_dev_observer_api_types_ai_proto_depIdxs,
		MessageInfos:      file_dev_observer_api_types_ai_proto_msgTypes,
	}.Build()
	File_dev_observer_api_types_ai_proto = out.File
	file_dev_observer_api_types_ai_proto_goTypes = nil
	file_dev_observer_api_types_ai_proto_depIdxs = nil
}
