// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: dev_observer/api/types/config.proto

package contextify

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GlobalConfig struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Analysis        *AnalysisConfig        `protobuf:"bytes,1,opt,name=analysis,proto3"`
	xxx_hidden_RepoAnalysis    *RepoAnalysisConfig    `protobuf:"bytes,2,opt,name=repo_analysis,json=repoAnalysis,proto3"`
	xxx_hidden_WebsiteCrawling *WebsiteCrawlingConfig `protobuf:"bytes,3,opt,name=website_crawling,json=websiteCrawling,proto3"`
	xxx_hidden_Periodic        *PeriodicConfig        `protobuf:"bytes,4,opt,name=periodic,proto3"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *GlobalConfig) Reset() {
	*x = GlobalConfig{}
	mi := &file_dev_observer_api_types_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalConfig) ProtoMessage() {}

func (x *GlobalConfig) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GlobalConfig) GetAnalysis() *AnalysisConfig {
	if x != nil {
		return x.xxx_hidden_Analysis
	}
	return nil
}

func (x *GlobalConfig) GetRepoAnalysis() *RepoAnalysisConfig {
	if x != nil {
		return x.xxx_hidden_RepoAnalysis
	}
	return nil
}

func (x *GlobalConfig) GetWebsiteCrawling() *WebsiteCrawlingConfig {
	if x != nil {
		return x.xxx_hidden_WebsiteCrawling
	}
	return nil
}

func (x *GlobalConfig) GetPeriodic() *PeriodicConfig {
	if x != nil {
		return x.xxx_hidden_Periodic
	}
	return nil
}

func (x *GlobalConfig) SetAnalysis(v *AnalysisConfig) {
	x.xxx_hidden_Analysis = v
}

func (x *GlobalConfig) SetRepoAnalysis(v *RepoAnalysisConfig) {
	x.xxx_hidden_RepoAnalysis = v
}

func (x *GlobalConfig) SetWebsiteCrawling(v *WebsiteCrawlingConfig) {
	x.xxx_hidden_WebsiteCrawling = v
}

func (x *GlobalConfig) SetPeriodic(v *PeriodicConfig) {
	x.xxx_hidden_Periodic = v
}

func (x *GlobalConfig) HasAnalysis() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Analysis != nil
}

func (x *GlobalConfig) HasRepoAnalysis() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_RepoAnalysis != nil
}

func (x *GlobalConfig) HasWebsiteCrawling() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_WebsiteCrawling != nil
}

func (x *GlobalConfig) HasPeriodic() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Periodic != nil
}

func (x *GlobalConfig) ClearAnalysis() {
	x.xxx_hidden_Analysis = nil
}

func (x *GlobalConfig) ClearRepoAnalysis() {
	x.xxx_hidden_RepoAnalysis = nil
}

func (x *GlobalConfig) ClearWebsiteCrawling() {
	x.xxx_hidden_WebsiteCrawling = nil
}

func (x *GlobalConfig) ClearPeriodic() {
	x.xxx_hidden_Periodic = nil
}

type GlobalConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Analysis        *AnalysisConfig
	RepoAnalysis    *RepoAnalysisConfig
	WebsiteCrawling *WebsiteCrawlingConfig
	Periodic        *PeriodicConfig
}

func (b0 GlobalConfig_builder) Build() *GlobalConfig {
	m0 := &GlobalConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Analysis = b.Analysis
	x.xxx_hidden_RepoAnalysis = b.RepoAnalysis
	x.xxx_hidden_WebsiteCrawling = b.WebsiteCrawling
	x.xxx_hidden_Periodic = b.Periodic
	return m0
}

type PeriodicConfig struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Concurrency int32                  `protobuf:"varint,1,opt,name=concurrency,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PeriodicConfig) Reset() {
	*x = PeriodicConfig{}
	mi := &file_dev_observer_api_types_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeriodicConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeriodicConfig) ProtoMessage() {}

func (x *PeriodicConfig) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PeriodicConfig) GetConcurrency() int32 {
	if x != nil {
		return x.xxx_hidden_Concurrency
	}
	return 0
}

func (x *PeriodicConfig) SetConcurrency(v int32) {
	x.xxx_hidden_Concurrency = v
}

type PeriodicConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Concurrency int32
}

func (b0 PeriodicConfig_builder) Build() *PeriodicConfig {
	m0 := &PeriodicConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Concurrency = b.Concurrency
	return m0
}

type AnalysisConfig struct {
	state                                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RepoAnalyzers                    *[]*Analyzer           `protobuf:"bytes,1,rep,name=repo_analyzers,json=repoAnalyzers,proto3"`
	xxx_hidden_SiteAnalyzers                    *[]*Analyzer           `protobuf:"bytes,2,rep,name=site_analyzers,json=siteAnalyzers,proto3"`
	xxx_hidden_DisableMasking                   bool                   `protobuf:"varint,3,opt,name=disable_masking,json=disableMasking,proto3"`
	xxx_hidden_DefaultGitChangesAnalyzer        *Analyzer              `protobuf:"bytes,4,opt,name=default_git_changes_analyzer,json=defaultGitChangesAnalyzer,proto3,oneof"`
	xxx_hidden_DefaultAggregatedSummaryAnalyzer *Analyzer              `protobuf:"bytes,5,opt,name=default_aggregated_summary_analyzer,json=defaultAggregatedSummaryAnalyzer,proto3,oneof"`
	unknownFields                               protoimpl.UnknownFields
	sizeCache                                   protoimpl.SizeCache
}

func (x *AnalysisConfig) Reset() {
	*x = AnalysisConfig{}
	mi := &file_dev_observer_api_types_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisConfig) ProtoMessage() {}

func (x *AnalysisConfig) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AnalysisConfig) GetRepoAnalyzers() []*Analyzer {
	if x != nil {
		if x.xxx_hidden_RepoAnalyzers != nil {
			return *x.xxx_hidden_RepoAnalyzers
		}
	}
	return nil
}

func (x *AnalysisConfig) GetSiteAnalyzers() []*Analyzer {
	if x != nil {
		if x.xxx_hidden_SiteAnalyzers != nil {
			return *x.xxx_hidden_SiteAnalyzers
		}
	}
	return nil
}

func (x *AnalysisConfig) GetDisableMasking() bool {
	if x != nil {
		return x.xxx_hidden_DisableMasking
	}
	return false
}

func (x *AnalysisConfig) GetDefaultGitChangesAnalyzer() *Analyzer {
	if x != nil {
		return x.xxx_hidden_DefaultGitChangesAnalyzer
	}
	return nil
}

func (x *AnalysisConfig) GetDefaultAggregatedSummaryAnalyzer() *Analyzer {
	if x != nil {
		return x.xxx_hidden_DefaultAggregatedSummaryAnalyzer
	}
	return nil
}

func (x *AnalysisConfig) SetRepoAnalyzers(v []*Analyzer) {
	x.xxx_hidden_RepoAnalyzers = &v
}

func (x *AnalysisConfig) SetSiteAnalyzers(v []*Analyzer) {
	x.xxx_hidden_SiteAnalyzers = &v
}

func (x *AnalysisConfig) SetDisableMasking(v bool) {
	x.xxx_hidden_DisableMasking = v
}

func (x *AnalysisConfig) SetDefaultGitChangesAnalyzer(v *Analyzer) {
	x.xxx_hidden_DefaultGitChangesAnalyzer = v
}

func (x *AnalysisConfig) SetDefaultAggregatedSummaryAnalyzer(v *Analyzer) {
	x.xxx_hidden_DefaultAggregatedSummaryAnalyzer = v
}

func (x *AnalysisConfig) HasDefaultGitChangesAnalyzer() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DefaultGitChangesAnalyzer != nil
}

func (x *AnalysisConfig) HasDefaultAggregatedSummaryAnalyzer() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DefaultAggregatedSummaryAnalyzer != nil
}

func (x *AnalysisConfig) ClearDefaultGitChangesAnalyzer() {
	x.xxx_hidden_DefaultGitChangesAnalyzer = nil
}

func (x *AnalysisConfig) ClearDefaultAggregatedSummaryAnalyzer() {
	x.xxx_hidden_DefaultAggregatedSummaryAnalyzer = nil
}

type AnalysisConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RepoAnalyzers                    []*Analyzer
	SiteAnalyzers                    []*Analyzer
	DisableMasking                   bool
	DefaultGitChangesAnalyzer        *Analyzer
	DefaultAggregatedSummaryAnalyzer *Analyzer
}

func (b0 AnalysisConfig_builder) Build() *AnalysisConfig {
	m0 := &AnalysisConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RepoAnalyzers = &b.RepoAnalyzers
	x.xxx_hidden_SiteAnalyzers = &b.SiteAnalyzers
	x.xxx_hidden_DisableMasking = b.DisableMasking
	x.xxx_hidden_DefaultGitChangesAnalyzer = b.DefaultGitChangesAnalyzer
	x.xxx_hidden_DefaultAggregatedSummaryAnalyzer = b.DefaultAggregatedSummaryAnalyzer
	return m0
}

type UserManagementStatus struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Enabled      bool                   `protobuf:"varint,1,opt,name=enabled,proto3"`
	xxx_hidden_PublicApiKey *string                `protobuf:"bytes,2,opt,name=public_api_key,json=publicApiKey,proto3,oneof"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *UserManagementStatus) Reset() {
	*x = UserManagementStatus{}
	mi := &file_dev_observer_api_types_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserManagementStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserManagementStatus) ProtoMessage() {}

func (x *UserManagementStatus) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserManagementStatus) GetEnabled() bool {
	if x != nil {
		return x.xxx_hidden_Enabled
	}
	return false
}

func (x *UserManagementStatus) GetPublicApiKey() string {
	if x != nil {
		if x.xxx_hidden_PublicApiKey != nil {
			return *x.xxx_hidden_PublicApiKey
		}
		return ""
	}
	return ""
}

func (x *UserManagementStatus) SetEnabled(v bool) {
	x.xxx_hidden_Enabled = v
}

func (x *UserManagementStatus) SetPublicApiKey(v string) {
	x.xxx_hidden_PublicApiKey = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *UserManagementStatus) HasPublicApiKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UserManagementStatus) ClearPublicApiKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_PublicApiKey = nil
}

type UserManagementStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Enabled      bool
	PublicApiKey *string
}

func (b0 UserManagementStatus_builder) Build() *UserManagementStatus {
	m0 := &UserManagementStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Enabled = b.Enabled
	if b.PublicApiKey != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_PublicApiKey = b.PublicApiKey
	}
	return m0
}

type RepoAnalysisConfig struct {
	state                            protoimpl.MessageState       `protogen:"opaque.v1"`
	xxx_hidden_Flatten               *RepoAnalysisConfig_Flatten  `protobuf:"bytes,1,opt,name=flatten,proto3"`
	xxx_hidden_ProcessingIntervalSec int32                        `protobuf:"varint,2,opt,name=processing_interval_sec,json=processingIntervalSec,proto3"`
	xxx_hidden_Disabled              bool                         `protobuf:"varint,3,opt,name=disabled,proto3"`
	xxx_hidden_Research              *RepoAnalysisConfig_Research `protobuf:"bytes,4,opt,name=research,proto3"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *RepoAnalysisConfig) Reset() {
	*x = RepoAnalysisConfig{}
	mi := &file_dev_observer_api_types_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoAnalysisConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoAnalysisConfig) ProtoMessage() {}

func (x *RepoAnalysisConfig) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RepoAnalysisConfig) GetFlatten() *RepoAnalysisConfig_Flatten {
	if x != nil {
		return x.xxx_hidden_Flatten
	}
	return nil
}

func (x *RepoAnalysisConfig) GetProcessingIntervalSec() int32 {
	if x != nil {
		return x.xxx_hidden_ProcessingIntervalSec
	}
	return 0
}

func (x *RepoAnalysisConfig) GetDisabled() bool {
	if x != nil {
		return x.xxx_hidden_Disabled
	}
	return false
}

func (x *RepoAnalysisConfig) GetResearch() *RepoAnalysisConfig_Research {
	if x != nil {
		return x.xxx_hidden_Research
	}
	return nil
}

func (x *RepoAnalysisConfig) SetFlatten(v *RepoAnalysisConfig_Flatten) {
	x.xxx_hidden_Flatten = v
}

func (x *RepoAnalysisConfig) SetProcessingIntervalSec(v int32) {
	x.xxx_hidden_ProcessingIntervalSec = v
}

func (x *RepoAnalysisConfig) SetDisabled(v bool) {
	x.xxx_hidden_Disabled = v
}

func (x *RepoAnalysisConfig) SetResearch(v *RepoAnalysisConfig_Research) {
	x.xxx_hidden_Research = v
}

func (x *RepoAnalysisConfig) HasFlatten() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Flatten != nil
}

func (x *RepoAnalysisConfig) HasResearch() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Research != nil
}

func (x *RepoAnalysisConfig) ClearFlatten() {
	x.xxx_hidden_Flatten = nil
}

func (x *RepoAnalysisConfig) ClearResearch() {
	x.xxx_hidden_Research = nil
}

type RepoAnalysisConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Flatten               *RepoAnalysisConfig_Flatten
	ProcessingIntervalSec int32
	Disabled              bool
	Research              *RepoAnalysisConfig_Research
}

func (b0 RepoAnalysisConfig_builder) Build() *RepoAnalysisConfig {
	m0 := &RepoAnalysisConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Flatten = b.Flatten
	x.xxx_hidden_ProcessingIntervalSec = b.ProcessingIntervalSec
	x.xxx_hidden_Disabled = b.Disabled
	x.xxx_hidden_Research = b.Research
	return m0
}

type WebsiteCrawlingConfig struct {
	state                                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_WebsiteScanTimeoutSeconds    int32                  `protobuf:"varint,1,opt,name=website_scan_timeout_seconds,json=websiteScanTimeoutSeconds,proto3"`
	xxx_hidden_ScrapyResponseTimeoutSeconds int32                  `protobuf:"varint,2,opt,name=scrapy_response_timeout_seconds,json=scrapyResponseTimeoutSeconds,proto3"`
	xxx_hidden_CrawlDepth                   int32                  `protobuf:"varint,3,opt,name=crawl_depth,json=crawlDepth,proto3"`
	xxx_hidden_TimeoutWithoutDataSeconds    int32                  `protobuf:"varint,4,opt,name=timeout_without_data_seconds,json=timeoutWithoutDataSeconds,proto3"`
	unknownFields                           protoimpl.UnknownFields
	sizeCache                               protoimpl.SizeCache
}

func (x *WebsiteCrawlingConfig) Reset() {
	*x = WebsiteCrawlingConfig{}
	mi := &file_dev_observer_api_types_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebsiteCrawlingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsiteCrawlingConfig) ProtoMessage() {}

func (x *WebsiteCrawlingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *WebsiteCrawlingConfig) GetWebsiteScanTimeoutSeconds() int32 {
	if x != nil {
		return x.xxx_hidden_WebsiteScanTimeoutSeconds
	}
	return 0
}

func (x *WebsiteCrawlingConfig) GetScrapyResponseTimeoutSeconds() int32 {
	if x != nil {
		return x.xxx_hidden_ScrapyResponseTimeoutSeconds
	}
	return 0
}

func (x *WebsiteCrawlingConfig) GetCrawlDepth() int32 {
	if x != nil {
		return x.xxx_hidden_CrawlDepth
	}
	return 0
}

func (x *WebsiteCrawlingConfig) GetTimeoutWithoutDataSeconds() int32 {
	if x != nil {
		return x.xxx_hidden_TimeoutWithoutDataSeconds
	}
	return 0
}

func (x *WebsiteCrawlingConfig) SetWebsiteScanTimeoutSeconds(v int32) {
	x.xxx_hidden_WebsiteScanTimeoutSeconds = v
}

func (x *WebsiteCrawlingConfig) SetScrapyResponseTimeoutSeconds(v int32) {
	x.xxx_hidden_ScrapyResponseTimeoutSeconds = v
}

func (x *WebsiteCrawlingConfig) SetCrawlDepth(v int32) {
	x.xxx_hidden_CrawlDepth = v
}

func (x *WebsiteCrawlingConfig) SetTimeoutWithoutDataSeconds(v int32) {
	x.xxx_hidden_TimeoutWithoutDataSeconds = v
}

type WebsiteCrawlingConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	WebsiteScanTimeoutSeconds    int32
	ScrapyResponseTimeoutSeconds int32
	CrawlDepth                   int32
	TimeoutWithoutDataSeconds    int32
}

func (b0 WebsiteCrawlingConfig_builder) Build() *WebsiteCrawlingConfig {
	m0 := &WebsiteCrawlingConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_WebsiteScanTimeoutSeconds = b.WebsiteScanTimeoutSeconds
	x.xxx_hidden_ScrapyResponseTimeoutSeconds = b.ScrapyResponseTimeoutSeconds
	x.xxx_hidden_CrawlDepth = b.CrawlDepth
	x.xxx_hidden_TimeoutWithoutDataSeconds = b.TimeoutWithoutDataSeconds
	return m0
}

type RepoAnalysisConfig_Flatten struct {
	state                             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Compress               bool                   `protobuf:"varint,1,opt,name=compress,proto3"`
	xxx_hidden_RemoveEmptyLines       bool                   `protobuf:"varint,2,opt,name=remove_empty_lines,json=removeEmptyLines,proto3"`
	xxx_hidden_OutStyle               string                 `protobuf:"bytes,3,opt,name=out_style,json=outStyle,proto3"`
	xxx_hidden_MaxTokensPerChunk      int32                  `protobuf:"varint,4,opt,name=max_tokens_per_chunk,json=maxTokensPerChunk,proto3"`
	xxx_hidden_MaxRepoSizeMb          int32                  `protobuf:"varint,5,opt,name=max_repo_size_mb,json=maxRepoSizeMb,proto3"`
	xxx_hidden_IgnorePattern          string                 `protobuf:"bytes,6,opt,name=ignore_pattern,json=ignorePattern,proto3"`
	xxx_hidden_LargeRepoThresholdMb   int32                  `protobuf:"varint,7,opt,name=large_repo_threshold_mb,json=largeRepoThresholdMb,proto3"`
	xxx_hidden_LargeRepoIgnorePattern string                 `protobuf:"bytes,8,opt,name=large_repo_ignore_pattern,json=largeRepoIgnorePattern,proto3"`
	xxx_hidden_CompressLarge          bool                   `protobuf:"varint,9,opt,name=compress_large,json=compressLarge,proto3"`
	xxx_hidden_MaxFileSizeBytes       int32                  `protobuf:"varint,10,opt,name=max_file_size_bytes,json=maxFileSizeBytes,proto3"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *RepoAnalysisConfig_Flatten) Reset() {
	*x = RepoAnalysisConfig_Flatten{}
	mi := &file_dev_observer_api_types_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoAnalysisConfig_Flatten) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoAnalysisConfig_Flatten) ProtoMessage() {}

func (x *RepoAnalysisConfig_Flatten) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RepoAnalysisConfig_Flatten) GetCompress() bool {
	if x != nil {
		return x.xxx_hidden_Compress
	}
	return false
}

func (x *RepoAnalysisConfig_Flatten) GetRemoveEmptyLines() bool {
	if x != nil {
		return x.xxx_hidden_RemoveEmptyLines
	}
	return false
}

func (x *RepoAnalysisConfig_Flatten) GetOutStyle() string {
	if x != nil {
		return x.xxx_hidden_OutStyle
	}
	return ""
}

func (x *RepoAnalysisConfig_Flatten) GetMaxTokensPerChunk() int32 {
	if x != nil {
		return x.xxx_hidden_MaxTokensPerChunk
	}
	return 0
}

func (x *RepoAnalysisConfig_Flatten) GetMaxRepoSizeMb() int32 {
	if x != nil {
		return x.xxx_hidden_MaxRepoSizeMb
	}
	return 0
}

func (x *RepoAnalysisConfig_Flatten) GetIgnorePattern() string {
	if x != nil {
		return x.xxx_hidden_IgnorePattern
	}
	return ""
}

func (x *RepoAnalysisConfig_Flatten) GetLargeRepoThresholdMb() int32 {
	if x != nil {
		return x.xxx_hidden_LargeRepoThresholdMb
	}
	return 0
}

func (x *RepoAnalysisConfig_Flatten) GetLargeRepoIgnorePattern() string {
	if x != nil {
		return x.xxx_hidden_LargeRepoIgnorePattern
	}
	return ""
}

func (x *RepoAnalysisConfig_Flatten) GetCompressLarge() bool {
	if x != nil {
		return x.xxx_hidden_CompressLarge
	}
	return false
}

func (x *RepoAnalysisConfig_Flatten) GetMaxFileSizeBytes() int32 {
	if x != nil {
		return x.xxx_hidden_MaxFileSizeBytes
	}
	return 0
}

func (x *RepoAnalysisConfig_Flatten) SetCompress(v bool) {
	x.xxx_hidden_Compress = v
}

func (x *RepoAnalysisConfig_Flatten) SetRemoveEmptyLines(v bool) {
	x.xxx_hidden_RemoveEmptyLines = v
}

func (x *RepoAnalysisConfig_Flatten) SetOutStyle(v string) {
	x.xxx_hidden_OutStyle = v
}

func (x *RepoAnalysisConfig_Flatten) SetMaxTokensPerChunk(v int32) {
	x.xxx_hidden_MaxTokensPerChunk = v
}

func (x *RepoAnalysisConfig_Flatten) SetMaxRepoSizeMb(v int32) {
	x.xxx_hidden_MaxRepoSizeMb = v
}

func (x *RepoAnalysisConfig_Flatten) SetIgnorePattern(v string) {
	x.xxx_hidden_IgnorePattern = v
}

func (x *RepoAnalysisConfig_Flatten) SetLargeRepoThresholdMb(v int32) {
	x.xxx_hidden_LargeRepoThresholdMb = v
}

func (x *RepoAnalysisConfig_Flatten) SetLargeRepoIgnorePattern(v string) {
	x.xxx_hidden_LargeRepoIgnorePattern = v
}

func (x *RepoAnalysisConfig_Flatten) SetCompressLarge(v bool) {
	x.xxx_hidden_CompressLarge = v
}

func (x *RepoAnalysisConfig_Flatten) SetMaxFileSizeBytes(v int32) {
	x.xxx_hidden_MaxFileSizeBytes = v
}

type RepoAnalysisConfig_Flatten_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Compress          bool
	RemoveEmptyLines  bool
	OutStyle          string
	MaxTokensPerChunk int32
	MaxRepoSizeMb     int32
	IgnorePattern     string
	// Threshold in MB for a repo to be considered large
	LargeRepoThresholdMb int32
	// Additional ignore pattern for large repo
	LargeRepoIgnorePattern string
	CompressLarge          bool
	MaxFileSizeBytes       int32
}

func (b0 RepoAnalysisConfig_Flatten_builder) Build() *RepoAnalysisConfig_Flatten {
	m0 := &RepoAnalysisConfig_Flatten{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Compress = b.Compress
	x.xxx_hidden_RemoveEmptyLines = b.RemoveEmptyLines
	x.xxx_hidden_OutStyle = b.OutStyle
	x.xxx_hidden_MaxTokensPerChunk = b.MaxTokensPerChunk
	x.xxx_hidden_MaxRepoSizeMb = b.MaxRepoSizeMb
	x.xxx_hidden_IgnorePattern = b.IgnorePattern
	x.xxx_hidden_LargeRepoThresholdMb = b.LargeRepoThresholdMb
	x.xxx_hidden_LargeRepoIgnorePattern = b.LargeRepoIgnorePattern
	x.xxx_hidden_CompressLarge = b.CompressLarge
	x.xxx_hidden_MaxFileSizeBytes = b.MaxFileSizeBytes
	return m0
}

type RepoAnalysisConfig_Research struct {
	state                           protoimpl.MessageState                    `protogen:"opaque.v1"`
	xxx_hidden_MaxRepoSizeMb        int32                                     `protobuf:"varint,1,opt,name=max_repo_size_mb,json=maxRepoSizeMb,proto3"`
	xxx_hidden_MaxIterations        int32                                     `protobuf:"varint,2,opt,name=max_iterations,json=maxIterations,proto3"`
	xxx_hidden_GeneralPrefix        *string                                   `protobuf:"bytes,3,opt,name=general_prefix,json=generalPrefix,proto3,oneof"`
	xxx_hidden_Analyzers            *[]*Analyzer                              `protobuf:"bytes,4,rep,name=analyzers,proto3"`
	xxx_hidden_ReportChunkSize      int32                                     `protobuf:"varint,5,opt,name=report_chunk_size,json=reportChunkSize,proto3"`
	xxx_hidden_MaxToolContentTokens int32                                     `protobuf:"varint,6,opt,name=max_tool_content_tokens,json=maxToolContentTokens,proto3"`
	xxx_hidden_HistoryLimits        *RepoAnalysisConfig_ResearchHistoryLimits `protobuf:"bytes,7,opt,name=history_limits,json=historyLimits,proto3"`
	XXX_raceDetectHookData          protoimpl.RaceDetectHookData
	XXX_presence                    [1]uint32
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *RepoAnalysisConfig_Research) Reset() {
	*x = RepoAnalysisConfig_Research{}
	mi := &file_dev_observer_api_types_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoAnalysisConfig_Research) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoAnalysisConfig_Research) ProtoMessage() {}

func (x *RepoAnalysisConfig_Research) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RepoAnalysisConfig_Research) GetMaxRepoSizeMb() int32 {
	if x != nil {
		return x.xxx_hidden_MaxRepoSizeMb
	}
	return 0
}

func (x *RepoAnalysisConfig_Research) GetMaxIterations() int32 {
	if x != nil {
		return x.xxx_hidden_MaxIterations
	}
	return 0
}

func (x *RepoAnalysisConfig_Research) GetGeneralPrefix() string {
	if x != nil {
		if x.xxx_hidden_GeneralPrefix != nil {
			return *x.xxx_hidden_GeneralPrefix
		}
		return ""
	}
	return ""
}

func (x *RepoAnalysisConfig_Research) GetAnalyzers() []*Analyzer {
	if x != nil {
		if x.xxx_hidden_Analyzers != nil {
			return *x.xxx_hidden_Analyzers
		}
	}
	return nil
}

func (x *RepoAnalysisConfig_Research) GetReportChunkSize() int32 {
	if x != nil {
		return x.xxx_hidden_ReportChunkSize
	}
	return 0
}

func (x *RepoAnalysisConfig_Research) GetMaxToolContentTokens() int32 {
	if x != nil {
		return x.xxx_hidden_MaxToolContentTokens
	}
	return 0
}

func (x *RepoAnalysisConfig_Research) GetHistoryLimits() *RepoAnalysisConfig_ResearchHistoryLimits {
	if x != nil {
		return x.xxx_hidden_HistoryLimits
	}
	return nil
}

func (x *RepoAnalysisConfig_Research) SetMaxRepoSizeMb(v int32) {
	x.xxx_hidden_MaxRepoSizeMb = v
}

func (x *RepoAnalysisConfig_Research) SetMaxIterations(v int32) {
	x.xxx_hidden_MaxIterations = v
}

func (x *RepoAnalysisConfig_Research) SetGeneralPrefix(v string) {
	x.xxx_hidden_GeneralPrefix = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *RepoAnalysisConfig_Research) SetAnalyzers(v []*Analyzer) {
	x.xxx_hidden_Analyzers = &v
}

func (x *RepoAnalysisConfig_Research) SetReportChunkSize(v int32) {
	x.xxx_hidden_ReportChunkSize = v
}

func (x *RepoAnalysisConfig_Research) SetMaxToolContentTokens(v int32) {
	x.xxx_hidden_MaxToolContentTokens = v
}

func (x *RepoAnalysisConfig_Research) SetHistoryLimits(v *RepoAnalysisConfig_ResearchHistoryLimits) {
	x.xxx_hidden_HistoryLimits = v
}

func (x *RepoAnalysisConfig_Research) HasGeneralPrefix() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *RepoAnalysisConfig_Research) HasHistoryLimits() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_HistoryLimits != nil
}

func (x *RepoAnalysisConfig_Research) ClearGeneralPrefix() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_GeneralPrefix = nil
}

func (x *RepoAnalysisConfig_Research) ClearHistoryLimits() {
	x.xxx_hidden_HistoryLimits = nil
}

type RepoAnalysisConfig_Research_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	MaxRepoSizeMb        int32
	MaxIterations        int32
	GeneralPrefix        *string
	Analyzers            []*Analyzer
	ReportChunkSize      int32
	MaxToolContentTokens int32
	HistoryLimits        *RepoAnalysisConfig_ResearchHistoryLimits
}

func (b0 RepoAnalysisConfig_Research_builder) Build() *RepoAnalysisConfig_Research {
	m0 := &RepoAnalysisConfig_Research{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_MaxRepoSizeMb = b.MaxRepoSizeMb
	x.xxx_hidden_MaxIterations = b.MaxIterations
	if b.GeneralPrefix != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_GeneralPrefix = b.GeneralPrefix
	}
	x.xxx_hidden_Analyzers = &b.Analyzers
	x.xxx_hidden_ReportChunkSize = b.ReportChunkSize
	x.xxx_hidden_MaxToolContentTokens = b.MaxToolContentTokens
	x.xxx_hidden_HistoryLimits = b.HistoryLimits
	return m0
}

type RepoAnalysisConfig_ResearchHistoryLimits struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Plan      int32                  `protobuf:"varint,1,opt,name=plan,proto3"`
	xxx_hidden_Summarize int32                  `protobuf:"varint,2,opt,name=summarize,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RepoAnalysisConfig_ResearchHistoryLimits) Reset() {
	*x = RepoAnalysisConfig_ResearchHistoryLimits{}
	mi := &file_dev_observer_api_types_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoAnalysisConfig_ResearchHistoryLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoAnalysisConfig_ResearchHistoryLimits) ProtoMessage() {}

func (x *RepoAnalysisConfig_ResearchHistoryLimits) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RepoAnalysisConfig_ResearchHistoryLimits) GetPlan() int32 {
	if x != nil {
		return x.xxx_hidden_Plan
	}
	return 0
}

func (x *RepoAnalysisConfig_ResearchHistoryLimits) GetSummarize() int32 {
	if x != nil {
		return x.xxx_hidden_Summarize
	}
	return 0
}

func (x *RepoAnalysisConfig_ResearchHistoryLimits) SetPlan(v int32) {
	x.xxx_hidden_Plan = v
}

func (x *RepoAnalysisConfig_ResearchHistoryLimits) SetSummarize(v int32) {
	x.xxx_hidden_Summarize = v
}

type RepoAnalysisConfig_ResearchHistoryLimits_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Plan      int32
	Summarize int32
}

func (b0 RepoAnalysisConfig_ResearchHistoryLimits_builder) Build() *RepoAnalysisConfig_ResearchHistoryLimits {
	m0 := &RepoAnalysisConfig_ResearchHistoryLimits{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Plan = b.Plan
	x.xxx_hidden_Summarize = b.Summarize
	return m0
}

var File_dev_observer_api_types_config_proto protoreflect.FileDescriptor

const file_dev_observer_api_types_config_proto_rawDesc = "" +
	"\n" +
	"#dev_observer/api/types/config.proto\x12\x1ddev_observer.api.types.config\x1a)dev_observer/api/types/observations.proto\"\xdd\x02\n" +
	"\fGlobalConfig\x12I\n" +
	"\banalysis\x18\x01 \x01(\v2-.dev_observer.api.types.config.AnalysisConfigR\banalysis\x12V\n" +
	"\rrepo_analysis\x18\x02 \x01(\v21.dev_observer.api.types.config.RepoAnalysisConfigR\frepoAnalysis\x12_\n" +
	"\x10website_crawling\x18\x03 \x01(\v24.dev_observer.api.types.config.WebsiteCrawlingConfigR\x0fwebsiteCrawling\x12I\n" +
	"\bperiodic\x18\x04 \x01(\v2-.dev_observer.api.types.config.PeriodicConfigR\bperiodic\"2\n" +
	"\x0ePeriodicConfig\x12 \n" +
	"\vconcurrency\x18\x01 \x01(\x05R\vconcurrency\"\xc6\x04\n" +
	"\x0eAnalysisConfig\x12T\n" +
	"\x0erepo_analyzers\x18\x01 \x03(\v2-.dev_observer.api.types.observations.AnalyzerR\rrepoAnalyzers\x12T\n" +
	"\x0esite_analyzers\x18\x02 \x03(\v2-.dev_observer.api.types.observations.AnalyzerR\rsiteAnalyzers\x12'\n" +
	"\x0fdisable_masking\x18\x03 \x01(\bR\x0edisableMasking\x12s\n" +
	"\x1cdefault_git_changes_analyzer\x18\x04 \x01(\v2-.dev_observer.api.types.observations.AnalyzerH\x00R\x19defaultGitChangesAnalyzer\x88\x01\x01\x12\x81\x01\n" +
	"#default_aggregated_summary_analyzer\x18\x05 \x01(\v2-.dev_observer.api.types.observations.AnalyzerH\x01R defaultAggregatedSummaryAnalyzer\x88\x01\x01B\x1f\n" +
	"\x1d_default_git_changes_analyzerB&\n" +
	"$_default_aggregated_summary_analyzerJ\x04\b\x06\x10\aR\x17code_research_analyzers\"n\n" +
	"\x14UserManagementStatus\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12)\n" +
	"\x0epublic_api_key\x18\x02 \x01(\tH\x00R\fpublicApiKey\x88\x01\x01B\x11\n" +
	"\x0f_public_api_key\"\xd8\t\n" +
	"\x12RepoAnalysisConfig\x12S\n" +
	"\aflatten\x18\x01 \x01(\v29.dev_observer.api.types.config.RepoAnalysisConfig.FlattenR\aflatten\x126\n" +
	"\x17processing_interval_sec\x18\x02 \x01(\x05R\x15processingIntervalSec\x12\x1a\n" +
	"\bdisabled\x18\x03 \x01(\bR\bdisabled\x12V\n" +
	"\bresearch\x18\x04 \x01(\v2:.dev_observer.api.types.config.RepoAnalysisConfig.ResearchR\bresearch\x1a\xb9\x03\n" +
	"\aFlatten\x12\x1a\n" +
	"\bcompress\x18\x01 \x01(\bR\bcompress\x12,\n" +
	"\x12remove_empty_lines\x18\x02 \x01(\bR\x10removeEmptyLines\x12\x1b\n" +
	"\tout_style\x18\x03 \x01(\tR\boutStyle\x12/\n" +
	"\x14max_tokens_per_chunk\x18\x04 \x01(\x05R\x11maxTokensPerChunk\x12'\n" +
	"\x10max_repo_size_mb\x18\x05 \x01(\x05R\rmaxRepoSizeMb\x12%\n" +
	"\x0eignore_pattern\x18\x06 \x01(\tR\rignorePattern\x125\n" +
	"\x17large_repo_threshold_mb\x18\a \x01(\x05R\x14largeRepoThresholdMb\x129\n" +
	"\x19large_repo_ignore_pattern\x18\b \x01(\tR\x16largeRepoIgnorePattern\x12%\n" +
	"\x0ecompress_large\x18\t \x01(\bR\rcompressLarge\x12-\n" +
	"\x13max_file_size_bytes\x18\n" +
	" \x01(\x05R\x10maxFileSizeBytes\x1a\xb9\x03\n" +
	"\bResearch\x12'\n" +
	"\x10max_repo_size_mb\x18\x01 \x01(\x05R\rmaxRepoSizeMb\x12%\n" +
	"\x0emax_iterations\x18\x02 \x01(\x05R\rmaxIterations\x12*\n" +
	"\x0egeneral_prefix\x18\x03 \x01(\tH\x00R\rgeneralPrefix\x88\x01\x01\x12K\n" +
	"\tanalyzers\x18\x04 \x03(\v2-.dev_observer.api.types.observations.AnalyzerR\tanalyzers\x12*\n" +
	"\x11report_chunk_size\x18\x05 \x01(\x05R\x0freportChunkSize\x125\n" +
	"\x17max_tool_content_tokens\x18\x06 \x01(\x05R\x14maxToolContentTokens\x12n\n" +
	"\x0ehistory_limits\x18\a \x01(\v2G.dev_observer.api.types.config.RepoAnalysisConfig.ResearchHistoryLimitsR\rhistoryLimitsB\x11\n" +
	"\x0f_general_prefix\x1aI\n" +
	"\x15ResearchHistoryLimits\x12\x12\n" +
	"\x04plan\x18\x01 \x01(\x05R\x04plan\x12\x1c\n" +
	"\tsummarize\x18\x02 \x01(\x05R\tsummarize\"\x81\x02\n" +
	"\x15WebsiteCrawlingConfig\x12?\n" +
	"\x1cwebsite_scan_timeout_seconds\x18\x01 \x01(\x05R\x19websiteScanTimeoutSeconds\x12E\n" +
	"\x1fscrapy_response_timeout_seconds\x18\x02 \x01(\x05R\x1cscrapyResponseTimeoutSeconds\x12\x1f\n" +
	"\vcrawl_depth\x18\x03 \x01(\x05R\n" +
	"crawlDepth\x12?\n" +
	"\x1ctimeout_without_data_seconds\x18\x04 \x01(\x05R\x19timeoutWithoutDataSecondsB8Z6github.com/devplaninc/contextify/clients/go/contextifyb\x06proto3"

var file_dev_observer_api_types_config_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_dev_observer_api_types_config_proto_goTypes = []any{
	(*GlobalConfig)(nil),                             // 0: dev_observer.api.types.config.GlobalConfig
	(*PeriodicConfig)(nil),                           // 1: dev_observer.api.types.config.PeriodicConfig
	(*AnalysisConfig)(nil),                           // 2: dev_observer.api.types.config.AnalysisConfig
	(*UserManagementStatus)(nil),                     // 3: dev_observer.api.types.config.UserManagementStatus
	(*RepoAnalysisConfig)(nil),                       // 4: dev_observer.api.types.config.RepoAnalysisConfig
	(*WebsiteCrawlingConfig)(nil),                    // 5: dev_observer.api.types.config.WebsiteCrawlingConfig
	(*RepoAnalysisConfig_Flatten)(nil),               // 6: dev_observer.api.types.config.RepoAnalysisConfig.Flatten
	(*RepoAnalysisConfig_Research)(nil),              // 7: dev_observer.api.types.config.RepoAnalysisConfig.Research
	(*RepoAnalysisConfig_ResearchHistoryLimits)(nil), // 8: dev_observer.api.types.config.RepoAnalysisConfig.ResearchHistoryLimits
	(*Analyzer)(nil),                                 // 9: dev_observer.api.types.observations.Analyzer
}
var file_dev_observer_api_types_config_proto_depIdxs = []int32{
	2,  // 0: dev_observer.api.types.config.GlobalConfig.analysis:type_name -> dev_observer.api.types.config.AnalysisConfig
	4,  // 1: dev_observer.api.types.config.GlobalConfig.repo_analysis:type_name -> dev_observer.api.types.config.RepoAnalysisConfig
	5,  // 2: dev_observer.api.types.config.GlobalConfig.website_crawling:type_name -> dev_observer.api.types.config.WebsiteCrawlingConfig
	1,  // 3: dev_observer.api.types.config.GlobalConfig.periodic:type_name -> dev_observer.api.types.config.PeriodicConfig
	9,  // 4: dev_observer.api.types.config.AnalysisConfig.repo_analyzers:type_name -> dev_observer.api.types.observations.Analyzer
	9,  // 5: dev_observer.api.types.config.AnalysisConfig.site_analyzers:type_name -> dev_observer.api.types.observations.Analyzer
	9,  // 6: dev_observer.api.types.config.AnalysisConfig.default_git_changes_analyzer:type_name -> dev_observer.api.types.observations.Analyzer
	9,  // 7: dev_observer.api.types.config.AnalysisConfig.default_aggregated_summary_analyzer:type_name -> dev_observer.api.types.observations.Analyzer
	6,  // 8: dev_observer.api.types.config.RepoAnalysisConfig.flatten:type_name -> dev_observer.api.types.config.RepoAnalysisConfig.Flatten
	7,  // 9: dev_observer.api.types.config.RepoAnalysisConfig.research:type_name -> dev_observer.api.types.config.RepoAnalysisConfig.Research
	9,  // 10: dev_observer.api.types.config.RepoAnalysisConfig.Research.analyzers:type_name -> dev_observer.api.types.observations.Analyzer
	8,  // 11: dev_observer.api.types.config.RepoAnalysisConfig.Research.history_limits:type_name -> dev_observer.api.types.config.RepoAnalysisConfig.ResearchHistoryLimits
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_dev_observer_api_types_config_proto_init() }
func file_dev_observer_api_types_config_proto_init() {
	if File_dev_observer_api_types_config_proto != nil {
		return
	}
	file_dev_observer_api_types_observations_proto_init()
	file_dev_observer_api_types_config_proto_msgTypes[2].OneofWrappers = []any{}
	file_dev_observer_api_types_config_proto_msgTypes[3].OneofWrappers = []any{}
	file_dev_observer_api_types_config_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dev_observer_api_types_config_proto_rawDesc), len(file_dev_observer_api_types_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dev_observer_api_types_config_proto_goTypes,
		DependencyIndexes: file_dev_observer_api_types_config_proto_depIdxs,
		MessageInfos:      file_dev_observer_api_types_config_proto_msgTypes,
	}.Build()
	File_dev_observer_api_types_config_proto = out.File
	file_dev_observer_api_types_config_proto_goTypes = nil
	file_dev_observer_api_types_config_proto_depIdxs = nil
}
