// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: dev_observer/api/types/processing.proto

package contextify

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessingItemKey struct {
	state             protoimpl.MessageState     `protogen:"opaque.v1"`
	xxx_hidden_Entity isProcessingItemKey_Entity `protobuf_oneof:"entity"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProcessingItemKey) Reset() {
	*x = ProcessingItemKey{}
	mi := &file_dev_observer_api_types_processing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingItemKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingItemKey) ProtoMessage() {}

func (x *ProcessingItemKey) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_processing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProcessingItemKey) GetGithubRepoId() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Entity.(*processingItemKey_GithubRepoId); ok {
			return x.GithubRepoId
		}
	}
	return ""
}

func (x *ProcessingItemKey) GetWebsiteUrl() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Entity.(*processingItemKey_WebsiteUrl); ok {
			return x.WebsiteUrl
		}
	}
	return ""
}

func (x *ProcessingItemKey) GetRequestId() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Entity.(*processingItemKey_RequestId); ok {
			return x.RequestId
		}
	}
	return ""
}

func (x *ProcessingItemKey) GetPeriodicAggregationId() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Entity.(*processingItemKey_PeriodicAggregationId); ok {
			return x.PeriodicAggregationId
		}
	}
	return ""
}

func (x *ProcessingItemKey) GetResearchGitRepoId() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Entity.(*processingItemKey_ResearchGitRepoId); ok {
			return x.ResearchGitRepoId
		}
	}
	return ""
}

func (x *ProcessingItemKey) SetGithubRepoId(v string) {
	x.xxx_hidden_Entity = &processingItemKey_GithubRepoId{v}
}

func (x *ProcessingItemKey) SetWebsiteUrl(v string) {
	x.xxx_hidden_Entity = &processingItemKey_WebsiteUrl{v}
}

func (x *ProcessingItemKey) SetRequestId(v string) {
	x.xxx_hidden_Entity = &processingItemKey_RequestId{v}
}

func (x *ProcessingItemKey) SetPeriodicAggregationId(v string) {
	x.xxx_hidden_Entity = &processingItemKey_PeriodicAggregationId{v}
}

func (x *ProcessingItemKey) SetResearchGitRepoId(v string) {
	x.xxx_hidden_Entity = &processingItemKey_ResearchGitRepoId{v}
}

func (x *ProcessingItemKey) HasEntity() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Entity != nil
}

func (x *ProcessingItemKey) HasGithubRepoId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Entity.(*processingItemKey_GithubRepoId)
	return ok
}

func (x *ProcessingItemKey) HasWebsiteUrl() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Entity.(*processingItemKey_WebsiteUrl)
	return ok
}

func (x *ProcessingItemKey) HasRequestId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Entity.(*processingItemKey_RequestId)
	return ok
}

func (x *ProcessingItemKey) HasPeriodicAggregationId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Entity.(*processingItemKey_PeriodicAggregationId)
	return ok
}

func (x *ProcessingItemKey) HasResearchGitRepoId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Entity.(*processingItemKey_ResearchGitRepoId)
	return ok
}

func (x *ProcessingItemKey) ClearEntity() {
	x.xxx_hidden_Entity = nil
}

func (x *ProcessingItemKey) ClearGithubRepoId() {
	if _, ok := x.xxx_hidden_Entity.(*processingItemKey_GithubRepoId); ok {
		x.xxx_hidden_Entity = nil
	}
}

func (x *ProcessingItemKey) ClearWebsiteUrl() {
	if _, ok := x.xxx_hidden_Entity.(*processingItemKey_WebsiteUrl); ok {
		x.xxx_hidden_Entity = nil
	}
}

func (x *ProcessingItemKey) ClearRequestId() {
	if _, ok := x.xxx_hidden_Entity.(*processingItemKey_RequestId); ok {
		x.xxx_hidden_Entity = nil
	}
}

func (x *ProcessingItemKey) ClearPeriodicAggregationId() {
	if _, ok := x.xxx_hidden_Entity.(*processingItemKey_PeriodicAggregationId); ok {
		x.xxx_hidden_Entity = nil
	}
}

func (x *ProcessingItemKey) ClearResearchGitRepoId() {
	if _, ok := x.xxx_hidden_Entity.(*processingItemKey_ResearchGitRepoId); ok {
		x.xxx_hidden_Entity = nil
	}
}

const ProcessingItemKey_Entity_not_set_case case_ProcessingItemKey_Entity = 0
const ProcessingItemKey_GithubRepoId_case case_ProcessingItemKey_Entity = 100
const ProcessingItemKey_WebsiteUrl_case case_ProcessingItemKey_Entity = 101
const ProcessingItemKey_RequestId_case case_ProcessingItemKey_Entity = 102
const ProcessingItemKey_PeriodicAggregationId_case case_ProcessingItemKey_Entity = 103
const ProcessingItemKey_ResearchGitRepoId_case case_ProcessingItemKey_Entity = 104

func (x *ProcessingItemKey) WhichEntity() case_ProcessingItemKey_Entity {
	if x == nil {
		return ProcessingItemKey_Entity_not_set_case
	}
	switch x.xxx_hidden_Entity.(type) {
	case *processingItemKey_GithubRepoId:
		return ProcessingItemKey_GithubRepoId_case
	case *processingItemKey_WebsiteUrl:
		return ProcessingItemKey_WebsiteUrl_case
	case *processingItemKey_RequestId:
		return ProcessingItemKey_RequestId_case
	case *processingItemKey_PeriodicAggregationId:
		return ProcessingItemKey_PeriodicAggregationId_case
	case *processingItemKey_ResearchGitRepoId:
		return ProcessingItemKey_ResearchGitRepoId_case
	default:
		return ProcessingItemKey_Entity_not_set_case
	}
}

type ProcessingItemKey_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Entity:
	// Repo summary processing.
	GithubRepoId *string
	// Website summary processing.
	WebsiteUrl *string
	// One-off request
	RequestId             *string
	PeriodicAggregationId *string
	// Periodic repo research.
	ResearchGitRepoId *string
	// -- end of xxx_hidden_Entity
}

func (b0 ProcessingItemKey_builder) Build() *ProcessingItemKey {
	m0 := &ProcessingItemKey{}
	b, x := &b0, m0
	_, _ = b, x
	if b.GithubRepoId != nil {
		x.xxx_hidden_Entity = &processingItemKey_GithubRepoId{*b.GithubRepoId}
	}
	if b.WebsiteUrl != nil {
		x.xxx_hidden_Entity = &processingItemKey_WebsiteUrl{*b.WebsiteUrl}
	}
	if b.RequestId != nil {
		x.xxx_hidden_Entity = &processingItemKey_RequestId{*b.RequestId}
	}
	if b.PeriodicAggregationId != nil {
		x.xxx_hidden_Entity = &processingItemKey_PeriodicAggregationId{*b.PeriodicAggregationId}
	}
	if b.ResearchGitRepoId != nil {
		x.xxx_hidden_Entity = &processingItemKey_ResearchGitRepoId{*b.ResearchGitRepoId}
	}
	return m0
}

type case_ProcessingItemKey_Entity protoreflect.FieldNumber

func (x case_ProcessingItemKey_Entity) String() string {
	md := file_dev_observer_api_types_processing_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isProcessingItemKey_Entity interface {
	isProcessingItemKey_Entity()
}

type processingItemKey_GithubRepoId struct {
	// Repo summary processing.
	GithubRepoId string `protobuf:"bytes,100,opt,name=github_repo_id,json=githubRepoId,proto3,oneof"`
}

type processingItemKey_WebsiteUrl struct {
	// Website summary processing.
	WebsiteUrl string `protobuf:"bytes,101,opt,name=website_url,json=websiteUrl,proto3,oneof"`
}

type processingItemKey_RequestId struct {
	// One-off request
	RequestId string `protobuf:"bytes,102,opt,name=request_id,json=requestId,proto3,oneof"`
}

type processingItemKey_PeriodicAggregationId struct {
	PeriodicAggregationId string `protobuf:"bytes,103,opt,name=periodic_aggregation_id,json=periodicAggregationId,proto3,oneof"`
}

type processingItemKey_ResearchGitRepoId struct {
	// Periodic repo research.
	ResearchGitRepoId string `protobuf:"bytes,104,opt,name=research_git_repo_id,json=researchGitRepoId,proto3,oneof"`
}

func (*processingItemKey_GithubRepoId) isProcessingItemKey_Entity() {}

func (*processingItemKey_WebsiteUrl) isProcessingItemKey_Entity() {}

func (*processingItemKey_RequestId) isProcessingItemKey_Entity() {}

func (*processingItemKey_PeriodicAggregationId) isProcessingItemKey_Entity() {}

func (*processingItemKey_ResearchGitRepoId) isProcessingItemKey_Entity() {}

type ProcessingItem struct {
	state                          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key                 *ProcessingItemKey     `protobuf:"bytes,1,opt,name=key,proto3"`
	xxx_hidden_NextProcessing      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=next_processing,json=nextProcessing,proto3,oneof"`
	xxx_hidden_LastProcessed       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_processed,json=lastProcessed,proto3,oneof"`
	xxx_hidden_LastError           *string                `protobuf:"bytes,4,opt,name=last_error,json=lastError,proto3,oneof"`
	xxx_hidden_NoProcessing        bool                   `protobuf:"varint,5,opt,name=no_processing,json=noProcessing,proto3"`
	xxx_hidden_ProcessingStartedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=processing_started_at,json=processingStartedAt,proto3,oneof"`
	xxx_hidden_Data                *ProcessingItemData    `protobuf:"bytes,8,opt,name=data,proto3,oneof"`
	XXX_raceDetectHookData         protoimpl.RaceDetectHookData
	XXX_presence                   [1]uint32
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *ProcessingItem) Reset() {
	*x = ProcessingItem{}
	mi := &file_dev_observer_api_types_processing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingItem) ProtoMessage() {}

func (x *ProcessingItem) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_processing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProcessingItem) GetKey() *ProcessingItemKey {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return nil
}

func (x *ProcessingItem) GetNextProcessing() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_NextProcessing
	}
	return nil
}

func (x *ProcessingItem) GetLastProcessed() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_LastProcessed
	}
	return nil
}

func (x *ProcessingItem) GetLastError() string {
	if x != nil {
		if x.xxx_hidden_LastError != nil {
			return *x.xxx_hidden_LastError
		}
		return ""
	}
	return ""
}

func (x *ProcessingItem) GetNoProcessing() bool {
	if x != nil {
		return x.xxx_hidden_NoProcessing
	}
	return false
}

func (x *ProcessingItem) GetProcessingStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ProcessingStartedAt
	}
	return nil
}

func (x *ProcessingItem) GetData() *ProcessingItemData {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *ProcessingItem) SetKey(v *ProcessingItemKey) {
	x.xxx_hidden_Key = v
}

func (x *ProcessingItem) SetNextProcessing(v *timestamppb.Timestamp) {
	x.xxx_hidden_NextProcessing = v
}

func (x *ProcessingItem) SetLastProcessed(v *timestamppb.Timestamp) {
	x.xxx_hidden_LastProcessed = v
}

func (x *ProcessingItem) SetLastError(v string) {
	x.xxx_hidden_LastError = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *ProcessingItem) SetNoProcessing(v bool) {
	x.xxx_hidden_NoProcessing = v
}

func (x *ProcessingItem) SetProcessingStartedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_ProcessingStartedAt = v
}

func (x *ProcessingItem) SetData(v *ProcessingItemData) {
	x.xxx_hidden_Data = v
}

func (x *ProcessingItem) HasKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Key != nil
}

func (x *ProcessingItem) HasNextProcessing() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_NextProcessing != nil
}

func (x *ProcessingItem) HasLastProcessed() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LastProcessed != nil
}

func (x *ProcessingItem) HasLastError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ProcessingItem) HasProcessingStartedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ProcessingStartedAt != nil
}

func (x *ProcessingItem) HasData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Data != nil
}

func (x *ProcessingItem) ClearKey() {
	x.xxx_hidden_Key = nil
}

func (x *ProcessingItem) ClearNextProcessing() {
	x.xxx_hidden_NextProcessing = nil
}

func (x *ProcessingItem) ClearLastProcessed() {
	x.xxx_hidden_LastProcessed = nil
}

func (x *ProcessingItem) ClearLastError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_LastError = nil
}

func (x *ProcessingItem) ClearProcessingStartedAt() {
	x.xxx_hidden_ProcessingStartedAt = nil
}

func (x *ProcessingItem) ClearData() {
	x.xxx_hidden_Data = nil
}

type ProcessingItem_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key                 *ProcessingItemKey
	NextProcessing      *timestamppb.Timestamp
	LastProcessed       *timestamppb.Timestamp
	LastError           *string
	NoProcessing        bool
	ProcessingStartedAt *timestamppb.Timestamp
	Data                *ProcessingItemData
}

func (b0 ProcessingItem_builder) Build() *ProcessingItem {
	m0 := &ProcessingItem{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Key = b.Key
	x.xxx_hidden_NextProcessing = b.NextProcessing
	x.xxx_hidden_LastProcessed = b.LastProcessed
	if b.LastError != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_LastError = b.LastError
	}
	x.xxx_hidden_NoProcessing = b.NoProcessing
	x.xxx_hidden_ProcessingStartedAt = b.ProcessingStartedAt
	x.xxx_hidden_Data = b.Data
	return m0
}

type PeriodicAggregation struct {
	state               protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_Params   *AggregatedSummaryParams `protobuf:"bytes,1,opt,name=params,proto3"`
	xxx_hidden_Schedule *Schedule                `protobuf:"bytes,2,opt,name=schedule,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PeriodicAggregation) Reset() {
	*x = PeriodicAggregation{}
	mi := &file_dev_observer_api_types_processing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeriodicAggregation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeriodicAggregation) ProtoMessage() {}

func (x *PeriodicAggregation) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_processing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PeriodicAggregation) GetParams() *AggregatedSummaryParams {
	if x != nil {
		return x.xxx_hidden_Params
	}
	return nil
}

func (x *PeriodicAggregation) GetSchedule() *Schedule {
	if x != nil {
		return x.xxx_hidden_Schedule
	}
	return nil
}

func (x *PeriodicAggregation) SetParams(v *AggregatedSummaryParams) {
	x.xxx_hidden_Params = v
}

func (x *PeriodicAggregation) SetSchedule(v *Schedule) {
	x.xxx_hidden_Schedule = v
}

func (x *PeriodicAggregation) HasParams() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Params != nil
}

func (x *PeriodicAggregation) HasSchedule() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Schedule != nil
}

func (x *PeriodicAggregation) ClearParams() {
	x.xxx_hidden_Params = nil
}

func (x *PeriodicAggregation) ClearSchedule() {
	x.xxx_hidden_Schedule = nil
}

type PeriodicAggregation_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Params   *AggregatedSummaryParams
	Schedule *Schedule
}

func (b0 PeriodicAggregation_builder) Build() *PeriodicAggregation {
	m0 := &PeriodicAggregation{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Params = b.Params
	x.xxx_hidden_Schedule = b.Schedule
	return m0
}

type AggregatedSummaryParams struct {
	state                   protoimpl.MessageState          `protogen:"opaque.v1"`
	xxx_hidden_LookBackDays int32                           `protobuf:"varint,1,opt,name=look_back_days,json=lookBackDays,proto3"`
	xxx_hidden_EndDate      *timestamppb.Timestamp          `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3"`
	xxx_hidden_Target       *AggregatedSummaryParams_Target `protobuf:"bytes,3,opt,name=target,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AggregatedSummaryParams) Reset() {
	*x = AggregatedSummaryParams{}
	mi := &file_dev_observer_api_types_processing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatedSummaryParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatedSummaryParams) ProtoMessage() {}

func (x *AggregatedSummaryParams) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_processing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AggregatedSummaryParams) GetLookBackDays() int32 {
	if x != nil {
		return x.xxx_hidden_LookBackDays
	}
	return 0
}

func (x *AggregatedSummaryParams) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_EndDate
	}
	return nil
}

func (x *AggregatedSummaryParams) GetTarget() *AggregatedSummaryParams_Target {
	if x != nil {
		return x.xxx_hidden_Target
	}
	return nil
}

func (x *AggregatedSummaryParams) SetLookBackDays(v int32) {
	x.xxx_hidden_LookBackDays = v
}

func (x *AggregatedSummaryParams) SetEndDate(v *timestamppb.Timestamp) {
	x.xxx_hidden_EndDate = v
}

func (x *AggregatedSummaryParams) SetTarget(v *AggregatedSummaryParams_Target) {
	x.xxx_hidden_Target = v
}

func (x *AggregatedSummaryParams) HasEndDate() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_EndDate != nil
}

func (x *AggregatedSummaryParams) HasTarget() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Target != nil
}

func (x *AggregatedSummaryParams) ClearEndDate() {
	x.xxx_hidden_EndDate = nil
}

func (x *AggregatedSummaryParams) ClearTarget() {
	x.xxx_hidden_Target = nil
}

type AggregatedSummaryParams_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	LookBackDays int32
	EndDate      *timestamppb.Timestamp
	Target       *AggregatedSummaryParams_Target
}

func (b0 AggregatedSummaryParams_builder) Build() *AggregatedSummaryParams {
	m0 := &AggregatedSummaryParams{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_LookBackDays = b.LookBackDays
	x.xxx_hidden_EndDate = b.EndDate
	x.xxx_hidden_Target = b.Target
	return m0
}

type ProcessingRequest struct {
	state           protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_Type isProcessingRequest_Type `protobuf_oneof:"type"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProcessingRequest) Reset() {
	*x = ProcessingRequest{}
	mi := &file_dev_observer_api_types_processing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingRequest) ProtoMessage() {}

func (x *ProcessingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_processing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProcessingRequest) GetGitChanges() *ProcessGitChangesRequest {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*processingRequest_GitChanges); ok {
			return x.GitChanges
		}
	}
	return nil
}

func (x *ProcessingRequest) SetGitChanges(v *ProcessGitChangesRequest) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &processingRequest_GitChanges{v}
}

func (x *ProcessingRequest) HasType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Type != nil
}

func (x *ProcessingRequest) HasGitChanges() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*processingRequest_GitChanges)
	return ok
}

func (x *ProcessingRequest) ClearType() {
	x.xxx_hidden_Type = nil
}

func (x *ProcessingRequest) ClearGitChanges() {
	if _, ok := x.xxx_hidden_Type.(*processingRequest_GitChanges); ok {
		x.xxx_hidden_Type = nil
	}
}

const ProcessingRequest_Type_not_set_case case_ProcessingRequest_Type = 0
const ProcessingRequest_GitChanges_case case_ProcessingRequest_Type = 100

func (x *ProcessingRequest) WhichType() case_ProcessingRequest_Type {
	if x == nil {
		return ProcessingRequest_Type_not_set_case
	}
	switch x.xxx_hidden_Type.(type) {
	case *processingRequest_GitChanges:
		return ProcessingRequest_GitChanges_case
	default:
		return ProcessingRequest_Type_not_set_case
	}
}

type ProcessingRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Type:
	GitChanges *ProcessGitChangesRequest
	// -- end of xxx_hidden_Type
}

func (b0 ProcessingRequest_builder) Build() *ProcessingRequest {
	m0 := &ProcessingRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.GitChanges != nil {
		x.xxx_hidden_Type = &processingRequest_GitChanges{b.GitChanges}
	}
	return m0
}

type case_ProcessingRequest_Type protoreflect.FieldNumber

func (x case_ProcessingRequest_Type) String() string {
	md := file_dev_observer_api_types_processing_proto_msgTypes[4].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isProcessingRequest_Type interface {
	isProcessingRequest_Type()
}

type processingRequest_GitChanges struct {
	GitChanges *ProcessGitChangesRequest `protobuf:"bytes,100,opt,name=git_changes,json=gitChanges,proto3,oneof"`
}

func (*processingRequest_GitChanges) isProcessingRequest_Type() {}

type ProcessGitChangesRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_GitRepoId    string                 `protobuf:"bytes,1,opt,name=git_repo_id,json=gitRepoId,proto3"`
	xxx_hidden_LookBackDays int32                  `protobuf:"varint,2,opt,name=look_back_days,json=lookBackDays,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ProcessGitChangesRequest) Reset() {
	*x = ProcessGitChangesRequest{}
	mi := &file_dev_observer_api_types_processing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessGitChangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessGitChangesRequest) ProtoMessage() {}

func (x *ProcessGitChangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_processing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProcessGitChangesRequest) GetGitRepoId() string {
	if x != nil {
		return x.xxx_hidden_GitRepoId
	}
	return ""
}

func (x *ProcessGitChangesRequest) GetLookBackDays() int32 {
	if x != nil {
		return x.xxx_hidden_LookBackDays
	}
	return 0
}

func (x *ProcessGitChangesRequest) SetGitRepoId(v string) {
	x.xxx_hidden_GitRepoId = v
}

func (x *ProcessGitChangesRequest) SetLookBackDays(v int32) {
	x.xxx_hidden_LookBackDays = v
}

type ProcessGitChangesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	GitRepoId    string
	LookBackDays int32
}

func (b0 ProcessGitChangesRequest_builder) Build() *ProcessGitChangesRequest {
	m0 := &ProcessGitChangesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_GitRepoId = b.GitRepoId
	x.xxx_hidden_LookBackDays = b.LookBackDays
	return m0
}

type ProcessingItemResult struct {
	state                   protoimpl.MessageState    `protogen:"opaque.v1"`
	xxx_hidden_Id           string                    `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_Key          *ProcessingItemKey        `protobuf:"bytes,2,opt,name=key,proto3"`
	xxx_hidden_ErrorMessage *string                   `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3,oneof"`
	xxx_hidden_CreatedAt    *timestamppb.Timestamp    `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3"`
	xxx_hidden_Data         *ProcessingItemData       `protobuf:"bytes,7,opt,name=data,proto3,oneof"`
	xxx_hidden_ResultData   *ProcessingItemResultData `protobuf:"bytes,8,opt,name=result_data,json=resultData,proto3,oneof"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ProcessingItemResult) Reset() {
	*x = ProcessingItemResult{}
	mi := &file_dev_observer_api_types_processing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingItemResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingItemResult) ProtoMessage() {}

func (x *ProcessingItemResult) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_processing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProcessingItemResult) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *ProcessingItemResult) GetKey() *ProcessingItemKey {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return nil
}

func (x *ProcessingItemResult) GetErrorMessage() string {
	if x != nil {
		if x.xxx_hidden_ErrorMessage != nil {
			return *x.xxx_hidden_ErrorMessage
		}
		return ""
	}
	return ""
}

func (x *ProcessingItemResult) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *ProcessingItemResult) GetData() *ProcessingItemData {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *ProcessingItemResult) GetResultData() *ProcessingItemResultData {
	if x != nil {
		return x.xxx_hidden_ResultData
	}
	return nil
}

func (x *ProcessingItemResult) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *ProcessingItemResult) SetKey(v *ProcessingItemKey) {
	x.xxx_hidden_Key = v
}

func (x *ProcessingItemResult) SetErrorMessage(v string) {
	x.xxx_hidden_ErrorMessage = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *ProcessingItemResult) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *ProcessingItemResult) SetData(v *ProcessingItemData) {
	x.xxx_hidden_Data = v
}

func (x *ProcessingItemResult) SetResultData(v *ProcessingItemResultData) {
	x.xxx_hidden_ResultData = v
}

func (x *ProcessingItemResult) HasKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Key != nil
}

func (x *ProcessingItemResult) HasErrorMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ProcessingItemResult) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *ProcessingItemResult) HasData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Data != nil
}

func (x *ProcessingItemResult) HasResultData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ResultData != nil
}

func (x *ProcessingItemResult) ClearKey() {
	x.xxx_hidden_Key = nil
}

func (x *ProcessingItemResult) ClearErrorMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ErrorMessage = nil
}

func (x *ProcessingItemResult) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *ProcessingItemResult) ClearData() {
	x.xxx_hidden_Data = nil
}

func (x *ProcessingItemResult) ClearResultData() {
	x.xxx_hidden_ResultData = nil
}

type ProcessingItemResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique id of the result
	Id           string
	Key          *ProcessingItemKey
	ErrorMessage *string
	CreatedAt    *timestamppb.Timestamp
	Data         *ProcessingItemData
	ResultData   *ProcessingItemResultData
}

func (b0 ProcessingItemResult_builder) Build() *ProcessingItemResult {
	m0 := &ProcessingItemResult{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Key = b.Key
	if b.ErrorMessage != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_ErrorMessage = b.ErrorMessage
	}
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_Data = b.Data
	x.xxx_hidden_ResultData = b.ResultData
	return m0
}

type RepoObservation struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RepoId       string                 `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3"`
	xxx_hidden_Observations *[]*ObservationKey     `protobuf:"bytes,2,rep,name=observations,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RepoObservation) Reset() {
	*x = RepoObservation{}
	mi := &file_dev_observer_api_types_processing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoObservation) ProtoMessage() {}

func (x *RepoObservation) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_processing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RepoObservation) GetRepoId() string {
	if x != nil {
		return x.xxx_hidden_RepoId
	}
	return ""
}

func (x *RepoObservation) GetObservations() []*ObservationKey {
	if x != nil {
		if x.xxx_hidden_Observations != nil {
			return *x.xxx_hidden_Observations
		}
	}
	return nil
}

func (x *RepoObservation) SetRepoId(v string) {
	x.xxx_hidden_RepoId = v
}

func (x *RepoObservation) SetObservations(v []*ObservationKey) {
	x.xxx_hidden_Observations = &v
}

type RepoObservation_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RepoId       string
	Observations []*ObservationKey
}

func (b0 RepoObservation_builder) Build() *RepoObservation {
	m0 := &RepoObservation{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RepoId = b.RepoId
	x.xxx_hidden_Observations = &b.Observations
	return m0
}

type PeriodicAggregationResult struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RepoObservations *[]*RepoObservation    `protobuf:"bytes,1,rep,name=repo_observations,json=repoObservations,proto3"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *PeriodicAggregationResult) Reset() {
	*x = PeriodicAggregationResult{}
	mi := &file_dev_observer_api_types_processing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeriodicAggregationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeriodicAggregationResult) ProtoMessage() {}

func (x *PeriodicAggregationResult) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_processing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PeriodicAggregationResult) GetRepoObservations() []*RepoObservation {
	if x != nil {
		if x.xxx_hidden_RepoObservations != nil {
			return *x.xxx_hidden_RepoObservations
		}
	}
	return nil
}

func (x *PeriodicAggregationResult) SetRepoObservations(v []*RepoObservation) {
	x.xxx_hidden_RepoObservations = &v
}

type PeriodicAggregationResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RepoObservations []*RepoObservation
}

func (b0 PeriodicAggregationResult_builder) Build() *PeriodicAggregationResult {
	m0 := &PeriodicAggregationResult{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RepoObservations = &b.RepoObservations
	return m0
}

type ProcessingItemData struct {
	state                  protoimpl.MessageState    `protogen:"opaque.v1"`
	xxx_hidden_ReferenceId *string                   `protobuf:"bytes,1,opt,name=reference_id,json=referenceId,proto3,oneof"`
	xxx_hidden_Namespace   *string                   `protobuf:"bytes,2,opt,name=namespace,proto3,oneof"`
	xxx_hidden_CreatedBy   *string                   `protobuf:"bytes,3,opt,name=created_by,json=createdBy,proto3,oneof"`
	xxx_hidden_Type        isProcessingItemData_Type `protobuf_oneof:"type"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ProcessingItemData) Reset() {
	*x = ProcessingItemData{}
	mi := &file_dev_observer_api_types_processing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingItemData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingItemData) ProtoMessage() {}

func (x *ProcessingItemData) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_processing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProcessingItemData) GetReferenceId() string {
	if x != nil {
		if x.xxx_hidden_ReferenceId != nil {
			return *x.xxx_hidden_ReferenceId
		}
		return ""
	}
	return ""
}

func (x *ProcessingItemData) GetNamespace() string {
	if x != nil {
		if x.xxx_hidden_Namespace != nil {
			return *x.xxx_hidden_Namespace
		}
		return ""
	}
	return ""
}

func (x *ProcessingItemData) GetCreatedBy() string {
	if x != nil {
		if x.xxx_hidden_CreatedBy != nil {
			return *x.xxx_hidden_CreatedBy
		}
		return ""
	}
	return ""
}

func (x *ProcessingItemData) GetRequest() *ProcessingRequest {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*processingItemData_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *ProcessingItemData) GetPeriodicAggregation() *PeriodicAggregation {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*processingItemData_PeriodicAggregation); ok {
			return x.PeriodicAggregation
		}
	}
	return nil
}

func (x *ProcessingItemData) SetReferenceId(v string) {
	x.xxx_hidden_ReferenceId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *ProcessingItemData) SetNamespace(v string) {
	x.xxx_hidden_Namespace = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *ProcessingItemData) SetCreatedBy(v string) {
	x.xxx_hidden_CreatedBy = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *ProcessingItemData) SetRequest(v *ProcessingRequest) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &processingItemData_Request{v}
}

func (x *ProcessingItemData) SetPeriodicAggregation(v *PeriodicAggregation) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &processingItemData_PeriodicAggregation{v}
}

func (x *ProcessingItemData) HasReferenceId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ProcessingItemData) HasNamespace() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ProcessingItemData) HasCreatedBy() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ProcessingItemData) HasType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Type != nil
}

func (x *ProcessingItemData) HasRequest() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*processingItemData_Request)
	return ok
}

func (x *ProcessingItemData) HasPeriodicAggregation() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*processingItemData_PeriodicAggregation)
	return ok
}

func (x *ProcessingItemData) ClearReferenceId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ReferenceId = nil
}

func (x *ProcessingItemData) ClearNamespace() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Namespace = nil
}

func (x *ProcessingItemData) ClearCreatedBy() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_CreatedBy = nil
}

func (x *ProcessingItemData) ClearType() {
	x.xxx_hidden_Type = nil
}

func (x *ProcessingItemData) ClearRequest() {
	if _, ok := x.xxx_hidden_Type.(*processingItemData_Request); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *ProcessingItemData) ClearPeriodicAggregation() {
	if _, ok := x.xxx_hidden_Type.(*processingItemData_PeriodicAggregation); ok {
		x.xxx_hidden_Type = nil
	}
}

const ProcessingItemData_Type_not_set_case case_ProcessingItemData_Type = 0
const ProcessingItemData_Request_case case_ProcessingItemData_Type = 100
const ProcessingItemData_PeriodicAggregation_case case_ProcessingItemData_Type = 101

func (x *ProcessingItemData) WhichType() case_ProcessingItemData_Type {
	if x == nil {
		return ProcessingItemData_Type_not_set_case
	}
	switch x.xxx_hidden_Type.(type) {
	case *processingItemData_Request:
		return ProcessingItemData_Request_case
	case *processingItemData_PeriodicAggregation:
		return ProcessingItemData_PeriodicAggregation_case
	default:
		return ProcessingItemData_Type_not_set_case
	}
}

type ProcessingItemData_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Free form indexed reference id that may be useful for connecting request to a specific repo or other entity.
	ReferenceId *string
	Namespace   *string
	CreatedBy   *string
	// Fields of oneof xxx_hidden_Type:
	Request             *ProcessingRequest
	PeriodicAggregation *PeriodicAggregation
	// -- end of xxx_hidden_Type
}

func (b0 ProcessingItemData_builder) Build() *ProcessingItemData {
	m0 := &ProcessingItemData{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ReferenceId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_ReferenceId = b.ReferenceId
	}
	if b.Namespace != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Namespace = b.Namespace
	}
	if b.CreatedBy != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_CreatedBy = b.CreatedBy
	}
	if b.Request != nil {
		x.xxx_hidden_Type = &processingItemData_Request{b.Request}
	}
	if b.PeriodicAggregation != nil {
		x.xxx_hidden_Type = &processingItemData_PeriodicAggregation{b.PeriodicAggregation}
	}
	return m0
}

type case_ProcessingItemData_Type protoreflect.FieldNumber

func (x case_ProcessingItemData_Type) String() string {
	md := file_dev_observer_api_types_processing_proto_msgTypes[9].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isProcessingItemData_Type interface {
	isProcessingItemData_Type()
}

type processingItemData_Request struct {
	Request *ProcessingRequest `protobuf:"bytes,100,opt,name=request,proto3,oneof"`
}

type processingItemData_PeriodicAggregation struct {
	PeriodicAggregation *PeriodicAggregation `protobuf:"bytes,101,opt,name=periodic_aggregation,json=periodicAggregation,proto3,oneof"`
}

func (*processingItemData_Request) isProcessingItemData_Type() {}

func (*processingItemData_PeriodicAggregation) isProcessingItemData_Type() {}

type ProcessingItemResultData struct {
	state                   protoimpl.MessageState          `protogen:"opaque.v1"`
	xxx_hidden_Observations *[]*ObservationKey              `protobuf:"bytes,1,rep,name=observations,proto3"`
	xxx_hidden_Type         isProcessingItemResultData_Type `protobuf_oneof:"type"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ProcessingItemResultData) Reset() {
	*x = ProcessingItemResultData{}
	mi := &file_dev_observer_api_types_processing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingItemResultData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingItemResultData) ProtoMessage() {}

func (x *ProcessingItemResultData) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_processing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProcessingItemResultData) GetObservations() []*ObservationKey {
	if x != nil {
		if x.xxx_hidden_Observations != nil {
			return *x.xxx_hidden_Observations
		}
	}
	return nil
}

func (x *ProcessingItemResultData) GetPeriodicAggregation() *PeriodicAggregationResult {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*processingItemResultData_PeriodicAggregation); ok {
			return x.PeriodicAggregation
		}
	}
	return nil
}

func (x *ProcessingItemResultData) SetObservations(v []*ObservationKey) {
	x.xxx_hidden_Observations = &v
}

func (x *ProcessingItemResultData) SetPeriodicAggregation(v *PeriodicAggregationResult) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &processingItemResultData_PeriodicAggregation{v}
}

func (x *ProcessingItemResultData) HasType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Type != nil
}

func (x *ProcessingItemResultData) HasPeriodicAggregation() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*processingItemResultData_PeriodicAggregation)
	return ok
}

func (x *ProcessingItemResultData) ClearType() {
	x.xxx_hidden_Type = nil
}

func (x *ProcessingItemResultData) ClearPeriodicAggregation() {
	if _, ok := x.xxx_hidden_Type.(*processingItemResultData_PeriodicAggregation); ok {
		x.xxx_hidden_Type = nil
	}
}

const ProcessingItemResultData_Type_not_set_case case_ProcessingItemResultData_Type = 0
const ProcessingItemResultData_PeriodicAggregation_case case_ProcessingItemResultData_Type = 100

func (x *ProcessingItemResultData) WhichType() case_ProcessingItemResultData_Type {
	if x == nil {
		return ProcessingItemResultData_Type_not_set_case
	}
	switch x.xxx_hidden_Type.(type) {
	case *processingItemResultData_PeriodicAggregation:
		return ProcessingItemResultData_PeriodicAggregation_case
	default:
		return ProcessingItemResultData_Type_not_set_case
	}
}

type ProcessingItemResultData_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Observations []*ObservationKey
	// Fields of oneof xxx_hidden_Type:
	PeriodicAggregation *PeriodicAggregationResult
	// -- end of xxx_hidden_Type
}

func (b0 ProcessingItemResultData_builder) Build() *ProcessingItemResultData {
	m0 := &ProcessingItemResultData{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Observations = &b.Observations
	if b.PeriodicAggregation != nil {
		x.xxx_hidden_Type = &processingItemResultData_PeriodicAggregation{b.PeriodicAggregation}
	}
	return m0
}

type case_ProcessingItemResultData_Type protoreflect.FieldNumber

func (x case_ProcessingItemResultData_Type) String() string {
	md := file_dev_observer_api_types_processing_proto_msgTypes[10].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isProcessingItemResultData_Type interface {
	isProcessingItemResultData_Type()
}

type processingItemResultData_PeriodicAggregation struct {
	PeriodicAggregation *PeriodicAggregationResult `protobuf:"bytes,100,opt,name=periodic_aggregation,json=periodicAggregation,proto3,oneof"`
}

func (*processingItemResultData_PeriodicAggregation) isProcessingItemResultData_Type() {}

type ProcessingResultFilter struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Namespace   *string                `protobuf:"bytes,1,opt,name=namespace,proto3,oneof"`
	xxx_hidden_ReferenceId *string                `protobuf:"bytes,2,opt,name=reference_id,json=referenceId,proto3,oneof"`
	xxx_hidden_RequestType *string                `protobuf:"bytes,3,opt,name=request_type,json=requestType,proto3,oneof"`
	xxx_hidden_Keys        *[]*ProcessingItemKey  `protobuf:"bytes,4,rep,name=keys,proto3"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ProcessingResultFilter) Reset() {
	*x = ProcessingResultFilter{}
	mi := &file_dev_observer_api_types_processing_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingResultFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingResultFilter) ProtoMessage() {}

func (x *ProcessingResultFilter) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_processing_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProcessingResultFilter) GetNamespace() string {
	if x != nil {
		if x.xxx_hidden_Namespace != nil {
			return *x.xxx_hidden_Namespace
		}
		return ""
	}
	return ""
}

func (x *ProcessingResultFilter) GetReferenceId() string {
	if x != nil {
		if x.xxx_hidden_ReferenceId != nil {
			return *x.xxx_hidden_ReferenceId
		}
		return ""
	}
	return ""
}

func (x *ProcessingResultFilter) GetRequestType() string {
	if x != nil {
		if x.xxx_hidden_RequestType != nil {
			return *x.xxx_hidden_RequestType
		}
		return ""
	}
	return ""
}

func (x *ProcessingResultFilter) GetKeys() []*ProcessingItemKey {
	if x != nil {
		if x.xxx_hidden_Keys != nil {
			return *x.xxx_hidden_Keys
		}
	}
	return nil
}

func (x *ProcessingResultFilter) SetNamespace(v string) {
	x.xxx_hidden_Namespace = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *ProcessingResultFilter) SetReferenceId(v string) {
	x.xxx_hidden_ReferenceId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *ProcessingResultFilter) SetRequestType(v string) {
	x.xxx_hidden_RequestType = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *ProcessingResultFilter) SetKeys(v []*ProcessingItemKey) {
	x.xxx_hidden_Keys = &v
}

func (x *ProcessingResultFilter) HasNamespace() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ProcessingResultFilter) HasReferenceId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ProcessingResultFilter) HasRequestType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ProcessingResultFilter) ClearNamespace() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Namespace = nil
}

func (x *ProcessingResultFilter) ClearReferenceId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ReferenceId = nil
}

func (x *ProcessingResultFilter) ClearRequestType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_RequestType = nil
}

type ProcessingResultFilter_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Namespace   *string
	ReferenceId *string
	RequestType *string
	Keys        []*ProcessingItemKey
}

func (b0 ProcessingResultFilter_builder) Build() *ProcessingResultFilter {
	m0 := &ProcessingResultFilter{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Namespace != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Namespace = b.Namespace
	}
	if b.ReferenceId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_ReferenceId = b.ReferenceId
	}
	if b.RequestType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_RequestType = b.RequestType
	}
	x.xxx_hidden_Keys = &b.Keys
	return m0
}

type ProcessingItemsFilter struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Namespace   *string                `protobuf:"bytes,1,opt,name=namespace,proto3,oneof"`
	xxx_hidden_ReferenceId *string                `protobuf:"bytes,2,opt,name=reference_id,json=referenceId,proto3,oneof"`
	xxx_hidden_RequestType *string                `protobuf:"bytes,3,opt,name=request_type,json=requestType,proto3,oneof"`
	xxx_hidden_Keys        *[]*ProcessingItemKey  `protobuf:"bytes,4,rep,name=keys,proto3"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ProcessingItemsFilter) Reset() {
	*x = ProcessingItemsFilter{}
	mi := &file_dev_observer_api_types_processing_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingItemsFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingItemsFilter) ProtoMessage() {}

func (x *ProcessingItemsFilter) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_processing_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProcessingItemsFilter) GetNamespace() string {
	if x != nil {
		if x.xxx_hidden_Namespace != nil {
			return *x.xxx_hidden_Namespace
		}
		return ""
	}
	return ""
}

func (x *ProcessingItemsFilter) GetReferenceId() string {
	if x != nil {
		if x.xxx_hidden_ReferenceId != nil {
			return *x.xxx_hidden_ReferenceId
		}
		return ""
	}
	return ""
}

func (x *ProcessingItemsFilter) GetRequestType() string {
	if x != nil {
		if x.xxx_hidden_RequestType != nil {
			return *x.xxx_hidden_RequestType
		}
		return ""
	}
	return ""
}

func (x *ProcessingItemsFilter) GetKeys() []*ProcessingItemKey {
	if x != nil {
		if x.xxx_hidden_Keys != nil {
			return *x.xxx_hidden_Keys
		}
	}
	return nil
}

func (x *ProcessingItemsFilter) SetNamespace(v string) {
	x.xxx_hidden_Namespace = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *ProcessingItemsFilter) SetReferenceId(v string) {
	x.xxx_hidden_ReferenceId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *ProcessingItemsFilter) SetRequestType(v string) {
	x.xxx_hidden_RequestType = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *ProcessingItemsFilter) SetKeys(v []*ProcessingItemKey) {
	x.xxx_hidden_Keys = &v
}

func (x *ProcessingItemsFilter) HasNamespace() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ProcessingItemsFilter) HasReferenceId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ProcessingItemsFilter) HasRequestType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ProcessingItemsFilter) ClearNamespace() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Namespace = nil
}

func (x *ProcessingItemsFilter) ClearReferenceId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ReferenceId = nil
}

func (x *ProcessingItemsFilter) ClearRequestType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_RequestType = nil
}

type ProcessingItemsFilter_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Namespace   *string
	ReferenceId *string
	RequestType *string
	Keys        []*ProcessingItemKey
}

func (b0 ProcessingItemsFilter_builder) Build() *ProcessingItemsFilter {
	m0 := &ProcessingItemsFilter{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Namespace != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Namespace = b.Namespace
	}
	if b.ReferenceId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_ReferenceId = b.ReferenceId
	}
	if b.RequestType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_RequestType = b.RequestType
	}
	x.xxx_hidden_Keys = &b.Keys
	return m0
}

type AggregatedSummaryParams_Target struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_GitRepoIds []string               `protobuf:"bytes,1,rep,name=git_repo_ids,json=gitRepoIds,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AggregatedSummaryParams_Target) Reset() {
	*x = AggregatedSummaryParams_Target{}
	mi := &file_dev_observer_api_types_processing_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatedSummaryParams_Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatedSummaryParams_Target) ProtoMessage() {}

func (x *AggregatedSummaryParams_Target) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_processing_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AggregatedSummaryParams_Target) GetGitRepoIds() []string {
	if x != nil {
		return x.xxx_hidden_GitRepoIds
	}
	return nil
}

func (x *AggregatedSummaryParams_Target) SetGitRepoIds(v []string) {
	x.xxx_hidden_GitRepoIds = v
}

type AggregatedSummaryParams_Target_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	GitRepoIds []string
}

func (b0 AggregatedSummaryParams_Target_builder) Build() *AggregatedSummaryParams_Target {
	m0 := &AggregatedSummaryParams_Target{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_GitRepoIds = b.GitRepoIds
	return m0
}

var File_dev_observer_api_types_processing_proto protoreflect.FileDescriptor

const file_dev_observer_api_types_processing_proto_rawDesc = "" +
	"\n" +
	"'dev_observer/api/types/processing.proto\x12!dev_observer.api.types.processing\x1a\x1fgoogle/protobuf/timestamp.proto\x1a)dev_observer/api/types/observations.proto\x1a%dev_observer/api/types/schedule.proto\"\xf6\x01\n" +
	"\x11ProcessingItemKey\x12&\n" +
	"\x0egithub_repo_id\x18d \x01(\tH\x00R\fgithubRepoId\x12!\n" +
	"\vwebsite_url\x18e \x01(\tH\x00R\n" +
	"websiteUrl\x12\x1f\n" +
	"\n" +
	"request_id\x18f \x01(\tH\x00R\trequestId\x128\n" +
	"\x17periodic_aggregation_id\x18g \x01(\tH\x00R\x15periodicAggregationId\x121\n" +
	"\x14research_git_repo_id\x18h \x01(\tH\x00R\x11researchGitRepoIdB\b\n" +
	"\x06entity\"\xc0\x04\n" +
	"\x0eProcessingItem\x12F\n" +
	"\x03key\x18\x01 \x01(\v24.dev_observer.api.types.processing.ProcessingItemKeyR\x03key\x12H\n" +
	"\x0fnext_processing\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x0enextProcessing\x88\x01\x01\x12F\n" +
	"\x0elast_processed\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\rlastProcessed\x88\x01\x01\x12\"\n" +
	"\n" +
	"last_error\x18\x04 \x01(\tH\x02R\tlastError\x88\x01\x01\x12#\n" +
	"\rno_processing\x18\x05 \x01(\bR\fnoProcessing\x12S\n" +
	"\x15processing_started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x03R\x13processingStartedAt\x88\x01\x01\x12N\n" +
	"\x04data\x18\b \x01(\v25.dev_observer.api.types.processing.ProcessingItemDataH\x04R\x04data\x88\x01\x01B\x12\n" +
	"\x10_next_processingB\x11\n" +
	"\x0f_last_processedB\r\n" +
	"\v_last_errorB\x18\n" +
	"\x16_processing_started_atB\a\n" +
	"\x05_dataJ\x04\b\x06\x10\aR\arequest\"\xb0\x01\n" +
	"\x13PeriodicAggregation\x12R\n" +
	"\x06params\x18\x01 \x01(\v2:.dev_observer.api.types.processing.AggregatedSummaryParamsR\x06params\x12E\n" +
	"\bschedule\x18\x02 \x01(\v2).dev_observer.api.types.schedule.ScheduleR\bschedule\"\xfd\x01\n" +
	"\x17AggregatedSummaryParams\x12$\n" +
	"\x0elook_back_days\x18\x01 \x01(\x05R\flookBackDays\x125\n" +
	"\bend_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12Y\n" +
	"\x06target\x18\x03 \x01(\v2A.dev_observer.api.types.processing.AggregatedSummaryParams.TargetR\x06target\x1a*\n" +
	"\x06Target\x12 \n" +
	"\fgit_repo_ids\x18\x01 \x03(\tR\n" +
	"gitRepoIds\"{\n" +
	"\x11ProcessingRequest\x12^\n" +
	"\vgit_changes\x18d \x01(\v2;.dev_observer.api.types.processing.ProcessGitChangesRequestH\x00R\n" +
	"gitChangesB\x06\n" +
	"\x04type\"`\n" +
	"\x18ProcessGitChangesRequest\x12\x1e\n" +
	"\vgit_repo_id\x18\x01 \x01(\tR\tgitRepoId\x12$\n" +
	"\x0elook_back_days\x18\x02 \x01(\x05R\flookBackDays\"\xd4\x03\n" +
	"\x14ProcessingItemResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12F\n" +
	"\x03key\x18\x02 \x01(\v24.dev_observer.api.types.processing.ProcessingItemKeyR\x03key\x12(\n" +
	"\rerror_message\x18\x04 \x01(\tH\x00R\ferrorMessage\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12N\n" +
	"\x04data\x18\a \x01(\v25.dev_observer.api.types.processing.ProcessingItemDataH\x01R\x04data\x88\x01\x01\x12a\n" +
	"\vresult_data\x18\b \x01(\v2;.dev_observer.api.types.processing.ProcessingItemResultDataH\x02R\n" +
	"resultData\x88\x01\x01B\x10\n" +
	"\x0e_error_messageB\a\n" +
	"\x05_dataB\x0e\n" +
	"\f_result_dataJ\x04\b\x06\x10\aJ\x04\b\x03\x10\x04R\arequestR\fobservations\"\x83\x01\n" +
	"\x0fRepoObservation\x12\x17\n" +
	"\arepo_id\x18\x01 \x01(\tR\x06repoId\x12W\n" +
	"\fobservations\x18\x02 \x03(\v23.dev_observer.api.types.observations.ObservationKeyR\fobservations\"|\n" +
	"\x19PeriodicAggregationResult\x12_\n" +
	"\x11repo_observations\x18\x01 \x03(\v22.dev_observer.api.types.processing.RepoObservationR\x10repoObservations\"\xf8\x02\n" +
	"\x12ProcessingItemData\x12&\n" +
	"\freference_id\x18\x01 \x01(\tH\x01R\vreferenceId\x88\x01\x01\x12!\n" +
	"\tnamespace\x18\x02 \x01(\tH\x02R\tnamespace\x88\x01\x01\x12\"\n" +
	"\n" +
	"created_by\x18\x03 \x01(\tH\x03R\tcreatedBy\x88\x01\x01\x12P\n" +
	"\arequest\x18d \x01(\v24.dev_observer.api.types.processing.ProcessingRequestH\x00R\arequest\x12k\n" +
	"\x14periodic_aggregation\x18e \x01(\v26.dev_observer.api.types.processing.PeriodicAggregationH\x00R\x13periodicAggregationB\x06\n" +
	"\x04typeB\x0f\n" +
	"\r_reference_idB\f\n" +
	"\n" +
	"_namespaceB\r\n" +
	"\v_created_by\"\xee\x01\n" +
	"\x18ProcessingItemResultData\x12W\n" +
	"\fobservations\x18\x01 \x03(\v23.dev_observer.api.types.observations.ObservationKeyR\fobservations\x12q\n" +
	"\x14periodic_aggregation\x18d \x01(\v2<.dev_observer.api.types.processing.PeriodicAggregationResultH\x00R\x13periodicAggregationB\x06\n" +
	"\x04type\"\x85\x02\n" +
	"\x16ProcessingResultFilter\x12!\n" +
	"\tnamespace\x18\x01 \x01(\tH\x00R\tnamespace\x88\x01\x01\x12&\n" +
	"\freference_id\x18\x02 \x01(\tH\x01R\vreferenceId\x88\x01\x01\x12&\n" +
	"\frequest_type\x18\x03 \x01(\tH\x02R\vrequestType\x88\x01\x01\x12H\n" +
	"\x04keys\x18\x04 \x03(\v24.dev_observer.api.types.processing.ProcessingItemKeyR\x04keysB\f\n" +
	"\n" +
	"_namespaceB\x0f\n" +
	"\r_reference_idB\x0f\n" +
	"\r_request_type\"\x84\x02\n" +
	"\x15ProcessingItemsFilter\x12!\n" +
	"\tnamespace\x18\x01 \x01(\tH\x00R\tnamespace\x88\x01\x01\x12&\n" +
	"\freference_id\x18\x02 \x01(\tH\x01R\vreferenceId\x88\x01\x01\x12&\n" +
	"\frequest_type\x18\x03 \x01(\tH\x02R\vrequestType\x88\x01\x01\x12H\n" +
	"\x04keys\x18\x04 \x03(\v24.dev_observer.api.types.processing.ProcessingItemKeyR\x04keysB\f\n" +
	"\n" +
	"_namespaceB\x0f\n" +
	"\r_reference_idB\x0f\n" +
	"\r_request_typeB8Z6github.com/devplaninc/contextify/clients/go/contextifyb\x06proto3"

var file_dev_observer_api_types_processing_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_dev_observer_api_types_processing_proto_goTypes = []any{
	(*ProcessingItemKey)(nil),              // 0: dev_observer.api.types.processing.ProcessingItemKey
	(*ProcessingItem)(nil),                 // 1: dev_observer.api.types.processing.ProcessingItem
	(*PeriodicAggregation)(nil),            // 2: dev_observer.api.types.processing.PeriodicAggregation
	(*AggregatedSummaryParams)(nil),        // 3: dev_observer.api.types.processing.AggregatedSummaryParams
	(*ProcessingRequest)(nil),              // 4: dev_observer.api.types.processing.ProcessingRequest
	(*ProcessGitChangesRequest)(nil),       // 5: dev_observer.api.types.processing.ProcessGitChangesRequest
	(*ProcessingItemResult)(nil),           // 6: dev_observer.api.types.processing.ProcessingItemResult
	(*RepoObservation)(nil),                // 7: dev_observer.api.types.processing.RepoObservation
	(*PeriodicAggregationResult)(nil),      // 8: dev_observer.api.types.processing.PeriodicAggregationResult
	(*ProcessingItemData)(nil),             // 9: dev_observer.api.types.processing.ProcessingItemData
	(*ProcessingItemResultData)(nil),       // 10: dev_observer.api.types.processing.ProcessingItemResultData
	(*ProcessingResultFilter)(nil),         // 11: dev_observer.api.types.processing.ProcessingResultFilter
	(*ProcessingItemsFilter)(nil),          // 12: dev_observer.api.types.processing.ProcessingItemsFilter
	(*AggregatedSummaryParams_Target)(nil), // 13: dev_observer.api.types.processing.AggregatedSummaryParams.Target
	(*timestamppb.Timestamp)(nil),          // 14: google.protobuf.Timestamp
	(*Schedule)(nil),                       // 15: dev_observer.api.types.schedule.Schedule
	(*ObservationKey)(nil),                 // 16: dev_observer.api.types.observations.ObservationKey
}
var file_dev_observer_api_types_processing_proto_depIdxs = []int32{
	0,  // 0: dev_observer.api.types.processing.ProcessingItem.key:type_name -> dev_observer.api.types.processing.ProcessingItemKey
	14, // 1: dev_observer.api.types.processing.ProcessingItem.next_processing:type_name -> google.protobuf.Timestamp
	14, // 2: dev_observer.api.types.processing.ProcessingItem.last_processed:type_name -> google.protobuf.Timestamp
	14, // 3: dev_observer.api.types.processing.ProcessingItem.processing_started_at:type_name -> google.protobuf.Timestamp
	9,  // 4: dev_observer.api.types.processing.ProcessingItem.data:type_name -> dev_observer.api.types.processing.ProcessingItemData
	3,  // 5: dev_observer.api.types.processing.PeriodicAggregation.params:type_name -> dev_observer.api.types.processing.AggregatedSummaryParams
	15, // 6: dev_observer.api.types.processing.PeriodicAggregation.schedule:type_name -> dev_observer.api.types.schedule.Schedule
	14, // 7: dev_observer.api.types.processing.AggregatedSummaryParams.end_date:type_name -> google.protobuf.Timestamp
	13, // 8: dev_observer.api.types.processing.AggregatedSummaryParams.target:type_name -> dev_observer.api.types.processing.AggregatedSummaryParams.Target
	5,  // 9: dev_observer.api.types.processing.ProcessingRequest.git_changes:type_name -> dev_observer.api.types.processing.ProcessGitChangesRequest
	0,  // 10: dev_observer.api.types.processing.ProcessingItemResult.key:type_name -> dev_observer.api.types.processing.ProcessingItemKey
	14, // 11: dev_observer.api.types.processing.ProcessingItemResult.created_at:type_name -> google.protobuf.Timestamp
	9,  // 12: dev_observer.api.types.processing.ProcessingItemResult.data:type_name -> dev_observer.api.types.processing.ProcessingItemData
	10, // 13: dev_observer.api.types.processing.ProcessingItemResult.result_data:type_name -> dev_observer.api.types.processing.ProcessingItemResultData
	16, // 14: dev_observer.api.types.processing.RepoObservation.observations:type_name -> dev_observer.api.types.observations.ObservationKey
	7,  // 15: dev_observer.api.types.processing.PeriodicAggregationResult.repo_observations:type_name -> dev_observer.api.types.processing.RepoObservation
	4,  // 16: dev_observer.api.types.processing.ProcessingItemData.request:type_name -> dev_observer.api.types.processing.ProcessingRequest
	2,  // 17: dev_observer.api.types.processing.ProcessingItemData.periodic_aggregation:type_name -> dev_observer.api.types.processing.PeriodicAggregation
	16, // 18: dev_observer.api.types.processing.ProcessingItemResultData.observations:type_name -> dev_observer.api.types.observations.ObservationKey
	8,  // 19: dev_observer.api.types.processing.ProcessingItemResultData.periodic_aggregation:type_name -> dev_observer.api.types.processing.PeriodicAggregationResult
	0,  // 20: dev_observer.api.types.processing.ProcessingResultFilter.keys:type_name -> dev_observer.api.types.processing.ProcessingItemKey
	0,  // 21: dev_observer.api.types.processing.ProcessingItemsFilter.keys:type_name -> dev_observer.api.types.processing.ProcessingItemKey
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_dev_observer_api_types_processing_proto_init() }
func file_dev_observer_api_types_processing_proto_init() {
	if File_dev_observer_api_types_processing_proto != nil {
		return
	}
	file_dev_observer_api_types_observations_proto_init()
	file_dev_observer_api_types_schedule_proto_init()
	file_dev_observer_api_types_processing_proto_msgTypes[0].OneofWrappers = []any{
		(*processingItemKey_GithubRepoId)(nil),
		(*processingItemKey_WebsiteUrl)(nil),
		(*processingItemKey_RequestId)(nil),
		(*processingItemKey_PeriodicAggregationId)(nil),
		(*processingItemKey_ResearchGitRepoId)(nil),
	}
	file_dev_observer_api_types_processing_proto_msgTypes[1].OneofWrappers = []any{}
	file_dev_observer_api_types_processing_proto_msgTypes[4].OneofWrappers = []any{
		(*processingRequest_GitChanges)(nil),
	}
	file_dev_observer_api_types_processing_proto_msgTypes[6].OneofWrappers = []any{}
	file_dev_observer_api_types_processing_proto_msgTypes[9].OneofWrappers = []any{
		(*processingItemData_Request)(nil),
		(*processingItemData_PeriodicAggregation)(nil),
	}
	file_dev_observer_api_types_processing_proto_msgTypes[10].OneofWrappers = []any{
		(*processingItemResultData_PeriodicAggregation)(nil),
	}
	file_dev_observer_api_types_processing_proto_msgTypes[11].OneofWrappers = []any{}
	file_dev_observer_api_types_processing_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dev_observer_api_types_processing_proto_rawDesc), len(file_dev_observer_api_types_processing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dev_observer_api_types_processing_proto_goTypes,
		DependencyIndexes: file_dev_observer_api_types_processing_proto_depIdxs,
		MessageInfos:      file_dev_observer_api_types_processing_proto_msgTypes,
	}.Build()
	File_dev_observer_api_types_processing_proto = out.File
	file_dev_observer_api_types_processing_proto_goTypes = nil
	file_dev_observer_api_types_processing_proto_depIdxs = nil
}
