// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: dev_observer/api/types/repo.proto

package contextify

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GitProvider int32

const (
	GitProvider_GITHUB     GitProvider = 0
	GitProvider_BIT_BUCKET GitProvider = 1
)

// Enum value maps for GitProvider.
var (
	GitProvider_name = map[int32]string{
		0: "GITHUB",
		1: "BIT_BUCKET",
	}
	GitProvider_value = map[string]int32{
		"GITHUB":     0,
		"BIT_BUCKET": 1,
	}
)

func (x GitProvider) Enum() *GitProvider {
	p := new(GitProvider)
	*p = x
	return p
}

func (x GitProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GitProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_dev_observer_api_types_repo_proto_enumTypes[0].Descriptor()
}

func (GitProvider) Type() protoreflect.EnumType {
	return &file_dev_observer_api_types_repo_proto_enumTypes[0]
}

func (x GitProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type ToolCallResult_ToolCallStatus int32

const (
	ToolCallResult_UNPROCESSED ToolCallResult_ToolCallStatus = 0
	ToolCallResult_SUCCESS     ToolCallResult_ToolCallStatus = 1
	ToolCallResult_FAILURE     ToolCallResult_ToolCallStatus = 2
)

// Enum value maps for ToolCallResult_ToolCallStatus.
var (
	ToolCallResult_ToolCallStatus_name = map[int32]string{
		0: "UNPROCESSED",
		1: "SUCCESS",
		2: "FAILURE",
	}
	ToolCallResult_ToolCallStatus_value = map[string]int32{
		"UNPROCESSED": 0,
		"SUCCESS":     1,
		"FAILURE":     2,
	}
)

func (x ToolCallResult_ToolCallStatus) Enum() *ToolCallResult_ToolCallStatus {
	p := new(ToolCallResult_ToolCallStatus)
	*p = x
	return p
}

func (x ToolCallResult_ToolCallStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ToolCallResult_ToolCallStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_dev_observer_api_types_repo_proto_enumTypes[1].Descriptor()
}

func (ToolCallResult_ToolCallStatus) Type() protoreflect.EnumType {
	return &file_dev_observer_api_types_repo_proto_enumTypes[1]
}

func (x ToolCallResult_ToolCallStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type GitRepository struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_Name        string                 `protobuf:"bytes,2,opt,name=name,proto3"`
	xxx_hidden_FullName    string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3"`
	xxx_hidden_Url         string                 `protobuf:"bytes,4,opt,name=url,proto3"`
	xxx_hidden_Description string                 `protobuf:"bytes,5,opt,name=description,proto3"`
	xxx_hidden_Provider    GitProvider            `protobuf:"varint,6,opt,name=provider,proto3,enum=dev_observer.api.types.repo.GitProvider"`
	xxx_hidden_Properties  *GitProperties         `protobuf:"bytes,7,opt,name=properties,proto3,oneof"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GitRepository) Reset() {
	*x = GitRepository{}
	mi := &file_dev_observer_api_types_repo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitRepository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitRepository) ProtoMessage() {}

func (x *GitRepository) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_repo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GitRepository) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *GitRepository) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *GitRepository) GetFullName() string {
	if x != nil {
		return x.xxx_hidden_FullName
	}
	return ""
}

func (x *GitRepository) GetUrl() string {
	if x != nil {
		return x.xxx_hidden_Url
	}
	return ""
}

func (x *GitRepository) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *GitRepository) GetProvider() GitProvider {
	if x != nil {
		return x.xxx_hidden_Provider
	}
	return GitProvider_GITHUB
}

func (x *GitRepository) GetProperties() *GitProperties {
	if x != nil {
		return x.xxx_hidden_Properties
	}
	return nil
}

func (x *GitRepository) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *GitRepository) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *GitRepository) SetFullName(v string) {
	x.xxx_hidden_FullName = v
}

func (x *GitRepository) SetUrl(v string) {
	x.xxx_hidden_Url = v
}

func (x *GitRepository) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *GitRepository) SetProvider(v GitProvider) {
	x.xxx_hidden_Provider = v
}

func (x *GitRepository) SetProperties(v *GitProperties) {
	x.xxx_hidden_Properties = v
}

func (x *GitRepository) HasProperties() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Properties != nil
}

func (x *GitRepository) ClearProperties() {
	x.xxx_hidden_Properties = nil
}

type GitRepository_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id          string
	Name        string
	FullName    string
	Url         string
	Description string
	Provider    GitProvider
	Properties  *GitProperties
}

func (b0 GitRepository_builder) Build() *GitRepository {
	m0 := &GitRepository{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_FullName = b.FullName
	x.xxx_hidden_Url = b.Url
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_Provider = b.Provider
	x.xxx_hidden_Properties = b.Properties
	return m0
}

type GitProperties struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_AppInfo       *GitAppInfo            `protobuf:"bytes,1,opt,name=app_info,json=appInfo,proto3,oneof"`
	xxx_hidden_Meta          *GitMeta               `protobuf:"bytes,2,opt,name=meta,proto3,oneof"`
	xxx_hidden_BitBucketInfo *BitBucketInfo         `protobuf:"bytes,3,opt,name=bit_bucket_info,json=bitBucketInfo,proto3,oneof"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *GitProperties) Reset() {
	*x = GitProperties{}
	mi := &file_dev_observer_api_types_repo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitProperties) ProtoMessage() {}

func (x *GitProperties) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_repo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GitProperties) GetAppInfo() *GitAppInfo {
	if x != nil {
		return x.xxx_hidden_AppInfo
	}
	return nil
}

func (x *GitProperties) GetMeta() *GitMeta {
	if x != nil {
		return x.xxx_hidden_Meta
	}
	return nil
}

func (x *GitProperties) GetBitBucketInfo() *BitBucketInfo {
	if x != nil {
		return x.xxx_hidden_BitBucketInfo
	}
	return nil
}

func (x *GitProperties) SetAppInfo(v *GitAppInfo) {
	x.xxx_hidden_AppInfo = v
}

func (x *GitProperties) SetMeta(v *GitMeta) {
	x.xxx_hidden_Meta = v
}

func (x *GitProperties) SetBitBucketInfo(v *BitBucketInfo) {
	x.xxx_hidden_BitBucketInfo = v
}

func (x *GitProperties) HasAppInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AppInfo != nil
}

func (x *GitProperties) HasMeta() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Meta != nil
}

func (x *GitProperties) HasBitBucketInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_BitBucketInfo != nil
}

func (x *GitProperties) ClearAppInfo() {
	x.xxx_hidden_AppInfo = nil
}

func (x *GitProperties) ClearMeta() {
	x.xxx_hidden_Meta = nil
}

func (x *GitProperties) ClearBitBucketInfo() {
	x.xxx_hidden_BitBucketInfo = nil
}

type GitProperties_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	AppInfo       *GitAppInfo
	Meta          *GitMeta
	BitBucketInfo *BitBucketInfo
}

func (b0 GitProperties_builder) Build() *GitProperties {
	m0 := &GitProperties{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_AppInfo = b.AppInfo
	x.xxx_hidden_Meta = b.Meta
	x.xxx_hidden_BitBucketInfo = b.BitBucketInfo
	return m0
}

type BitBucketInfo struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_WorkspaceUuid string                 `protobuf:"bytes,1,opt,name=workspace_uuid,json=workspaceUuid,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *BitBucketInfo) Reset() {
	*x = BitBucketInfo{}
	mi := &file_dev_observer_api_types_repo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BitBucketInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BitBucketInfo) ProtoMessage() {}

func (x *BitBucketInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_repo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BitBucketInfo) GetWorkspaceUuid() string {
	if x != nil {
		return x.xxx_hidden_WorkspaceUuid
	}
	return ""
}

func (x *BitBucketInfo) SetWorkspaceUuid(v string) {
	x.xxx_hidden_WorkspaceUuid = v
}

type BitBucketInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	WorkspaceUuid string
}

func (b0 BitBucketInfo_builder) Build() *BitBucketInfo {
	m0 := &BitBucketInfo{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_WorkspaceUuid = b.WorkspaceUuid
	return m0
}

type GitMeta struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_LastRefresh *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=last_refresh,json=lastRefresh,proto3"`
	xxx_hidden_CloneUrl    *string                `protobuf:"bytes,2,opt,name=clone_url,json=cloneUrl,proto3,oneof"`
	xxx_hidden_SizeKb      int32                  `protobuf:"varint,3,opt,name=size_kb,json=sizeKb,proto3,oneof"`
	xxx_hidden_TokensInfo  *TokensInfo            `protobuf:"bytes,4,opt,name=tokens_info,json=tokensInfo,proto3,oneof"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GitMeta) Reset() {
	*x = GitMeta{}
	mi := &file_dev_observer_api_types_repo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitMeta) ProtoMessage() {}

func (x *GitMeta) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_repo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GitMeta) GetLastRefresh() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_LastRefresh
	}
	return nil
}

func (x *GitMeta) GetCloneUrl() string {
	if x != nil {
		if x.xxx_hidden_CloneUrl != nil {
			return *x.xxx_hidden_CloneUrl
		}
		return ""
	}
	return ""
}

func (x *GitMeta) GetSizeKb() int32 {
	if x != nil {
		return x.xxx_hidden_SizeKb
	}
	return 0
}

func (x *GitMeta) GetTokensInfo() *TokensInfo {
	if x != nil {
		return x.xxx_hidden_TokensInfo
	}
	return nil
}

func (x *GitMeta) SetLastRefresh(v *timestamppb.Timestamp) {
	x.xxx_hidden_LastRefresh = v
}

func (x *GitMeta) SetCloneUrl(v string) {
	x.xxx_hidden_CloneUrl = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *GitMeta) SetSizeKb(v int32) {
	x.xxx_hidden_SizeKb = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *GitMeta) SetTokensInfo(v *TokensInfo) {
	x.xxx_hidden_TokensInfo = v
}

func (x *GitMeta) HasLastRefresh() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LastRefresh != nil
}

func (x *GitMeta) HasCloneUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GitMeta) HasSizeKb() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *GitMeta) HasTokensInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_TokensInfo != nil
}

func (x *GitMeta) ClearLastRefresh() {
	x.xxx_hidden_LastRefresh = nil
}

func (x *GitMeta) ClearCloneUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_CloneUrl = nil
}

func (x *GitMeta) ClearSizeKb() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_SizeKb = 0
}

func (x *GitMeta) ClearTokensInfo() {
	x.xxx_hidden_TokensInfo = nil
}

type GitMeta_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	LastRefresh *timestamppb.Timestamp
	CloneUrl    *string
	SizeKb      *int32
	TokensInfo  *TokensInfo
}

func (b0 GitMeta_builder) Build() *GitMeta {
	m0 := &GitMeta{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_LastRefresh = b.LastRefresh
	if b.CloneUrl != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_CloneUrl = b.CloneUrl
	}
	if b.SizeKb != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_SizeKb = *b.SizeKb
	}
	x.xxx_hidden_TokensInfo = b.TokensInfo
	return m0
}

type TokensInfo struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3"`
	xxx_hidden_TokensCount int32                  `protobuf:"varint,2,opt,name=tokens_count,json=tokensCount,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TokensInfo) Reset() {
	*x = TokensInfo{}
	mi := &file_dev_observer_api_types_repo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokensInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokensInfo) ProtoMessage() {}

func (x *TokensInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_repo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TokensInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *TokensInfo) GetTokensCount() int32 {
	if x != nil {
		return x.xxx_hidden_TokensCount
	}
	return 0
}

func (x *TokensInfo) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *TokensInfo) SetTokensCount(v int32) {
	x.xxx_hidden_TokensCount = v
}

func (x *TokensInfo) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *TokensInfo) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

type TokensInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	CreatedAt   *timestamppb.Timestamp
	TokensCount int32
}

func (b0 TokensInfo_builder) Build() *TokensInfo {
	m0 := &TokensInfo{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_TokensCount = b.TokensCount
	return m0
}

type GitAppInfo struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_LastRefresh    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=last_refresh,json=lastRefresh,proto3"`
	xxx_hidden_InstallationId int32                  `protobuf:"varint,2,opt,name=installation_id,json=installationId,proto3,oneof"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *GitAppInfo) Reset() {
	*x = GitAppInfo{}
	mi := &file_dev_observer_api_types_repo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitAppInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitAppInfo) ProtoMessage() {}

func (x *GitAppInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_repo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GitAppInfo) GetLastRefresh() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_LastRefresh
	}
	return nil
}

func (x *GitAppInfo) GetInstallationId() int32 {
	if x != nil {
		return x.xxx_hidden_InstallationId
	}
	return 0
}

func (x *GitAppInfo) SetLastRefresh(v *timestamppb.Timestamp) {
	x.xxx_hidden_LastRefresh = v
}

func (x *GitAppInfo) SetInstallationId(v int32) {
	x.xxx_hidden_InstallationId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *GitAppInfo) HasLastRefresh() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LastRefresh != nil
}

func (x *GitAppInfo) HasInstallationId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GitAppInfo) ClearLastRefresh() {
	x.xxx_hidden_LastRefresh = nil
}

func (x *GitAppInfo) ClearInstallationId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_InstallationId = 0
}

type GitAppInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	LastRefresh    *timestamppb.Timestamp
	InstallationId *int32
}

func (b0 GitAppInfo_builder) Build() *GitAppInfo {
	m0 := &GitAppInfo{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_LastRefresh = b.LastRefresh
	if b.InstallationId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_InstallationId = *b.InstallationId
	}
	return m0
}

type ReposFilter struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Provider    GitProvider            `protobuf:"varint,1,opt,name=provider,proto3,enum=dev_observer.api.types.repo.GitProvider,oneof"`
	xxx_hidden_Owner       *string                `protobuf:"bytes,2,opt,name=owner,proto3,oneof"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ReposFilter) Reset() {
	*x = ReposFilter{}
	mi := &file_dev_observer_api_types_repo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReposFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReposFilter) ProtoMessage() {}

func (x *ReposFilter) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_repo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReposFilter) GetProvider() GitProvider {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Provider
		}
	}
	return GitProvider_GITHUB
}

func (x *ReposFilter) GetOwner() string {
	if x != nil {
		if x.xxx_hidden_Owner != nil {
			return *x.xxx_hidden_Owner
		}
		return ""
	}
	return ""
}

func (x *ReposFilter) SetProvider(v GitProvider) {
	x.xxx_hidden_Provider = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ReposFilter) SetOwner(v string) {
	x.xxx_hidden_Owner = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ReposFilter) HasProvider() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ReposFilter) HasOwner() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ReposFilter) ClearProvider() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Provider = GitProvider_GITHUB
}

func (x *ReposFilter) ClearOwner() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Owner = nil
}

type ReposFilter_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Provider *GitProvider
	Owner    *string
}

func (b0 ReposFilter_builder) Build() *ReposFilter {
	m0 := &ReposFilter{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Provider != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Provider = *b.Provider
	}
	if b.Owner != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Owner = b.Owner
	}
	return m0
}

type CodeResearchMeta struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Summary      string                 `protobuf:"bytes,1,opt,name=summary,proto3"`
	xxx_hidden_CreatedAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3"`
	xxx_hidden_RepoFullName string                 `protobuf:"bytes,3,opt,name=repo_full_name,json=repoFullName,proto3"`
	xxx_hidden_RepoUrl      string                 `protobuf:"bytes,4,opt,name=repo_url,json=repoUrl,proto3"`
	xxx_hidden_AreaTitle    string                 `protobuf:"bytes,5,opt,name=area_title,json=areaTitle,proto3"`
	xxx_hidden_DirKey       *ObservationKey        `protobuf:"bytes,6,opt,name=dir_key,json=dirKey,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *CodeResearchMeta) Reset() {
	*x = CodeResearchMeta{}
	mi := &file_dev_observer_api_types_repo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeResearchMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeResearchMeta) ProtoMessage() {}

func (x *CodeResearchMeta) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_repo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CodeResearchMeta) GetSummary() string {
	if x != nil {
		return x.xxx_hidden_Summary
	}
	return ""
}

func (x *CodeResearchMeta) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *CodeResearchMeta) GetRepoFullName() string {
	if x != nil {
		return x.xxx_hidden_RepoFullName
	}
	return ""
}

func (x *CodeResearchMeta) GetRepoUrl() string {
	if x != nil {
		return x.xxx_hidden_RepoUrl
	}
	return ""
}

func (x *CodeResearchMeta) GetAreaTitle() string {
	if x != nil {
		return x.xxx_hidden_AreaTitle
	}
	return ""
}

func (x *CodeResearchMeta) GetDirKey() *ObservationKey {
	if x != nil {
		return x.xxx_hidden_DirKey
	}
	return nil
}

func (x *CodeResearchMeta) SetSummary(v string) {
	x.xxx_hidden_Summary = v
}

func (x *CodeResearchMeta) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *CodeResearchMeta) SetRepoFullName(v string) {
	x.xxx_hidden_RepoFullName = v
}

func (x *CodeResearchMeta) SetRepoUrl(v string) {
	x.xxx_hidden_RepoUrl = v
}

func (x *CodeResearchMeta) SetAreaTitle(v string) {
	x.xxx_hidden_AreaTitle = v
}

func (x *CodeResearchMeta) SetDirKey(v *ObservationKey) {
	x.xxx_hidden_DirKey = v
}

func (x *CodeResearchMeta) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *CodeResearchMeta) HasDirKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DirKey != nil
}

func (x *CodeResearchMeta) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *CodeResearchMeta) ClearDirKey() {
	x.xxx_hidden_DirKey = nil
}

type CodeResearchMeta_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Summary      string
	CreatedAt    *timestamppb.Timestamp
	RepoFullName string
	RepoUrl      string
	AreaTitle    string
	DirKey       *ObservationKey
}

func (b0 CodeResearchMeta_builder) Build() *CodeResearchMeta {
	m0 := &CodeResearchMeta{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Summary = b.Summary
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_RepoFullName = b.RepoFullName
	x.xxx_hidden_RepoUrl = b.RepoUrl
	x.xxx_hidden_AreaTitle = b.AreaTitle
	x.xxx_hidden_DirKey = b.DirKey
	return m0
}

type CodeResearchAreaMeta struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ResearchKey *ObservationKey        `protobuf:"bytes,1,opt,name=research_key,json=researchKey,proto3"`
	xxx_hidden_Meta        *CodeResearchMeta      `protobuf:"bytes,2,opt,name=meta,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CodeResearchAreaMeta) Reset() {
	*x = CodeResearchAreaMeta{}
	mi := &file_dev_observer_api_types_repo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeResearchAreaMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeResearchAreaMeta) ProtoMessage() {}

func (x *CodeResearchAreaMeta) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_repo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CodeResearchAreaMeta) GetResearchKey() *ObservationKey {
	if x != nil {
		return x.xxx_hidden_ResearchKey
	}
	return nil
}

func (x *CodeResearchAreaMeta) GetMeta() *CodeResearchMeta {
	if x != nil {
		return x.xxx_hidden_Meta
	}
	return nil
}

func (x *CodeResearchAreaMeta) SetResearchKey(v *ObservationKey) {
	x.xxx_hidden_ResearchKey = v
}

func (x *CodeResearchAreaMeta) SetMeta(v *CodeResearchMeta) {
	x.xxx_hidden_Meta = v
}

func (x *CodeResearchAreaMeta) HasResearchKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ResearchKey != nil
}

func (x *CodeResearchAreaMeta) HasMeta() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Meta != nil
}

func (x *CodeResearchAreaMeta) ClearResearchKey() {
	x.xxx_hidden_ResearchKey = nil
}

func (x *CodeResearchAreaMeta) ClearMeta() {
	x.xxx_hidden_Meta = nil
}

type CodeResearchAreaMeta_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ResearchKey *ObservationKey
	Meta        *CodeResearchMeta
}

func (b0 CodeResearchAreaMeta_builder) Build() *CodeResearchAreaMeta {
	m0 := &CodeResearchAreaMeta{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ResearchKey = b.ResearchKey
	x.xxx_hidden_Meta = b.Meta
	return m0
}

type CodeResearchOrganizationMeta struct {
	state                protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_AreaMetas *[]*CodeResearchAreaMeta `protobuf:"bytes,1,rep,name=area_metas,json=areaMetas,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CodeResearchOrganizationMeta) Reset() {
	*x = CodeResearchOrganizationMeta{}
	mi := &file_dev_observer_api_types_repo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeResearchOrganizationMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeResearchOrganizationMeta) ProtoMessage() {}

func (x *CodeResearchOrganizationMeta) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_repo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CodeResearchOrganizationMeta) GetAreaMetas() []*CodeResearchAreaMeta {
	if x != nil {
		if x.xxx_hidden_AreaMetas != nil {
			return *x.xxx_hidden_AreaMetas
		}
	}
	return nil
}

func (x *CodeResearchOrganizationMeta) SetAreaMetas(v []*CodeResearchAreaMeta) {
	x.xxx_hidden_AreaMetas = &v
}

type CodeResearchOrganizationMeta_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	AreaMetas []*CodeResearchAreaMeta
}

func (b0 CodeResearchOrganizationMeta_builder) Build() *CodeResearchOrganizationMeta {
	m0 := &CodeResearchOrganizationMeta{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_AreaMetas = &b.AreaMetas
	return m0
}

type ResearchLog struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items      *[]*ResearchLogItem    `protobuf:"bytes,1,rep,name=items,proto3"`
	xxx_hidden_StartedAt  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=started_at,json=startedAt,proto3"`
	xxx_hidden_FinishedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=finished_at,json=finishedAt,proto3"`
	xxx_hidden_TotalUsage *UsageMetadata         `protobuf:"bytes,6,opt,name=total_usage,json=totalUsage,proto3,oneof"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ResearchLog) Reset() {
	*x = ResearchLog{}
	mi := &file_dev_observer_api_types_repo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResearchLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResearchLog) ProtoMessage() {}

func (x *ResearchLog) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_repo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ResearchLog) GetItems() []*ResearchLogItem {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *ResearchLog) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_StartedAt
	}
	return nil
}

func (x *ResearchLog) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_FinishedAt
	}
	return nil
}

func (x *ResearchLog) GetTotalUsage() *UsageMetadata {
	if x != nil {
		return x.xxx_hidden_TotalUsage
	}
	return nil
}

func (x *ResearchLog) SetItems(v []*ResearchLogItem) {
	x.xxx_hidden_Items = &v
}

func (x *ResearchLog) SetStartedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_StartedAt = v
}

func (x *ResearchLog) SetFinishedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_FinishedAt = v
}

func (x *ResearchLog) SetTotalUsage(v *UsageMetadata) {
	x.xxx_hidden_TotalUsage = v
}

func (x *ResearchLog) HasStartedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_StartedAt != nil
}

func (x *ResearchLog) HasFinishedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_FinishedAt != nil
}

func (x *ResearchLog) HasTotalUsage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_TotalUsage != nil
}

func (x *ResearchLog) ClearStartedAt() {
	x.xxx_hidden_StartedAt = nil
}

func (x *ResearchLog) ClearFinishedAt() {
	x.xxx_hidden_FinishedAt = nil
}

func (x *ResearchLog) ClearTotalUsage() {
	x.xxx_hidden_TotalUsage = nil
}

type ResearchLog_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Items      []*ResearchLogItem
	StartedAt  *timestamppb.Timestamp
	FinishedAt *timestamppb.Timestamp
	TotalUsage *UsageMetadata
}

func (b0 ResearchLog_builder) Build() *ResearchLog {
	m0 := &ResearchLog{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	x.xxx_hidden_StartedAt = b.StartedAt
	x.xxx_hidden_FinishedAt = b.FinishedAt
	x.xxx_hidden_TotalUsage = b.TotalUsage
	return m0
}

type ResearchLogItem struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Observations string                 `protobuf:"bytes,1,opt,name=observations,proto3"`
	xxx_hidden_ToolCalls    *[]*ToolCallResult     `protobuf:"bytes,2,rep,name=tool_calls,json=toolCalls,proto3"`
	xxx_hidden_StartedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3"`
	xxx_hidden_FinishedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=finished_at,json=finishedAt,proto3"`
	xxx_hidden_Summary      string                 `protobuf:"bytes,5,opt,name=summary,proto3"`
	xxx_hidden_Usage        *UsageMetadata         `protobuf:"bytes,6,opt,name=usage,proto3,oneof"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ResearchLogItem) Reset() {
	*x = ResearchLogItem{}
	mi := &file_dev_observer_api_types_repo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResearchLogItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResearchLogItem) ProtoMessage() {}

func (x *ResearchLogItem) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_repo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ResearchLogItem) GetObservations() string {
	if x != nil {
		return x.xxx_hidden_Observations
	}
	return ""
}

func (x *ResearchLogItem) GetToolCalls() []*ToolCallResult {
	if x != nil {
		if x.xxx_hidden_ToolCalls != nil {
			return *x.xxx_hidden_ToolCalls
		}
	}
	return nil
}

func (x *ResearchLogItem) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_StartedAt
	}
	return nil
}

func (x *ResearchLogItem) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_FinishedAt
	}
	return nil
}

func (x *ResearchLogItem) GetSummary() string {
	if x != nil {
		return x.xxx_hidden_Summary
	}
	return ""
}

func (x *ResearchLogItem) GetUsage() *UsageMetadata {
	if x != nil {
		return x.xxx_hidden_Usage
	}
	return nil
}

func (x *ResearchLogItem) SetObservations(v string) {
	x.xxx_hidden_Observations = v
}

func (x *ResearchLogItem) SetToolCalls(v []*ToolCallResult) {
	x.xxx_hidden_ToolCalls = &v
}

func (x *ResearchLogItem) SetStartedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_StartedAt = v
}

func (x *ResearchLogItem) SetFinishedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_FinishedAt = v
}

func (x *ResearchLogItem) SetSummary(v string) {
	x.xxx_hidden_Summary = v
}

func (x *ResearchLogItem) SetUsage(v *UsageMetadata) {
	x.xxx_hidden_Usage = v
}

func (x *ResearchLogItem) HasStartedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_StartedAt != nil
}

func (x *ResearchLogItem) HasFinishedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_FinishedAt != nil
}

func (x *ResearchLogItem) HasUsage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Usage != nil
}

func (x *ResearchLogItem) ClearStartedAt() {
	x.xxx_hidden_StartedAt = nil
}

func (x *ResearchLogItem) ClearFinishedAt() {
	x.xxx_hidden_FinishedAt = nil
}

func (x *ResearchLogItem) ClearUsage() {
	x.xxx_hidden_Usage = nil
}

type ResearchLogItem_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Observations string
	ToolCalls    []*ToolCallResult
	StartedAt    *timestamppb.Timestamp
	FinishedAt   *timestamppb.Timestamp
	Summary      string
	Usage        *UsageMetadata
}

func (b0 ResearchLogItem_builder) Build() *ResearchLogItem {
	m0 := &ResearchLogItem{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Observations = b.Observations
	x.xxx_hidden_ToolCalls = &b.ToolCalls
	x.xxx_hidden_StartedAt = b.StartedAt
	x.xxx_hidden_FinishedAt = b.FinishedAt
	x.xxx_hidden_Summary = b.Summary
	x.xxx_hidden_Usage = b.Usage
	return m0
}

type ToolCallResult struct {
	state                        protoimpl.MessageState        `protogen:"opaque.v1"`
	xxx_hidden_RequestedToolCall string                        `protobuf:"bytes,1,opt,name=requested_tool_call,json=requestedToolCall,proto3"`
	xxx_hidden_Result            string                        `protobuf:"bytes,2,opt,name=result,proto3"`
	xxx_hidden_Status            ToolCallResult_ToolCallStatus `protobuf:"varint,3,opt,name=status,proto3,enum=dev_observer.api.types.repo.ToolCallResult_ToolCallStatus"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *ToolCallResult) Reset() {
	*x = ToolCallResult{}
	mi := &file_dev_observer_api_types_repo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallResult) ProtoMessage() {}

func (x *ToolCallResult) ProtoReflect() protoreflect.Message {
	mi := &file_dev_observer_api_types_repo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ToolCallResult) GetRequestedToolCall() string {
	if x != nil {
		return x.xxx_hidden_RequestedToolCall
	}
	return ""
}

func (x *ToolCallResult) GetResult() string {
	if x != nil {
		return x.xxx_hidden_Result
	}
	return ""
}

func (x *ToolCallResult) GetStatus() ToolCallResult_ToolCallStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return ToolCallResult_UNPROCESSED
}

func (x *ToolCallResult) SetRequestedToolCall(v string) {
	x.xxx_hidden_RequestedToolCall = v
}

func (x *ToolCallResult) SetResult(v string) {
	x.xxx_hidden_Result = v
}

func (x *ToolCallResult) SetStatus(v ToolCallResult_ToolCallStatus) {
	x.xxx_hidden_Status = v
}

type ToolCallResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RequestedToolCall string
	Result            string
	Status            ToolCallResult_ToolCallStatus
}

func (b0 ToolCallResult_builder) Build() *ToolCallResult {
	m0 := &ToolCallResult{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RequestedToolCall = b.RequestedToolCall
	x.xxx_hidden_Result = b.Result
	x.xxx_hidden_Status = b.Status
	return m0
}

var File_dev_observer_api_types_repo_proto protoreflect.FileDescriptor

const file_dev_observer_api_types_repo_proto_rawDesc = "" +
	"\n" +
	"!dev_observer/api/types/repo.proto\x12\x1bdev_observer.api.types.repo\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1fdev_observer/api/types/ai.proto\x1a)dev_observer/api/types/observations.proto\"\xaa\x02\n" +
	"\rGitRepository\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12D\n" +
	"\bprovider\x18\x06 \x01(\x0e2(.dev_observer.api.types.repo.GitProviderR\bprovider\x12O\n" +
	"\n" +
	"properties\x18\a \x01(\v2*.dev_observer.api.types.repo.GitPropertiesH\x00R\n" +
	"properties\x88\x01\x01B\r\n" +
	"\v_properties\"\x9a\x02\n" +
	"\rGitProperties\x12G\n" +
	"\bapp_info\x18\x01 \x01(\v2'.dev_observer.api.types.repo.GitAppInfoH\x00R\aappInfo\x88\x01\x01\x12=\n" +
	"\x04meta\x18\x02 \x01(\v2$.dev_observer.api.types.repo.GitMetaH\x01R\x04meta\x88\x01\x01\x12W\n" +
	"\x0fbit_bucket_info\x18\x03 \x01(\v2*.dev_observer.api.types.repo.BitBucketInfoH\x02R\rbitBucketInfo\x88\x01\x01B\v\n" +
	"\t_app_infoB\a\n" +
	"\x05_metaB\x12\n" +
	"\x10_bit_bucket_info\"6\n" +
	"\rBitBucketInfo\x12%\n" +
	"\x0eworkspace_uuid\x18\x01 \x01(\tR\rworkspaceUuid\"\x81\x02\n" +
	"\aGitMeta\x12=\n" +
	"\flast_refresh\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\vlastRefresh\x12 \n" +
	"\tclone_url\x18\x02 \x01(\tH\x00R\bcloneUrl\x88\x01\x01\x12\x1c\n" +
	"\asize_kb\x18\x03 \x01(\x05H\x01R\x06sizeKb\x88\x01\x01\x12M\n" +
	"\vtokens_info\x18\x04 \x01(\v2'.dev_observer.api.types.repo.TokensInfoH\x02R\n" +
	"tokensInfo\x88\x01\x01B\f\n" +
	"\n" +
	"_clone_urlB\n" +
	"\n" +
	"\b_size_kbB\x0e\n" +
	"\f_tokens_info\"j\n" +
	"\n" +
	"TokensInfo\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12!\n" +
	"\ftokens_count\x18\x02 \x01(\x05R\vtokensCount\"\x8d\x01\n" +
	"\n" +
	"GitAppInfo\x12=\n" +
	"\flast_refresh\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\vlastRefresh\x12,\n" +
	"\x0finstallation_id\x18\x02 \x01(\x05H\x00R\x0einstallationId\x88\x01\x01B\x12\n" +
	"\x10_installation_id\"\x8a\x01\n" +
	"\vReposFilter\x12I\n" +
	"\bprovider\x18\x01 \x01(\x0e2(.dev_observer.api.types.repo.GitProviderH\x00R\bprovider\x88\x01\x01\x12\x19\n" +
	"\x05owner\x18\x02 \x01(\tH\x01R\x05owner\x88\x01\x01B\v\n" +
	"\t_providerB\b\n" +
	"\x06_owner\"\x95\x02\n" +
	"\x10CodeResearchMeta\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12$\n" +
	"\x0erepo_full_name\x18\x03 \x01(\tR\frepoFullName\x12\x19\n" +
	"\brepo_url\x18\x04 \x01(\tR\arepoUrl\x12\x1d\n" +
	"\n" +
	"area_title\x18\x05 \x01(\tR\tareaTitle\x12L\n" +
	"\adir_key\x18\x06 \x01(\v23.dev_observer.api.types.observations.ObservationKeyR\x06dirKey\"\xb1\x01\n" +
	"\x14CodeResearchAreaMeta\x12V\n" +
	"\fresearch_key\x18\x01 \x01(\v23.dev_observer.api.types.observations.ObservationKeyR\vresearchKey\x12A\n" +
	"\x04meta\x18\x02 \x01(\v2-.dev_observer.api.types.repo.CodeResearchMetaR\x04meta\"p\n" +
	"\x1cCodeResearchOrganizationMeta\x12P\n" +
	"\n" +
	"area_metas\x18\x01 \x03(\v21.dev_observer.api.types.repo.CodeResearchAreaMetaR\tareaMetas\"\xa9\x02\n" +
	"\vResearchLog\x12B\n" +
	"\x05items\x18\x01 \x03(\v2,.dev_observer.api.types.repo.ResearchLogItemR\x05items\x129\n" +
	"\n" +
	"started_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12N\n" +
	"\vtotal_usage\x18\x06 \x01(\v2(.dev_observer.api.types.ai.UsageMetadataH\x00R\n" +
	"totalUsage\x88\x01\x01B\x0e\n" +
	"\f_total_usage\"\xe2\x02\n" +
	"\x0fResearchLogItem\x12\"\n" +
	"\fobservations\x18\x01 \x01(\tR\fobservations\x12J\n" +
	"\n" +
	"tool_calls\x18\x02 \x03(\v2+.dev_observer.api.types.repo.ToolCallResultR\ttoolCalls\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12C\n" +
	"\x05usage\x18\x06 \x01(\v2(.dev_observer.api.types.ai.UsageMetadataH\x00R\x05usage\x88\x01\x01B\b\n" +
	"\x06_usage\"\xe9\x01\n" +
	"\x0eToolCallResult\x12.\n" +
	"\x13requested_tool_call\x18\x01 \x01(\tR\x11requestedToolCall\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12R\n" +
	"\x06status\x18\x03 \x01(\x0e2:.dev_observer.api.types.repo.ToolCallResult.ToolCallStatusR\x06status\";\n" +
	"\x0eToolCallStatus\x12\x0f\n" +
	"\vUNPROCESSED\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\v\n" +
	"\aFAILURE\x10\x02*)\n" +
	"\vGitProvider\x12\n" +
	"\n" +
	"\x06GITHUB\x10\x00\x12\x0e\n" +
	"\n" +
	"BIT_BUCKET\x10\x01B8Z6github.com/devplaninc/contextify/clients/go/contextifyb\x06proto3"

var file_dev_observer_api_types_repo_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_dev_observer_api_types_repo_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_dev_observer_api_types_repo_proto_goTypes = []any{
	(GitProvider)(0),                     // 0: dev_observer.api.types.repo.GitProvider
	(ToolCallResult_ToolCallStatus)(0),   // 1: dev_observer.api.types.repo.ToolCallResult.ToolCallStatus
	(*GitRepository)(nil),                // 2: dev_observer.api.types.repo.GitRepository
	(*GitProperties)(nil),                // 3: dev_observer.api.types.repo.GitProperties
	(*BitBucketInfo)(nil),                // 4: dev_observer.api.types.repo.BitBucketInfo
	(*GitMeta)(nil),                      // 5: dev_observer.api.types.repo.GitMeta
	(*TokensInfo)(nil),                   // 6: dev_observer.api.types.repo.TokensInfo
	(*GitAppInfo)(nil),                   // 7: dev_observer.api.types.repo.GitAppInfo
	(*ReposFilter)(nil),                  // 8: dev_observer.api.types.repo.ReposFilter
	(*CodeResearchMeta)(nil),             // 9: dev_observer.api.types.repo.CodeResearchMeta
	(*CodeResearchAreaMeta)(nil),         // 10: dev_observer.api.types.repo.CodeResearchAreaMeta
	(*CodeResearchOrganizationMeta)(nil), // 11: dev_observer.api.types.repo.CodeResearchOrganizationMeta
	(*ResearchLog)(nil),                  // 12: dev_observer.api.types.repo.ResearchLog
	(*ResearchLogItem)(nil),              // 13: dev_observer.api.types.repo.ResearchLogItem
	(*ToolCallResult)(nil),               // 14: dev_observer.api.types.repo.ToolCallResult
	(*timestamppb.Timestamp)(nil),        // 15: google.protobuf.Timestamp
	(*ObservationKey)(nil),               // 16: dev_observer.api.types.observations.ObservationKey
	(*UsageMetadata)(nil),                // 17: dev_observer.api.types.ai.UsageMetadata
}
var file_dev_observer_api_types_repo_proto_depIdxs = []int32{
	0,  // 0: dev_observer.api.types.repo.GitRepository.provider:type_name -> dev_observer.api.types.repo.GitProvider
	3,  // 1: dev_observer.api.types.repo.GitRepository.properties:type_name -> dev_observer.api.types.repo.GitProperties
	7,  // 2: dev_observer.api.types.repo.GitProperties.app_info:type_name -> dev_observer.api.types.repo.GitAppInfo
	5,  // 3: dev_observer.api.types.repo.GitProperties.meta:type_name -> dev_observer.api.types.repo.GitMeta
	4,  // 4: dev_observer.api.types.repo.GitProperties.bit_bucket_info:type_name -> dev_observer.api.types.repo.BitBucketInfo
	15, // 5: dev_observer.api.types.repo.GitMeta.last_refresh:type_name -> google.protobuf.Timestamp
	6,  // 6: dev_observer.api.types.repo.GitMeta.tokens_info:type_name -> dev_observer.api.types.repo.TokensInfo
	15, // 7: dev_observer.api.types.repo.TokensInfo.created_at:type_name -> google.protobuf.Timestamp
	15, // 8: dev_observer.api.types.repo.GitAppInfo.last_refresh:type_name -> google.protobuf.Timestamp
	0,  // 9: dev_observer.api.types.repo.ReposFilter.provider:type_name -> dev_observer.api.types.repo.GitProvider
	15, // 10: dev_observer.api.types.repo.CodeResearchMeta.created_at:type_name -> google.protobuf.Timestamp
	16, // 11: dev_observer.api.types.repo.CodeResearchMeta.dir_key:type_name -> dev_observer.api.types.observations.ObservationKey
	16, // 12: dev_observer.api.types.repo.CodeResearchAreaMeta.research_key:type_name -> dev_observer.api.types.observations.ObservationKey
	9,  // 13: dev_observer.api.types.repo.CodeResearchAreaMeta.meta:type_name -> dev_observer.api.types.repo.CodeResearchMeta
	10, // 14: dev_observer.api.types.repo.CodeResearchOrganizationMeta.area_metas:type_name -> dev_observer.api.types.repo.CodeResearchAreaMeta
	13, // 15: dev_observer.api.types.repo.ResearchLog.items:type_name -> dev_observer.api.types.repo.ResearchLogItem
	15, // 16: dev_observer.api.types.repo.ResearchLog.started_at:type_name -> google.protobuf.Timestamp
	15, // 17: dev_observer.api.types.repo.ResearchLog.finished_at:type_name -> google.protobuf.Timestamp
	17, // 18: dev_observer.api.types.repo.ResearchLog.total_usage:type_name -> dev_observer.api.types.ai.UsageMetadata
	14, // 19: dev_observer.api.types.repo.ResearchLogItem.tool_calls:type_name -> dev_observer.api.types.repo.ToolCallResult
	15, // 20: dev_observer.api.types.repo.ResearchLogItem.started_at:type_name -> google.protobuf.Timestamp
	15, // 21: dev_observer.api.types.repo.ResearchLogItem.finished_at:type_name -> google.protobuf.Timestamp
	17, // 22: dev_observer.api.types.repo.ResearchLogItem.usage:type_name -> dev_observer.api.types.ai.UsageMetadata
	1,  // 23: dev_observer.api.types.repo.ToolCallResult.status:type_name -> dev_observer.api.types.repo.ToolCallResult.ToolCallStatus
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_dev_observer_api_types_repo_proto_init() }
func file_dev_observer_api_types_repo_proto_init() {
	if File_dev_observer_api_types_repo_proto != nil {
		return
	}
	file_dev_observer_api_types_ai_proto_init()
	file_dev_observer_api_types_observations_proto_init()
	file_dev_observer_api_types_repo_proto_msgTypes[0].OneofWrappers = []any{}
	file_dev_observer_api_types_repo_proto_msgTypes[1].OneofWrappers = []any{}
	file_dev_observer_api_types_repo_proto_msgTypes[3].OneofWrappers = []any{}
	file_dev_observer_api_types_repo_proto_msgTypes[5].OneofWrappers = []any{}
	file_dev_observer_api_types_repo_proto_msgTypes[6].OneofWrappers = []any{}
	file_dev_observer_api_types_repo_proto_msgTypes[10].OneofWrappers = []any{}
	file_dev_observer_api_types_repo_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dev_observer_api_types_repo_proto_rawDesc), len(file_dev_observer_api_types_repo_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dev_observer_api_types_repo_proto_goTypes,
		DependencyIndexes: file_dev_observer_api_types_repo_proto_depIdxs,
		EnumInfos:         file_dev_observer_api_types_repo_proto_enumTypes,
		MessageInfos:      file_dev_observer_api_types_repo_proto_msgTypes,
	}.Build()
	File_dev_observer_api_types_repo_proto = out.File
	file_dev_observer_api_types_repo_proto_goTypes = nil
	file_dev_observer_api_types_repo_proto_depIdxs = nil
}
