"""repo_owner

Revision ID: 990bd8273f85
Revises: 50496cc07758
Create Date: 2025-08-07 23:00:17.162633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '990bd8273f85'
down_revision: Union[str, None] = '50496cc07758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('git_repo', sa.Column('owner', sa.String(), nullable=True))
    op.execute("UPDATE git_repo  SET owner = LOWER(SPLIT_PART(full_name, '/', 1))")
    op.alter_column('git_repo', 'owner', nullable=False)
    op.create_index(op.f('ix_git_repo_owner'), 'git_repo', ['owner'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_git_repo_owner'), table_name='git_repo')
    op.drop_column('git_repo', 'owner')
    # ### end Alembic commands ###
