# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dev_observer/api/web/repositories.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'dev_observer/api/web/repositories.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dev_observer.api.types import repo_pb2 as dev__observer_dot_api_dot_types_dot_repo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'dev_observer/api/web/repositories.proto\x12!dev_observer.api.web.repositories\x1a!dev_observer/api/types/repo.proto\"U\n\x18ListRepositoriesResponse\x12\x39\n\x05repos\x18\x01 \x03(\x0b\x32*.dev_observer.api.types.repo.GitRepository\"_\n\x14\x41\x64\x64RepositoryRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\x12:\n\x08provider\x18\x02 \x01(\x0e\x32(.dev_observer.api.types.repo.GitProvider\"Q\n\x15\x41\x64\x64RepositoryResponse\x12\x38\n\x04repo\x18\x01 \x01(\x0b\x32*.dev_observer.api.types.repo.GitRepository\"i\n\x17RescanRepositoryRequest\x12\x15\n\x08research\x18\x01 \x01(\x08H\x00\x88\x01\x01\x12\x19\n\x0cskip_summary\x18\x02 \x01(\x08H\x01\x88\x01\x01\x42\x0b\n\t_researchB\x0f\n\r_skip_summary\"\x1a\n\x18RescanRepositoryResponse\"Q\n\x15GetRepositoryResponse\x12\x38\n\x04repo\x18\x01 \x01(\x0b\x32*.dev_observer.api.types.repo.GitRepository\"U\n\x18\x44\x65leteRepositoryResponse\x12\x39\n\x05repos\x18\x01 \x03(\x0b\x32*.dev_observer.api.types.repo.GitRepository\"U\n\x19\x46ilterRepositoriesRequest\x12\x38\n\x06\x66ilter\x18\x01 \x01(\x0b\x32(.dev_observer.api.types.repo.ReposFilter\"W\n\x1a\x46ilterRepositoriesResponse\x12\x39\n\x05repos\x18\x01 \x03(\x0b\x32*.dev_observer.api.types.repo.GitRepository\"-\n\x1cRescanAnalysisSummaryRequest\x12\r\n\x05\x66orce\x18\x01 \x01(\x08\"\x1f\n\x1dRescanAnalysisSummaryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dev_observer.api.web.repositories_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTREPOSITORIESRESPONSE']._serialized_start=113
  _globals['_LISTREPOSITORIESRESPONSE']._serialized_end=198
  _globals['_ADDREPOSITORYREQUEST']._serialized_start=200
  _globals['_ADDREPOSITORYREQUEST']._serialized_end=295
  _globals['_ADDREPOSITORYRESPONSE']._serialized_start=297
  _globals['_ADDREPOSITORYRESPONSE']._serialized_end=378
  _globals['_RESCANREPOSITORYREQUEST']._serialized_start=380
  _globals['_RESCANREPOSITORYREQUEST']._serialized_end=485
  _globals['_RESCANREPOSITORYRESPONSE']._serialized_start=487
  _globals['_RESCANREPOSITORYRESPONSE']._serialized_end=513
  _globals['_GETREPOSITORYRESPONSE']._serialized_start=515
  _globals['_GETREPOSITORYRESPONSE']._serialized_end=596
  _globals['_DELETEREPOSITORYRESPONSE']._serialized_start=598
  _globals['_DELETEREPOSITORYRESPONSE']._serialized_end=683
  _globals['_FILTERREPOSITORIESREQUEST']._serialized_start=685
  _globals['_FILTERREPOSITORIESREQUEST']._serialized_end=770
  _globals['_FILTERREPOSITORIESRESPONSE']._serialized_start=772
  _globals['_FILTERREPOSITORIESRESPONSE']._serialized_end=859
  _globals['_RESCANANALYSISSUMMARYREQUEST']._serialized_start=861
  _globals['_RESCANANALYSISSUMMARYREQUEST']._serialized_end=906
  _globals['_RESCANANALYSISSUMMARYRESPONSE']._serialized_start=908
  _globals['_RESCANANALYSISSUMMARYRESPONSE']._serialized_end=939
# @@protoc_insertion_point(module_scope)
