[git.github]
auth_type = "token"

[prompts]
provider = "local"

[prompts.local]
dir = "prompts"

[observations.local]
dir = "_local_data_"

[analysis]
provider = "stub"

[tokenizer]
provider = "stub"

[storage]
provider = "local"
[storage.local]
dir = "_local_data_/__storage"
