services:
  dev-observer-pg:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: dev_observer
      PGDATA: /opt/pgsql/data
    ports:
      - 54322:5432
    volumes:
      - ${PG_DATA_PATH}:/opt/pgsql/data
    privileged: true