// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.1
// source: dev_observer/api/types/processing.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "../../../google/protobuf/timestamp";
import { ObservationKey } from "./observations";
import { Schedule } from "./schedule";

export const protobufPackage = "dev_observer.api.types.processing";

export interface ProcessingItemKey {
  entity?:
    | //
    /** Repo summary processing. */
    { $case: "githubRepoId"; value: string }
    | //
    /** Website summary processing. */
    { $case: "websiteUrl"; value: string }
    | //
    /** One-off request */
    { $case: "requestId"; value: string }
    | { $case: "periodicAggregationId"; value: string }
    | //
    /** Periodic repo research. */
    { $case: "researchGitRepoId"; value: string }
    | undefined;
}

export interface ProcessingItem {
  key: ProcessingItemKey | undefined;
  nextProcessing?: Date | undefined;
  lastProcessed?: Date | undefined;
  lastError?: string | undefined;
  noProcessing: boolean;
  processingStartedAt?: Date | undefined;
  data?: ProcessingItemData | undefined;
}

export interface PeriodicAggregation {
  params: AggregatedSummaryParams | undefined;
  schedule: Schedule | undefined;
}

export interface AggregatedSummaryParams {
  lookBackDays: number;
  endDate: Date | undefined;
  target: AggregatedSummaryParams_Target | undefined;
}

export interface AggregatedSummaryParams_Target {
  gitRepoIds: string[];
}

export interface ProcessingRequest {
  type?: { $case: "gitChanges"; value: ProcessGitChangesRequest } | undefined;
}

export interface ProcessGitChangesRequest {
  gitRepoId: string;
  lookBackDays: number;
}

export interface ProcessingItemResult {
  /** Unique id of the result */
  id: string;
  key: ProcessingItemKey | undefined;
  errorMessage?: string | undefined;
  createdAt: Date | undefined;
  data?: ProcessingItemData | undefined;
  resultData?: ProcessingItemResultData | undefined;
}

export interface RepoObservation {
  repoId: string;
  observations: ObservationKey[];
}

export interface PeriodicAggregationResult {
  repoObservations: RepoObservation[];
}

export interface ProcessingItemData {
  /** Free form indexed reference id that may be useful for connecting request to a specific repo or other entity. */
  referenceId?: string | undefined;
  namespace?: string | undefined;
  createdBy?: string | undefined;
  type?:
    | { $case: "request"; value: ProcessingRequest }
    | { $case: "periodicAggregation"; value: PeriodicAggregation }
    | undefined;
}

export interface ProcessingItemResultData {
  observations: ObservationKey[];
  type?: { $case: "periodicAggregation"; value: PeriodicAggregationResult } | undefined;
}

export interface ProcessingResultFilter {
  namespace?: string | undefined;
  referenceId?: string | undefined;
  requestType?: string | undefined;
  keys: ProcessingItemKey[];
}

export interface ProcessingItemsFilter {
  namespace?: string | undefined;
  referenceId?: string | undefined;
  requestType?: string | undefined;
  keys: ProcessingItemKey[];
}

function createBaseProcessingItemKey(): ProcessingItemKey {
  return { entity: undefined };
}

export const ProcessingItemKey: MessageFns<ProcessingItemKey> = {
  encode(message: ProcessingItemKey, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    switch (message.entity?.$case) {
      case "githubRepoId":
        writer.uint32(802).string(message.entity.value);
        break;
      case "websiteUrl":
        writer.uint32(810).string(message.entity.value);
        break;
      case "requestId":
        writer.uint32(818).string(message.entity.value);
        break;
      case "periodicAggregationId":
        writer.uint32(826).string(message.entity.value);
        break;
      case "researchGitRepoId":
        writer.uint32(834).string(message.entity.value);
        break;
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProcessingItemKey {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProcessingItemKey();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 100: {
          if (tag !== 802) {
            break;
          }

          message.entity = { $case: "githubRepoId", value: reader.string() };
          continue;
        }
        case 101: {
          if (tag !== 810) {
            break;
          }

          message.entity = { $case: "websiteUrl", value: reader.string() };
          continue;
        }
        case 102: {
          if (tag !== 818) {
            break;
          }

          message.entity = { $case: "requestId", value: reader.string() };
          continue;
        }
        case 103: {
          if (tag !== 826) {
            break;
          }

          message.entity = { $case: "periodicAggregationId", value: reader.string() };
          continue;
        }
        case 104: {
          if (tag !== 834) {
            break;
          }

          message.entity = { $case: "researchGitRepoId", value: reader.string() };
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProcessingItemKey {
    return {
      entity: isSet(object.githubRepoId)
        ? { $case: "githubRepoId", value: gt.String(object.githubRepoId) }
        : isSet(object.websiteUrl)
        ? { $case: "websiteUrl", value: gt.String(object.websiteUrl) }
        : isSet(object.requestId)
        ? { $case: "requestId", value: gt.String(object.requestId) }
        : isSet(object.periodicAggregationId)
        ? { $case: "periodicAggregationId", value: gt.String(object.periodicAggregationId) }
        : isSet(object.researchGitRepoId)
        ? { $case: "researchGitRepoId", value: gt.String(object.researchGitRepoId) }
        : undefined,
    };
  },

  toJSON(message: ProcessingItemKey): unknown {
    const obj: any = {};
    if (message.entity?.$case === "githubRepoId") {
      obj.githubRepoId = message.entity.value;
    } else if (message.entity?.$case === "websiteUrl") {
      obj.websiteUrl = message.entity.value;
    } else if (message.entity?.$case === "requestId") {
      obj.requestId = message.entity.value;
    } else if (message.entity?.$case === "periodicAggregationId") {
      obj.periodicAggregationId = message.entity.value;
    } else if (message.entity?.$case === "researchGitRepoId") {
      obj.researchGitRepoId = message.entity.value;
    }
    return obj;
  },

  create(base?: DeepPartial<ProcessingItemKey>): ProcessingItemKey {
    return ProcessingItemKey.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ProcessingItemKey>): ProcessingItemKey {
    const message = createBaseProcessingItemKey();
    switch (object.entity?.$case) {
      case "githubRepoId": {
        if (object.entity?.value !== undefined && object.entity?.value !== null) {
          message.entity = { $case: "githubRepoId", value: object.entity.value };
        }
        break;
      }
      case "websiteUrl": {
        if (object.entity?.value !== undefined && object.entity?.value !== null) {
          message.entity = { $case: "websiteUrl", value: object.entity.value };
        }
        break;
      }
      case "requestId": {
        if (object.entity?.value !== undefined && object.entity?.value !== null) {
          message.entity = { $case: "requestId", value: object.entity.value };
        }
        break;
      }
      case "periodicAggregationId": {
        if (object.entity?.value !== undefined && object.entity?.value !== null) {
          message.entity = { $case: "periodicAggregationId", value: object.entity.value };
        }
        break;
      }
      case "researchGitRepoId": {
        if (object.entity?.value !== undefined && object.entity?.value !== null) {
          message.entity = { $case: "researchGitRepoId", value: object.entity.value };
        }
        break;
      }
    }
    return message;
  },
};

function createBaseProcessingItem(): ProcessingItem {
  return {
    key: undefined,
    nextProcessing: undefined,
    lastProcessed: undefined,
    lastError: undefined,
    noProcessing: false,
    processingStartedAt: undefined,
    data: undefined,
  };
}

export const ProcessingItem: MessageFns<ProcessingItem> = {
  encode(message: ProcessingItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== undefined) {
      ProcessingItemKey.encode(message.key, writer.uint32(10).fork()).join();
    }
    if (message.nextProcessing !== undefined) {
      Timestamp.encode(toTimestamp(message.nextProcessing), writer.uint32(18).fork()).join();
    }
    if (message.lastProcessed !== undefined) {
      Timestamp.encode(toTimestamp(message.lastProcessed), writer.uint32(26).fork()).join();
    }
    if (message.lastError !== undefined) {
      writer.uint32(34).string(message.lastError);
    }
    if (message.noProcessing !== false) {
      writer.uint32(40).bool(message.noProcessing);
    }
    if (message.processingStartedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.processingStartedAt), writer.uint32(58).fork()).join();
    }
    if (message.data !== undefined) {
      ProcessingItemData.encode(message.data, writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProcessingItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProcessingItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = ProcessingItemKey.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nextProcessing = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.lastProcessed = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.lastError = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.noProcessing = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.processingStartedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.data = ProcessingItemData.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProcessingItem {
    return {
      key: isSet(object.key) ? ProcessingItemKey.fromJSON(object.key) : undefined,
      nextProcessing: isSet(object.nextProcessing) ? fromJsonTimestamp(object.nextProcessing) : undefined,
      lastProcessed: isSet(object.lastProcessed) ? fromJsonTimestamp(object.lastProcessed) : undefined,
      lastError: isSet(object.lastError) ? gt.String(object.lastError) : undefined,
      noProcessing: isSet(object.noProcessing) ? gt.Boolean(object.noProcessing) : false,
      processingStartedAt: isSet(object.processingStartedAt)
        ? fromJsonTimestamp(object.processingStartedAt)
        : undefined,
      data: isSet(object.data) ? ProcessingItemData.fromJSON(object.data) : undefined,
    };
  },

  toJSON(message: ProcessingItem): unknown {
    const obj: any = {};
    if (message.key !== undefined) {
      obj.key = ProcessingItemKey.toJSON(message.key);
    }
    if (message.nextProcessing !== undefined) {
      obj.nextProcessing = message.nextProcessing.toISOString();
    }
    if (message.lastProcessed !== undefined) {
      obj.lastProcessed = message.lastProcessed.toISOString();
    }
    if (message.lastError !== undefined) {
      obj.lastError = message.lastError;
    }
    if (message.noProcessing !== false) {
      obj.noProcessing = message.noProcessing;
    }
    if (message.processingStartedAt !== undefined) {
      obj.processingStartedAt = message.processingStartedAt.toISOString();
    }
    if (message.data !== undefined) {
      obj.data = ProcessingItemData.toJSON(message.data);
    }
    return obj;
  },

  create(base?: DeepPartial<ProcessingItem>): ProcessingItem {
    return ProcessingItem.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ProcessingItem>): ProcessingItem {
    const message = createBaseProcessingItem();
    message.key = (object.key !== undefined && object.key !== null)
      ? ProcessingItemKey.fromPartial(object.key)
      : undefined;
    message.nextProcessing = object.nextProcessing ?? undefined;
    message.lastProcessed = object.lastProcessed ?? undefined;
    message.lastError = object.lastError ?? undefined;
    message.noProcessing = object.noProcessing ?? false;
    message.processingStartedAt = object.processingStartedAt ?? undefined;
    message.data = (object.data !== undefined && object.data !== null)
      ? ProcessingItemData.fromPartial(object.data)
      : undefined;
    return message;
  },
};

function createBasePeriodicAggregation(): PeriodicAggregation {
  return { params: undefined, schedule: undefined };
}

export const PeriodicAggregation: MessageFns<PeriodicAggregation> = {
  encode(message: PeriodicAggregation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.params !== undefined) {
      AggregatedSummaryParams.encode(message.params, writer.uint32(10).fork()).join();
    }
    if (message.schedule !== undefined) {
      Schedule.encode(message.schedule, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PeriodicAggregation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePeriodicAggregation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.params = AggregatedSummaryParams.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.schedule = Schedule.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PeriodicAggregation {
    return {
      params: isSet(object.params) ? AggregatedSummaryParams.fromJSON(object.params) : undefined,
      schedule: isSet(object.schedule) ? Schedule.fromJSON(object.schedule) : undefined,
    };
  },

  toJSON(message: PeriodicAggregation): unknown {
    const obj: any = {};
    if (message.params !== undefined) {
      obj.params = AggregatedSummaryParams.toJSON(message.params);
    }
    if (message.schedule !== undefined) {
      obj.schedule = Schedule.toJSON(message.schedule);
    }
    return obj;
  },

  create(base?: DeepPartial<PeriodicAggregation>): PeriodicAggregation {
    return PeriodicAggregation.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<PeriodicAggregation>): PeriodicAggregation {
    const message = createBasePeriodicAggregation();
    message.params = (object.params !== undefined && object.params !== null)
      ? AggregatedSummaryParams.fromPartial(object.params)
      : undefined;
    message.schedule = (object.schedule !== undefined && object.schedule !== null)
      ? Schedule.fromPartial(object.schedule)
      : undefined;
    return message;
  },
};

function createBaseAggregatedSummaryParams(): AggregatedSummaryParams {
  return { lookBackDays: 0, endDate: undefined, target: undefined };
}

export const AggregatedSummaryParams: MessageFns<AggregatedSummaryParams> = {
  encode(message: AggregatedSummaryParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.lookBackDays !== 0) {
      writer.uint32(8).int32(message.lookBackDays);
    }
    if (message.endDate !== undefined) {
      Timestamp.encode(toTimestamp(message.endDate), writer.uint32(18).fork()).join();
    }
    if (message.target !== undefined) {
      AggregatedSummaryParams_Target.encode(message.target, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AggregatedSummaryParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAggregatedSummaryParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.lookBackDays = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.endDate = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.target = AggregatedSummaryParams_Target.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AggregatedSummaryParams {
    return {
      lookBackDays: isSet(object.lookBackDays) ? gt.Number(object.lookBackDays) : 0,
      endDate: isSet(object.endDate) ? fromJsonTimestamp(object.endDate) : undefined,
      target: isSet(object.target) ? AggregatedSummaryParams_Target.fromJSON(object.target) : undefined,
    };
  },

  toJSON(message: AggregatedSummaryParams): unknown {
    const obj: any = {};
    if (message.lookBackDays !== 0) {
      obj.lookBackDays = Math.round(message.lookBackDays);
    }
    if (message.endDate !== undefined) {
      obj.endDate = message.endDate.toISOString();
    }
    if (message.target !== undefined) {
      obj.target = AggregatedSummaryParams_Target.toJSON(message.target);
    }
    return obj;
  },

  create(base?: DeepPartial<AggregatedSummaryParams>): AggregatedSummaryParams {
    return AggregatedSummaryParams.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AggregatedSummaryParams>): AggregatedSummaryParams {
    const message = createBaseAggregatedSummaryParams();
    message.lookBackDays = object.lookBackDays ?? 0;
    message.endDate = object.endDate ?? undefined;
    message.target = (object.target !== undefined && object.target !== null)
      ? AggregatedSummaryParams_Target.fromPartial(object.target)
      : undefined;
    return message;
  },
};

function createBaseAggregatedSummaryParams_Target(): AggregatedSummaryParams_Target {
  return { gitRepoIds: [] };
}

export const AggregatedSummaryParams_Target: MessageFns<AggregatedSummaryParams_Target> = {
  encode(message: AggregatedSummaryParams_Target, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.gitRepoIds) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AggregatedSummaryParams_Target {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAggregatedSummaryParams_Target();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.gitRepoIds.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AggregatedSummaryParams_Target {
    return { gitRepoIds: gt.Array.isArray(object?.gitRepoIds) ? object.gitRepoIds.map((e: any) => gt.String(e)) : [] };
  },

  toJSON(message: AggregatedSummaryParams_Target): unknown {
    const obj: any = {};
    if (message.gitRepoIds?.length) {
      obj.gitRepoIds = message.gitRepoIds;
    }
    return obj;
  },

  create(base?: DeepPartial<AggregatedSummaryParams_Target>): AggregatedSummaryParams_Target {
    return AggregatedSummaryParams_Target.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AggregatedSummaryParams_Target>): AggregatedSummaryParams_Target {
    const message = createBaseAggregatedSummaryParams_Target();
    message.gitRepoIds = object.gitRepoIds?.map((e) => e) || [];
    return message;
  },
};

function createBaseProcessingRequest(): ProcessingRequest {
  return { type: undefined };
}

export const ProcessingRequest: MessageFns<ProcessingRequest> = {
  encode(message: ProcessingRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    switch (message.type?.$case) {
      case "gitChanges":
        ProcessGitChangesRequest.encode(message.type.value, writer.uint32(802).fork()).join();
        break;
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProcessingRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProcessingRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 100: {
          if (tag !== 802) {
            break;
          }

          message.type = { $case: "gitChanges", value: ProcessGitChangesRequest.decode(reader, reader.uint32()) };
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProcessingRequest {
    return {
      type: isSet(object.gitChanges)
        ? { $case: "gitChanges", value: ProcessGitChangesRequest.fromJSON(object.gitChanges) }
        : undefined,
    };
  },

  toJSON(message: ProcessingRequest): unknown {
    const obj: any = {};
    if (message.type?.$case === "gitChanges") {
      obj.gitChanges = ProcessGitChangesRequest.toJSON(message.type.value);
    }
    return obj;
  },

  create(base?: DeepPartial<ProcessingRequest>): ProcessingRequest {
    return ProcessingRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ProcessingRequest>): ProcessingRequest {
    const message = createBaseProcessingRequest();
    switch (object.type?.$case) {
      case "gitChanges": {
        if (object.type?.value !== undefined && object.type?.value !== null) {
          message.type = { $case: "gitChanges", value: ProcessGitChangesRequest.fromPartial(object.type.value) };
        }
        break;
      }
    }
    return message;
  },
};

function createBaseProcessGitChangesRequest(): ProcessGitChangesRequest {
  return { gitRepoId: "", lookBackDays: 0 };
}

export const ProcessGitChangesRequest: MessageFns<ProcessGitChangesRequest> = {
  encode(message: ProcessGitChangesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.gitRepoId !== "") {
      writer.uint32(10).string(message.gitRepoId);
    }
    if (message.lookBackDays !== 0) {
      writer.uint32(16).int32(message.lookBackDays);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProcessGitChangesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProcessGitChangesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.gitRepoId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.lookBackDays = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProcessGitChangesRequest {
    return {
      gitRepoId: isSet(object.gitRepoId) ? gt.String(object.gitRepoId) : "",
      lookBackDays: isSet(object.lookBackDays) ? gt.Number(object.lookBackDays) : 0,
    };
  },

  toJSON(message: ProcessGitChangesRequest): unknown {
    const obj: any = {};
    if (message.gitRepoId !== "") {
      obj.gitRepoId = message.gitRepoId;
    }
    if (message.lookBackDays !== 0) {
      obj.lookBackDays = Math.round(message.lookBackDays);
    }
    return obj;
  },

  create(base?: DeepPartial<ProcessGitChangesRequest>): ProcessGitChangesRequest {
    return ProcessGitChangesRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ProcessGitChangesRequest>): ProcessGitChangesRequest {
    const message = createBaseProcessGitChangesRequest();
    message.gitRepoId = object.gitRepoId ?? "";
    message.lookBackDays = object.lookBackDays ?? 0;
    return message;
  },
};

function createBaseProcessingItemResult(): ProcessingItemResult {
  return {
    id: "",
    key: undefined,
    errorMessage: undefined,
    createdAt: undefined,
    data: undefined,
    resultData: undefined,
  };
}

export const ProcessingItemResult: MessageFns<ProcessingItemResult> = {
  encode(message: ProcessingItemResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.key !== undefined) {
      ProcessingItemKey.encode(message.key, writer.uint32(18).fork()).join();
    }
    if (message.errorMessage !== undefined) {
      writer.uint32(34).string(message.errorMessage);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(42).fork()).join();
    }
    if (message.data !== undefined) {
      ProcessingItemData.encode(message.data, writer.uint32(58).fork()).join();
    }
    if (message.resultData !== undefined) {
      ProcessingItemResultData.encode(message.resultData, writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProcessingItemResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProcessingItemResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.key = ProcessingItemKey.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.data = ProcessingItemData.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.resultData = ProcessingItemResultData.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProcessingItemResult {
    return {
      id: isSet(object.id) ? gt.String(object.id) : "",
      key: isSet(object.key) ? ProcessingItemKey.fromJSON(object.key) : undefined,
      errorMessage: isSet(object.errorMessage) ? gt.String(object.errorMessage) : undefined,
      createdAt: isSet(object.createdAt) ? fromJsonTimestamp(object.createdAt) : undefined,
      data: isSet(object.data) ? ProcessingItemData.fromJSON(object.data) : undefined,
      resultData: isSet(object.resultData) ? ProcessingItemResultData.fromJSON(object.resultData) : undefined,
    };
  },

  toJSON(message: ProcessingItemResult): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.key !== undefined) {
      obj.key = ProcessingItemKey.toJSON(message.key);
    }
    if (message.errorMessage !== undefined) {
      obj.errorMessage = message.errorMessage;
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    if (message.data !== undefined) {
      obj.data = ProcessingItemData.toJSON(message.data);
    }
    if (message.resultData !== undefined) {
      obj.resultData = ProcessingItemResultData.toJSON(message.resultData);
    }
    return obj;
  },

  create(base?: DeepPartial<ProcessingItemResult>): ProcessingItemResult {
    return ProcessingItemResult.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ProcessingItemResult>): ProcessingItemResult {
    const message = createBaseProcessingItemResult();
    message.id = object.id ?? "";
    message.key = (object.key !== undefined && object.key !== null)
      ? ProcessingItemKey.fromPartial(object.key)
      : undefined;
    message.errorMessage = object.errorMessage ?? undefined;
    message.createdAt = object.createdAt ?? undefined;
    message.data = (object.data !== undefined && object.data !== null)
      ? ProcessingItemData.fromPartial(object.data)
      : undefined;
    message.resultData = (object.resultData !== undefined && object.resultData !== null)
      ? ProcessingItemResultData.fromPartial(object.resultData)
      : undefined;
    return message;
  },
};

function createBaseRepoObservation(): RepoObservation {
  return { repoId: "", observations: [] };
}

export const RepoObservation: MessageFns<RepoObservation> = {
  encode(message: RepoObservation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.repoId !== "") {
      writer.uint32(10).string(message.repoId);
    }
    for (const v of message.observations) {
      ObservationKey.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RepoObservation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRepoObservation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.repoId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.observations.push(ObservationKey.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RepoObservation {
    return {
      repoId: isSet(object.repoId) ? gt.String(object.repoId) : "",
      observations: gt.Array.isArray(object?.observations)
        ? object.observations.map((e: any) => ObservationKey.fromJSON(e))
        : [],
    };
  },

  toJSON(message: RepoObservation): unknown {
    const obj: any = {};
    if (message.repoId !== "") {
      obj.repoId = message.repoId;
    }
    if (message.observations?.length) {
      obj.observations = message.observations.map((e) => ObservationKey.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<RepoObservation>): RepoObservation {
    return RepoObservation.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RepoObservation>): RepoObservation {
    const message = createBaseRepoObservation();
    message.repoId = object.repoId ?? "";
    message.observations = object.observations?.map((e) => ObservationKey.fromPartial(e)) || [];
    return message;
  },
};

function createBasePeriodicAggregationResult(): PeriodicAggregationResult {
  return { repoObservations: [] };
}

export const PeriodicAggregationResult: MessageFns<PeriodicAggregationResult> = {
  encode(message: PeriodicAggregationResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.repoObservations) {
      RepoObservation.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PeriodicAggregationResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePeriodicAggregationResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.repoObservations.push(RepoObservation.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PeriodicAggregationResult {
    return {
      repoObservations: gt.Array.isArray(object?.repoObservations)
        ? object.repoObservations.map((e: any) => RepoObservation.fromJSON(e))
        : [],
    };
  },

  toJSON(message: PeriodicAggregationResult): unknown {
    const obj: any = {};
    if (message.repoObservations?.length) {
      obj.repoObservations = message.repoObservations.map((e) => RepoObservation.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<PeriodicAggregationResult>): PeriodicAggregationResult {
    return PeriodicAggregationResult.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<PeriodicAggregationResult>): PeriodicAggregationResult {
    const message = createBasePeriodicAggregationResult();
    message.repoObservations = object.repoObservations?.map((e) => RepoObservation.fromPartial(e)) || [];
    return message;
  },
};

function createBaseProcessingItemData(): ProcessingItemData {
  return { referenceId: undefined, namespace: undefined, createdBy: undefined, type: undefined };
}

export const ProcessingItemData: MessageFns<ProcessingItemData> = {
  encode(message: ProcessingItemData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.referenceId !== undefined) {
      writer.uint32(10).string(message.referenceId);
    }
    if (message.namespace !== undefined) {
      writer.uint32(18).string(message.namespace);
    }
    if (message.createdBy !== undefined) {
      writer.uint32(26).string(message.createdBy);
    }
    switch (message.type?.$case) {
      case "request":
        ProcessingRequest.encode(message.type.value, writer.uint32(802).fork()).join();
        break;
      case "periodicAggregation":
        PeriodicAggregation.encode(message.type.value, writer.uint32(810).fork()).join();
        break;
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProcessingItemData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProcessingItemData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.referenceId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.namespace = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.createdBy = reader.string();
          continue;
        }
        case 100: {
          if (tag !== 802) {
            break;
          }

          message.type = { $case: "request", value: ProcessingRequest.decode(reader, reader.uint32()) };
          continue;
        }
        case 101: {
          if (tag !== 810) {
            break;
          }

          message.type = { $case: "periodicAggregation", value: PeriodicAggregation.decode(reader, reader.uint32()) };
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProcessingItemData {
    return {
      referenceId: isSet(object.referenceId) ? gt.String(object.referenceId) : undefined,
      namespace: isSet(object.namespace) ? gt.String(object.namespace) : undefined,
      createdBy: isSet(object.createdBy) ? gt.String(object.createdBy) : undefined,
      type: isSet(object.request)
        ? { $case: "request", value: ProcessingRequest.fromJSON(object.request) }
        : isSet(object.periodicAggregation)
        ? { $case: "periodicAggregation", value: PeriodicAggregation.fromJSON(object.periodicAggregation) }
        : undefined,
    };
  },

  toJSON(message: ProcessingItemData): unknown {
    const obj: any = {};
    if (message.referenceId !== undefined) {
      obj.referenceId = message.referenceId;
    }
    if (message.namespace !== undefined) {
      obj.namespace = message.namespace;
    }
    if (message.createdBy !== undefined) {
      obj.createdBy = message.createdBy;
    }
    if (message.type?.$case === "request") {
      obj.request = ProcessingRequest.toJSON(message.type.value);
    } else if (message.type?.$case === "periodicAggregation") {
      obj.periodicAggregation = PeriodicAggregation.toJSON(message.type.value);
    }
    return obj;
  },

  create(base?: DeepPartial<ProcessingItemData>): ProcessingItemData {
    return ProcessingItemData.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ProcessingItemData>): ProcessingItemData {
    const message = createBaseProcessingItemData();
    message.referenceId = object.referenceId ?? undefined;
    message.namespace = object.namespace ?? undefined;
    message.createdBy = object.createdBy ?? undefined;
    switch (object.type?.$case) {
      case "request": {
        if (object.type?.value !== undefined && object.type?.value !== null) {
          message.type = { $case: "request", value: ProcessingRequest.fromPartial(object.type.value) };
        }
        break;
      }
      case "periodicAggregation": {
        if (object.type?.value !== undefined && object.type?.value !== null) {
          message.type = { $case: "periodicAggregation", value: PeriodicAggregation.fromPartial(object.type.value) };
        }
        break;
      }
    }
    return message;
  },
};

function createBaseProcessingItemResultData(): ProcessingItemResultData {
  return { observations: [], type: undefined };
}

export const ProcessingItemResultData: MessageFns<ProcessingItemResultData> = {
  encode(message: ProcessingItemResultData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.observations) {
      ObservationKey.encode(v!, writer.uint32(10).fork()).join();
    }
    switch (message.type?.$case) {
      case "periodicAggregation":
        PeriodicAggregationResult.encode(message.type.value, writer.uint32(802).fork()).join();
        break;
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProcessingItemResultData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProcessingItemResultData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.observations.push(ObservationKey.decode(reader, reader.uint32()));
          continue;
        }
        case 100: {
          if (tag !== 802) {
            break;
          }

          message.type = {
            $case: "periodicAggregation",
            value: PeriodicAggregationResult.decode(reader, reader.uint32()),
          };
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProcessingItemResultData {
    return {
      observations: gt.Array.isArray(object?.observations)
        ? object.observations.map((e: any) => ObservationKey.fromJSON(e))
        : [],
      type: isSet(object.periodicAggregation)
        ? { $case: "periodicAggregation", value: PeriodicAggregationResult.fromJSON(object.periodicAggregation) }
        : undefined,
    };
  },

  toJSON(message: ProcessingItemResultData): unknown {
    const obj: any = {};
    if (message.observations?.length) {
      obj.observations = message.observations.map((e) => ObservationKey.toJSON(e));
    }
    if (message.type?.$case === "periodicAggregation") {
      obj.periodicAggregation = PeriodicAggregationResult.toJSON(message.type.value);
    }
    return obj;
  },

  create(base?: DeepPartial<ProcessingItemResultData>): ProcessingItemResultData {
    return ProcessingItemResultData.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ProcessingItemResultData>): ProcessingItemResultData {
    const message = createBaseProcessingItemResultData();
    message.observations = object.observations?.map((e) => ObservationKey.fromPartial(e)) || [];
    switch (object.type?.$case) {
      case "periodicAggregation": {
        if (object.type?.value !== undefined && object.type?.value !== null) {
          message.type = {
            $case: "periodicAggregation",
            value: PeriodicAggregationResult.fromPartial(object.type.value),
          };
        }
        break;
      }
    }
    return message;
  },
};

function createBaseProcessingResultFilter(): ProcessingResultFilter {
  return { namespace: undefined, referenceId: undefined, requestType: undefined, keys: [] };
}

export const ProcessingResultFilter: MessageFns<ProcessingResultFilter> = {
  encode(message: ProcessingResultFilter, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.namespace !== undefined) {
      writer.uint32(10).string(message.namespace);
    }
    if (message.referenceId !== undefined) {
      writer.uint32(18).string(message.referenceId);
    }
    if (message.requestType !== undefined) {
      writer.uint32(26).string(message.requestType);
    }
    for (const v of message.keys) {
      ProcessingItemKey.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProcessingResultFilter {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProcessingResultFilter();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.namespace = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.referenceId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.requestType = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.keys.push(ProcessingItemKey.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProcessingResultFilter {
    return {
      namespace: isSet(object.namespace) ? gt.String(object.namespace) : undefined,
      referenceId: isSet(object.referenceId) ? gt.String(object.referenceId) : undefined,
      requestType: isSet(object.requestType) ? gt.String(object.requestType) : undefined,
      keys: gt.Array.isArray(object?.keys) ? object.keys.map((e: any) => ProcessingItemKey.fromJSON(e)) : [],
    };
  },

  toJSON(message: ProcessingResultFilter): unknown {
    const obj: any = {};
    if (message.namespace !== undefined) {
      obj.namespace = message.namespace;
    }
    if (message.referenceId !== undefined) {
      obj.referenceId = message.referenceId;
    }
    if (message.requestType !== undefined) {
      obj.requestType = message.requestType;
    }
    if (message.keys?.length) {
      obj.keys = message.keys.map((e) => ProcessingItemKey.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<ProcessingResultFilter>): ProcessingResultFilter {
    return ProcessingResultFilter.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ProcessingResultFilter>): ProcessingResultFilter {
    const message = createBaseProcessingResultFilter();
    message.namespace = object.namespace ?? undefined;
    message.referenceId = object.referenceId ?? undefined;
    message.requestType = object.requestType ?? undefined;
    message.keys = object.keys?.map((e) => ProcessingItemKey.fromPartial(e)) || [];
    return message;
  },
};

function createBaseProcessingItemsFilter(): ProcessingItemsFilter {
  return { namespace: undefined, referenceId: undefined, requestType: undefined, keys: [] };
}

export const ProcessingItemsFilter: MessageFns<ProcessingItemsFilter> = {
  encode(message: ProcessingItemsFilter, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.namespace !== undefined) {
      writer.uint32(10).string(message.namespace);
    }
    if (message.referenceId !== undefined) {
      writer.uint32(18).string(message.referenceId);
    }
    if (message.requestType !== undefined) {
      writer.uint32(26).string(message.requestType);
    }
    for (const v of message.keys) {
      ProcessingItemKey.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProcessingItemsFilter {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProcessingItemsFilter();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.namespace = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.referenceId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.requestType = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.keys.push(ProcessingItemKey.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProcessingItemsFilter {
    return {
      namespace: isSet(object.namespace) ? gt.String(object.namespace) : undefined,
      referenceId: isSet(object.referenceId) ? gt.String(object.referenceId) : undefined,
      requestType: isSet(object.requestType) ? gt.String(object.requestType) : undefined,
      keys: gt.Array.isArray(object?.keys) ? object.keys.map((e: any) => ProcessingItemKey.fromJSON(e)) : [],
    };
  },

  toJSON(message: ProcessingItemsFilter): unknown {
    const obj: any = {};
    if (message.namespace !== undefined) {
      obj.namespace = message.namespace;
    }
    if (message.referenceId !== undefined) {
      obj.referenceId = message.referenceId;
    }
    if (message.requestType !== undefined) {
      obj.requestType = message.requestType;
    }
    if (message.keys?.length) {
      obj.keys = message.keys.map((e) => ProcessingItemKey.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<ProcessingItemsFilter>): ProcessingItemsFilter {
    return ProcessingItemsFilter.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ProcessingItemsFilter>): ProcessingItemsFilter {
    const message = createBaseProcessingItemsFilter();
    message.namespace = object.namespace ?? undefined;
    message.referenceId = object.referenceId ?? undefined;
    message.requestType = object.requestType ?? undefined;
    message.keys = object.keys?.map((e) => ProcessingItemKey.fromPartial(e)) || [];
    return message;
  },
};

declare const self: any | undefined;
declare const window: any | undefined;
declare const global: any | undefined;
const gt: any = (() => {
  if (typeof globalThis !== "undefined") {
    return globalThis;
  }
  if (typeof self !== "undefined") {
    return self;
  }
  if (typeof window !== "undefined") {
    return window;
  }
  if (typeof global !== "undefined") {
    return global;
  }
  throw "Unable to locate global object";
})();

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string; value: unknown } ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new gt.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof gt.Date) {
    return o;
  } else if (typeof o === "string") {
    return new gt.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
