[git]
provider="copying"

[git.github]
auth_type = "token"

[analysis]
provider="stub"

[tokenizer]
provider="stub"

[prompts]
provider = "local"
[prompts.local]
dir = "scripts/dev/prompts"

[storage]
provider = "local"
#provider = "postgresql"
[storage.local]
dir = "scripts/dev/_local_data_/__storage"

[storage.postgresql]
db_url="postgresql+asyncpg://postgres:test_password@localhost:54322/dev_observer"

[users_management]
provider="none"
#provider="clerk"

#[users_management.clerk]
#public_key="<PUBLIC CLERK KEY GOES HERE>"

[api_keys]
keys=["test-api-key"]

[observations.local]
dir = "scripts/dev/_local_data_"