[system]
text ='''You will be given combined analysis of different parts of a website. Combine that into a single cohesive description without loosing any important details.
'''
[user]
text = '''Here are the summaries of different chunks of a website:

{{content}}
'''
[config.model]
provider="google_genai"
model_name="gemini-2.0-flash-lite"
temperature=0.1
